// @generated by Cratis. Source: Planner.Repositories.Organizations.Adding.AddOrganization. Time: 2026-08-08T17:09:59.4947360Z. Hash: 0CCD8BD2EFBE6A815079192364D15D13568552F7DDE05F60AE5D8B82B2A15D05
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command, CommandValidator } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';

/**
 * Command for adding a GitHub organization whose repositories the Planner should track.
 */
export interface IAddOrganization {
    
    /**
     * The name of the organization.
     */
    name?: string;
}

export class AddOrganizationValidator extends CommandValidator<IAddOrganization> {
    constructor() {
        super();
        this.ruleFor(c => c.name).notEmpty().withMessage('An organization name is required');
    }
}

/**
 * Command for adding a GitHub organization whose repositories the Planner should track.
 */
export class AddOrganization extends Command<IAddOrganization, string> implements IAddOrganization {
    readonly route: string = '/api/repositories/organizations/adding';
    readonly validation: CommandValidator = new AddOrganizationValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('name', String, false),
    ];

    private _name!: string;

    constructor() {
        super(String, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The name of the organization.
     */
    get name(): string {
        return this._name;
    }

    set name(value: string) {
        this._name = value;
        this.propertyChanged('name');
    }

    static use(initialValues?: IAddOrganization): [AddOrganization, SetCommandValues<IAddOrganization>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<AddOrganization, IAddOrganization>(AddOrganization, initialValues);
    }
}
