// @generated by Cratis. Source: Planner.Repositories.Organizations.Adding.AddOrganization. Time: 2026-08-19T16:32:25.3218460Z. Hash: C86D35FDDBACEB7892C4C2C5DFA61358B3ACE2EDB3666F03B994D2828B94D65B
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command, CommandValidator } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { OrganizationTrackingPolicy } from '../OrganizationTrackingPolicy';

/**
 * Command for adding a GitHub organization whose repositories the Planner should track.
 */
export interface IAddOrganization {
    
    /**
     * The name of the organization.
     */
    name?: string;
    
    /**
     * Whether every repository is tracked automatically, or only ones explicitly selected after discovery - defaults to {@link All}, the existing behavior.
     */
    trackingPolicy?: OrganizationTrackingPolicy;
}

export class AddOrganizationValidator extends CommandValidator<IAddOrganization> {
    constructor() {
        super();
        this.ruleFor(c => c.name).notEmpty().withMessage('An organization name is required');
    }
}

/**
 * Command for adding a GitHub organization whose repositories the Planner should track.
 */
export class AddOrganization extends Command<IAddOrganization, string> implements IAddOrganization {
    readonly route: string = '/api/repositories/organizations/adding';
    readonly validation: CommandValidator = new AddOrganizationValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('name', String, false),
        new PropertyDescriptor('trackingPolicy', Number, false),
    ];

    private _name!: string;
    private _trackingPolicy!: OrganizationTrackingPolicy;

    constructor() {
        super(String, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The name of the organization.
     */
    get name(): string {
        return this._name;
    }

    set name(value: string) {
        this._name = value;
        this.propertyChanged('name');
    }
    /**
     * Whether every repository is tracked automatically, or only ones explicitly selected after discovery - defaults to {@link All}, the existing behavior.
     */
    get trackingPolicy(): OrganizationTrackingPolicy {
        return this._trackingPolicy;
    }

    set trackingPolicy(value: OrganizationTrackingPolicy) {
        this._trackingPolicy = value;
        this.propertyChanged('trackingPolicy');
    }

    static use(initialValues?: IAddOrganization): [AddOrganization, SetCommandValues<IAddOrganization>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<AddOrganization, IAddOrganization>(AddOrganization, initialValues);
    }
}
