// @generated by Cratis. Source: Planner.Issues.Reopening.ReopenIssue, Planner.Issues.Reopening.IssueReopened. Time: 2026-08-08T17:17:47.5182270Z. Hash: 4BF799EF5B94E09BE3EBB05CF738791D928D377FC17180A234EA3ED4F93A0D24
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';

/**
 * Command for reopening an issue - mirroring the issue being reopened on GitHub.
 */
export interface IReopenIssue {
    
    /**
     * The identity of the issue.
     */
    issue?: string;
}


/**
 * Command for reopening an issue - mirroring the issue being reopened on GitHub.
 */
export class ReopenIssue extends Command<IReopenIssue, IssueReopened> implements IReopenIssue {
    readonly route: string = '/api/issues/reopening';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('issue', String, false),
    ];

    private _issue!: string;

    constructor() {
        super(IssueReopened, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The identity of the issue.
     */
    get issue(): string {
        return this._issue;
    }

    set issue(value: string) {
        this._issue = value;
        this.propertyChanged('issue');
    }

    static use(initialValues?: IReopenIssue): [ReopenIssue, SetCommandValues<IReopenIssue>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<ReopenIssue, IReopenIssue>(ReopenIssue, initialValues);
    }
}

/**
 * Event raised when an issue has been reopened on GitHub.
 */
export class IssueReopened {
}
