// @generated by Cratis. Source: Planner.Repositories.Removing.RemoveRepository, Planner.Repositories.Removing.RepositoryRemoved. Time: 2026-08-08T17:09:59.4947360Z. Hash: E887BB909FFF474B6807A0DD64F33F28DC4C6A2E8FCA5C549D600F7D0254E34B
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';

/**
 * Command for removing a repository from the Planner.
 */
export interface IRemoveRepository {
    
    /**
     * The identity of the repository to remove.
     */
    repository?: string;
}


/**
 * Command for removing a repository from the Planner.
 */
export class RemoveRepository extends Command<IRemoveRepository, RepositoryRemoved> implements IRemoveRepository {
    readonly route: string = '/api/repositories/removing';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('repository', String, false),
    ];

    private _repository!: string;

    constructor() {
        super(RepositoryRemoved, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The identity of the repository to remove.
     */
    get repository(): string {
        return this._repository;
    }

    set repository(value: string) {
        this._repository = value;
        this.propertyChanged('repository');
    }

    static use(initialValues?: IRemoveRepository): [RemoveRepository, SetCommandValues<IRemoveRepository>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<RemoveRepository, IRemoveRepository>(RemoveRepository, initialValues);
    }
}

/**
 * Event raised when a repository has been removed - its issues are no longer mirrored.
 */
export class RepositoryRemoved {
}
