// @generated by Cratis. Source: Planner.Issues.Comments.Replying.ReplyToIssue. Time: 2026-08-19T15:49:08.5315340Z. Hash: 9F1A7A42A2D3A09FE3CFC2546F857D7DB7A405F9CE4FA3BDE4EE1933E2580A68
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command, CommandValidator } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';

/**
 * Command for replying to an issue from the Planner's inbox - posts the comment to GitHub as the Planner's own identity, attributed to the signed-in user, since the Planner authenticates as a GitHub App rather than as the person. The mirror then picks the comment back up through the regular `issue_comment` webhook, so it shows up on the issue like any other.
 */
export interface IReplyToIssue {
    
    /**
     * The identity of the issue to reply to.
     */
    issue?: string;
    
    /**
     * The markdown body of the reply.
     */
    text?: string;
}

export class ReplyToIssueValidator extends CommandValidator<IReplyToIssue> {
    constructor() {
        super();
        this.ruleFor(c => c.text).notEmpty().withMessage('A reply needs some text');
    }
}

/**
 * Command for replying to an issue from the Planner's inbox - posts the comment to GitHub as the Planner's own identity, attributed to the signed-in user, since the Planner authenticates as a GitHub App rather than as the person. The mirror then picks the comment back up through the regular `issue_comment` webhook, so it shows up on the issue like any other.
 */
export class ReplyToIssue extends Command<IReplyToIssue> implements IReplyToIssue {
    readonly route: string = '/api/issues/comments/replying';
    readonly validation: CommandValidator = new ReplyToIssueValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('issue', String, false),
        new PropertyDescriptor('text', String, false),
    ];

    private _issue!: string;
    private _text!: string;

    constructor() {
        super(Object, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The identity of the issue to reply to.
     */
    get issue(): string {
        return this._issue;
    }

    set issue(value: string) {
        this._issue = value;
        this.propertyChanged('issue');
    }
    /**
     * The markdown body of the reply.
     */
    get text(): string {
        return this._text;
    }

    set text(value: string) {
        this._text = value;
        this.propertyChanged('text');
    }

    static use(initialValues?: IReplyToIssue): [ReplyToIssue, SetCommandValues<IReplyToIssue>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<ReplyToIssue, IReplyToIssue>(ReplyToIssue, initialValues);
    }
}
