// @generated by Cratis. Source: Planner.Issues.Listing.Issue, Planner.Issues.Listing.Issue. Time: 2026-08-08T17:17:47.5182270Z. Hash: CB4447571BFBC08A23C266ADFEB81F92EE04C51F378BEF5FAD7A848566D2F2D4
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { ObservableQueryFor, QueryResultWithState, Sorting, Paging, ChangeSet } from '@cratis/arc/queries';
import { useObservableQuery, useObservableQueryWithPaging, useSuspenseObservableQuery, useSuspenseObservableQueryWithPaging, useChangeStream, SetSorting, SetPage, SetPageSize, ObservableQueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { field } from '@cratis/fundamentals';
import { AuthorAssociation } from '../../Common/AuthorAssociation';
import { IssueStatus } from '../IssueStatus';

class AllIssuesSortBy {

    constructor(readonly query: AllIssues) {
    }

}

class AllIssuesSortByWithoutQuery {

}


/**
 * Observes all issues across every tracked repository.
 */
export class AllIssues extends ObservableQueryFor<Issue[]> {
    readonly route: string = '/api/issues/listing/all-issues';
    readonly queryName: string = 'Planner.Issues.Listing.Issue.AllIssues';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: Issue[] = [];
    private readonly _sortBy: AllIssuesSortBy;
    private static readonly _sortBy: AllIssuesSortByWithoutQuery = new AllIssuesSortByWithoutQuery();

    constructor() {
        super(Issue, true);
        this._sortBy = new AllIssuesSortBy(this);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];


    get sortBy(): AllIssuesSortBy {
        return this._sortBy;
    }

    static get sortBy(): AllIssuesSortByWithoutQuery {
        return this._sortBy;
    }

    static use(sorting?: Sorting): [QueryResultWithState<Issue[]>, SetSorting] {
        return useObservableQuery<Issue[], AllIssues>(AllIssues, undefined, sorting);
    }

    static useWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<Issue[]>, SetSorting, SetPage, SetPageSize] {
        return useObservableQueryWithPaging<Issue[], AllIssues>(AllIssues, new Paging(0, pageSize), undefined, sorting);
    }

    static useSuspense(sorting?: Sorting): [QueryResultWithState<Issue[]>, SetSorting] {
        return useSuspenseObservableQuery<Issue[], AllIssues>(AllIssues, undefined, sorting);
    }

    static useSuspenseWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<Issue[]>, SetSorting, SetPage, SetPageSize] {
        return useSuspenseObservableQueryWithPaging<Issue[], AllIssues>(AllIssues, new Paging(0, pageSize), undefined, sorting);
    }

    static useChangeStream(getKey?: (item: Issue) => unknown, sorting?: Sorting): ChangeSet<Issue> {
        return useChangeStream<Issue, AllIssues>(AllIssues, undefined, getKey, sorting);
    }

    static when(condition: boolean): ObservableQueryWhen<AllIssues, Issue[]> {
        return new ObservableQueryWhen<AllIssues, Issue[]>(AllIssues, condition);
    }
}

/**
 * Read model for the issue list - the vitals of every mirrored issue together with the Planner's own status, grouping, ordering, pull request and investigation state.
 */
export class Issue {

    /**
     * The issue identity - the predictable `{org}-{repo}-{issue}` key.
     */
    @field(String)
    id!: string;

    /**
     * The organization owning the repository the issue lives in.
     */
    @field(String)
    owner!: string;

    /**
     * The repository the issue lives in.
     */
    @field(String)
    repository!: string;

    /**
     * The issue number.
     */
    @field(Number)
    number!: number;

    /**
     * The issue title.
     */
    @field(String)
    title!: string;

    /**
     * The issue type as classified on GitHub.
     */
    @field(String)
    type!: string;

    /**
     * The login of the user that created the issue.
     */
    @field(String)
    createdBy!: string;

    /**
     * When the issue was created on GitHub.
     */
    @field(Date)
    createdAt!: Date;

    /**
     * The author's association with the repository.
     */
    @field(Number)
    authorAssociation!: AuthorAssociation;

    /**
     * Whether the issue is open on GitHub.
     */
    @field(Boolean)
    isOpen!: boolean;

    /**
     * The Planner's internal status.
     */
    @field(Number)
    status!: IssueStatus;

    /**
     * The manual sort position - `null` until the issue has been dragged.
     */
    @field(Number)
    order?: number;

    /**
     * The group the issue belongs to - `null` when ungrouped.
     */
    @field(String)
    group?: string;

    /**
     * The associated pull request number - `null` until work produced one.
     */
    @field(Number)
    pullRequest?: number;

    /**
     * The associated pull request URL.
     */
    @field(String)
    pullRequestUrl?: string;

    /**
     * The organization owning the repository the pull request was opened in.
     */
    @field(String)
    pullRequestOwner?: string;

    /**
     * The repository the pull request was opened in.
     */
    @field(String)
    pullRequestRepository?: string;

    /**
     * The investigation summary - `null` until investigated.
     */
    @field(String)
    investigation?: string;

    /**
     * The model an investigation suggested for implementing the issue.
     */
    @field(String)
    suggestedModel?: string;
}
