// @generated by Cratis. Source: Planner.PullRequests.Reopening.ReopenPullRequest, Planner.PullRequests.Reopening.PullRequestReopened. Time: 2026-08-09T09:18:49.3333770Z. Hash: 63F35244C01353533B814A939970F7BE09450164037D79A74282B7FD160695D4
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';

/**
 * Command for reopening a pull request mirrored from GitHub - executed by the webhook receiver when a previously closed pull request is reopened.
 */
export interface IReopenPullRequest {
    
    /**
     * The identity of the pull request.
     */
    pullRequest?: string;
}


/**
 * Command for reopening a pull request mirrored from GitHub - executed by the webhook receiver when a previously closed pull request is reopened.
 */
export class ReopenPullRequest extends Command<IReopenPullRequest, PullRequestReopened> implements IReopenPullRequest {
    readonly route: string = '/api/pull-requests/reopening';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('pullRequest', String, false),
    ];

    private _pullRequest!: string;

    constructor() {
        super(PullRequestReopened, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The identity of the pull request.
     */
    get pullRequest(): string {
        return this._pullRequest;
    }

    set pullRequest(value: string) {
        this._pullRequest = value;
        this.propertyChanged('pullRequest');
    }

    static use(initialValues?: IReopenPullRequest): [ReopenPullRequest, SetCommandValues<IReopenPullRequest>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<ReopenPullRequest, IReopenPullRequest>(ReopenPullRequest, initialValues);
    }
}

/**
 * Event raised when a pull request mirrored from GitHub has been reopened.
 */
export class PullRequestReopened {
}
