// @generated by Cratis. Source: Planner.Issues.RecordingInvestigation.RecordInvestigation, Planner.Issues.RecordingInvestigation.IssueInvestigated. Time: 2026-08-08T17:17:47.5182270Z. Hash: 16855E77A3000916C348FE0A37033E76DB913A929D8D220780367FAFC50638F5
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command, CommandValidator } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { field } from '@cratis/fundamentals';

/**
 * Command for recording the outcome of an investigation of an issue - the plan for how it can be implemented and the model suggested for doing the work.
 */
export interface IRecordInvestigation {
    
    /**
     * The identity of the issue.
     */
    issue?: string;
    
    /**
     * The model the investigation suggests for implementing the issue.
     */
    suggestedModel?: string;
    
    /**
     * The markdown summary of the investigation.
     */
    summary?: string;
}

export class RecordInvestigationValidator extends CommandValidator<IRecordInvestigation> {
    constructor() {
        super();
        this.ruleFor(c => c.summary).notEmpty().withMessage('An investigation summary is required');
    }
}

/**
 * Command for recording the outcome of an investigation of an issue - the plan for how it can be implemented and the model suggested for doing the work.
 */
export class RecordInvestigation extends Command<IRecordInvestigation, IssueInvestigated> implements IRecordInvestigation {
    readonly route: string = '/api/issues/recording-investigation';
    readonly validation: CommandValidator = new RecordInvestigationValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('issue', String, false),
        new PropertyDescriptor('suggestedModel', String, false),
        new PropertyDescriptor('summary', String, false),
    ];

    private _issue!: string;
    private _suggestedModel!: string;
    private _summary!: string;

    constructor() {
        super(IssueInvestigated, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The identity of the issue.
     */
    get issue(): string {
        return this._issue;
    }

    set issue(value: string) {
        this._issue = value;
        this.propertyChanged('issue');
    }
    /**
     * The model the investigation suggests for implementing the issue.
     */
    get suggestedModel(): string {
        return this._suggestedModel;
    }

    set suggestedModel(value: string) {
        this._suggestedModel = value;
        this.propertyChanged('suggestedModel');
    }
    /**
     * The markdown summary of the investigation.
     */
    get summary(): string {
        return this._summary;
    }

    set summary(value: string) {
        this._summary = value;
        this.propertyChanged('summary');
    }

    static use(initialValues?: IRecordInvestigation): [RecordInvestigation, SetCommandValues<IRecordInvestigation>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<RecordInvestigation, IRecordInvestigation>(RecordInvestigation, initialValues);
    }
}

/**
 * Event raised when an issue has been investigated by an agent - it holds the implementation plan and which model the investigation suggests for doing the work, used when scheduling.
 */
export class IssueInvestigated {

    /**
     * The markdown summary of the investigation.
     */
    @field(String)
    summary!: string;

    /**
     * The model suggested for implementing the issue.
     */
    @field(String)
    suggestedModel!: string;
}
