// @generated by Cratis. Source: Planner.Alerts.AddingNote.AddAlertNote, Planner.Alerts.AddingNote.AlertNoteAdded. Time: 2026-08-10T15:01:02.9193540Z. Hash: D3E7549C12919A630D9180BE6C8C6F4F5B1DB190746FA7C7F96F4A5AA55A8588
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { field, Guid } from '@cratis/fundamentals';

/**
 * Command for recording what someone found out about an alert on the way to resolving it - the detail that accumulates between an agent handing an alert over and a person closing it.
 */
export interface IAddAlertNote {
    
    /**
     * The identity of the alert.
     */
    alert?: string;
    
    /**
     * What to record.
     */
    text?: string;
}


/**
 * Command for recording what someone found out about an alert on the way to resolving it - the detail that accumulates between an agent handing an alert over and a person closing it.
 */
export class AddAlertNote extends Command<IAddAlertNote, AlertNoteAdded> implements IAddAlertNote {
    readonly route: string = '/api/alerts/adding-note';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('alert', String, false),
        new PropertyDescriptor('text', String, false),
    ];

    private _alert!: string;
    private _text!: string;

    constructor() {
        super(AlertNoteAdded, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The identity of the alert.
     */
    get alert(): string {
        return this._alert;
    }

    set alert(value: string) {
        this._alert = value;
        this.propertyChanged('alert');
    }
    /**
     * What to record.
     */
    get text(): string {
        return this._text;
    }

    set text(value: string) {
        this._text = value;
        this.propertyChanged('text');
    }

    static use(initialValues?: IAddAlertNote): [AddAlertNote, SetCommandValues<IAddAlertNote>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<AddAlertNote, IAddAlertNote>(AddAlertNote, initialValues);
    }
}

/**
 * Event raised when a note has been recorded against an alert.
 */
export class AlertNoteAdded {

    /**
     * The identity of the note.
     */
    @field(Guid)
    note!: Guid;

    /**
     * What was recorded.
     */
    @field(String)
    text!: string;

    /**
     * The login of the user that recorded it - {@link NotSet} for automation.
     */
    @field(String)
    addedBy!: string;
}
