// @generated by Cratis. Source: Planner.WeeklyDigests.GeneratingDescription.GenerateWeeklyDigestDescription, Planner.WeeklyDigests.GeneratingDescription.SetWeeklyDigestDescription, Planner.WeeklyDigests.GeneratingDescription.WeeklyDigestDescriptionGenerated, Planner.WeeklyDigests.GeneratingDescription.WeeklyDigestDescriptionEdited. Time: 2026-08-19T16:16:25.3642610Z. Hash: C2B1C2584E3BAF9DB221368F80237DC21790FD9DB0401F4F66B1D88EA98E5012
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command, CommandValidator } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { Guid, field } from '@cratis/fundamentals';

/**
 * Command for recording the language model's suggested description of a weekly digest - executed by the weekly digest analysis reactor. Once this fires the digest moves to {@link Unpublished} - ready for review.
 */
export interface IGenerateWeeklyDigestDescription {
    
    /**
     * The suggested description.
     */
    description?: string;
    
    /**
     * The identity of the weekly digest.
     */
    weeklyDigest?: Guid;
}


/**
 * Command for recording the language model's suggested description of a weekly digest - executed by the weekly digest analysis reactor. Once this fires the digest moves to {@link Unpublished} - ready for review.
 */
export class GenerateWeeklyDigestDescription extends Command<IGenerateWeeklyDigestDescription, WeeklyDigestDescriptionGenerated> implements IGenerateWeeklyDigestDescription {
    readonly route: string = '/api/weekly-digests/generating-description/generate-weekly-digest-description';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('description', String, false),
        new PropertyDescriptor('weeklyDigest', Guid, false),
    ];

    private _description!: string;
    private _weeklyDigest!: Guid;

    constructor() {
        super(WeeklyDigestDescriptionGenerated, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The suggested description.
     */
    get description(): string {
        return this._description;
    }

    set description(value: string) {
        this._description = value;
        this.propertyChanged('description');
    }
    /**
     * The identity of the weekly digest.
     */
    get weeklyDigest(): Guid {
        return this._weeklyDigest;
    }

    set weeklyDigest(value: Guid) {
        this._weeklyDigest = value;
        this.propertyChanged('weeklyDigest');
    }

    static use(initialValues?: IGenerateWeeklyDigestDescription): [GenerateWeeklyDigestDescription, SetCommandValues<IGenerateWeeklyDigestDescription>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<GenerateWeeklyDigestDescription, IGenerateWeeklyDigestDescription>(GenerateWeeklyDigestDescription, initialValues);
    }
}

/**
 * Command for editing the description of a weekly digest - a person overriding what the language model suggested, or writing one when none was generated.
 */
export interface ISetWeeklyDigestDescription {
    
    /**
     * The description to set.
     */
    description?: string;
    
    /**
     * The identity of the weekly digest.
     */
    weeklyDigest?: Guid;
}

export class SetWeeklyDigestDescriptionValidator extends CommandValidator<ISetWeeklyDigestDescription> {
    constructor() {
        super();
        this.ruleFor(c => c.description).notEmpty().withMessage('A description is required');
    }
}

/**
 * Command for editing the description of a weekly digest - a person overriding what the language model suggested, or writing one when none was generated.
 */
export class SetWeeklyDigestDescription extends Command<ISetWeeklyDigestDescription, WeeklyDigestDescriptionEdited> implements ISetWeeklyDigestDescription {
    readonly route: string = '/api/weekly-digests/generating-description/set-weekly-digest-description';
    readonly validation: CommandValidator = new SetWeeklyDigestDescriptionValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('description', String, false),
        new PropertyDescriptor('weeklyDigest', Guid, false),
    ];

    private _description!: string;
    private _weeklyDigest!: Guid;

    constructor() {
        super(WeeklyDigestDescriptionEdited, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The description to set.
     */
    get description(): string {
        return this._description;
    }

    set description(value: string) {
        this._description = value;
        this.propertyChanged('description');
    }
    /**
     * The identity of the weekly digest.
     */
    get weeklyDigest(): Guid {
        return this._weeklyDigest;
    }

    set weeklyDigest(value: Guid) {
        this._weeklyDigest = value;
        this.propertyChanged('weeklyDigest');
    }

    static use(initialValues?: ISetWeeklyDigestDescription): [SetWeeklyDigestDescription, SetCommandValues<ISetWeeklyDigestDescription>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<SetWeeklyDigestDescription, ISetWeeklyDigestDescription>(SetWeeklyDigestDescription, initialValues);
    }
}

/**
 * Event raised when the language model has suggested a description for a weekly digest.
 */
export class WeeklyDigestDescriptionGenerated {

    /**
     * The suggested description.
     */
    @field(String)
    description!: string;
}

/**
 * Event raised when a person edited the description of a weekly digest.
 */
export class WeeklyDigestDescriptionEdited {

    /**
     * The description that was set.
     */
    @field(String)
    description!: string;
}
