// @generated by Cratis. Source: Planner.Accounts.Removing.RemoveAccount, Planner.Accounts.Removing.ClaudeAccountRemoved. Time: 2026-08-08T17:20:55.2325870Z. Hash: DD881F3B4BAE0519603E9E1FA282324B673EB4AA9409320D8BB7322631829880
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { Guid } from '@cratis/fundamentals';

/**
 * Command for removing a Claude account - no further work is scheduled on it.
 */
export interface IRemoveAccount {
    
    /**
     * The identity of the account to remove.
     */
    account?: Guid;
}


/**
 * Command for removing a Claude account - no further work is scheduled on it.
 */
export class RemoveAccount extends Command<IRemoveAccount, ClaudeAccountRemoved> implements IRemoveAccount {
    readonly route: string = '/api/accounts/removing';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('account', Guid, false),
    ];

    private _account!: Guid;

    constructor() {
        super(ClaudeAccountRemoved, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The identity of the account to remove.
     */
    get account(): Guid {
        return this._account;
    }

    set account(value: Guid) {
        this._account = value;
        this.propertyChanged('account');
    }

    static use(initialValues?: IRemoveAccount): [RemoveAccount, SetCommandValues<IRemoveAccount>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<RemoveAccount, IRemoveAccount>(RemoveAccount, initialValues);
    }
}

/**
 * Event raised when a Claude account has been removed.
 */
export class ClaudeAccountRemoved {
}
