// @generated by Cratis. Source: Planner.Issues.Grouping.Renaming.RenameGroup, Planner.Issues.Grouping.Renaming.GroupRenamed. Time: 2026-08-08T21:11:05.5434570Z. Hash: 78FB5231FC6A14B3C0473BA1F3EEBE525951099DD91E3BCA666A75FF6ECBA146
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command, CommandValidator } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { field } from '@cratis/fundamentals';

/**
 * Command for renaming a group of issues.
 */
export interface IRenameGroup {
    
    /**
     * The identity of the group.
     */
    group?: string;
    
    /**
     * The new display name.
     */
    name?: string;
}

export class RenameGroupValidator extends CommandValidator<IRenameGroup> {
    constructor() {
        super();
        this.ruleFor(c => c.name).notEmpty().withMessage('A group name is required');
    }
}

/**
 * Command for renaming a group of issues.
 */
export class RenameGroup extends Command<IRenameGroup, GroupRenamed> implements IRenameGroup {
    readonly route: string = '/api/issues/grouping/renaming';
    readonly validation: CommandValidator = new RenameGroupValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('group', String, false),
        new PropertyDescriptor('name', String, false),
    ];

    private _group!: string;
    private _name!: string;

    constructor() {
        super(GroupRenamed, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The identity of the group.
     */
    get group(): string {
        return this._group;
    }

    set group(value: string) {
        this._group = value;
        this.propertyChanged('group');
    }
    /**
     * The new display name.
     */
    get name(): string {
        return this._name;
    }

    set name(value: string) {
        this._name = value;
        this.propertyChanged('name');
    }

    static use(initialValues?: IRenameGroup): [RenameGroup, SetCommandValues<IRenameGroup>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<RenameGroup, IRenameGroup>(RenameGroup, initialValues);
    }
}

/**
 * Event raised when a group of issues has been renamed.
 */
export class GroupRenamed {

    /**
     * The new display name.
     */
    @field(String)
    name!: string;
}
