// @generated by Cratis. Source: Planner.Roadmap.PlanStatus. Time: 2026-08-19T16:55:58.0712010Z. Hash: 0615B39963828AF5A90DCF499425D4416C94B45F9E9CF12AF6CC7558E3C6BCE1
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

// eslint-disable-next-line header/header
/**
 * Where a plan stands.
 */
export enum PlanStatus {
    generating = 0,
    ready = 1,
    failed = 2,
}
