// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System.Text;

namespace Planner.Work.Workers;

/// <summary>
/// The contract for how credentials reach a worker container - as a file the entrypoint sources,
/// never as environment variables on the container specification.
/// </summary>
/// <remarks>
/// Anything on the container specification is readable by whoever can read the specification:
/// <c>kubectl get job -o yaml</c> in the worker namespace, or <c>docker inspect</c> on the host.
/// It also outlives the container, because the specification does. Both runtimes therefore deliver
/// secrets out of band - Kubernetes through a mounted <c>Secret</c>, Docker through a tmpfs file
/// copied in after the container starts - and both land on exactly this contract, so the entrypoint
/// has one code path rather than one per runtime.
/// </remarks>
public static class WorkerSecrets
{
    /// <summary>
    /// The directory secrets are delivered into inside the container.
    /// </summary>
    public const string Directory = "/run/planner-secrets";

    /// <summary>
    /// The name of the file carrying the secrets, as shell assignments.
    /// </summary>
    public const string FileName = "secrets.env";

    /// <summary>
    /// The name of the marker written once the secrets file is complete.
    /// </summary>
    /// <remarks>
    /// The Docker runtime copies the file in after the container has started, so the entrypoint can
    /// observe a partially extracted file. The marker is written last and is what the entrypoint
    /// actually waits for - the secrets file existing is not proof that it is complete.
    /// </remarks>
    public const string ReadyFileName = "secrets.ready";

    /// <summary>
    /// The full path of the secrets file inside the container.
    /// </summary>
    public const string Path = $"{Directory}/{FileName}";

    /// <summary>
    /// The full path of the readiness marker inside the container.
    /// </summary>
    public const string ReadyPath = $"{Directory}/{ReadyFileName}";

    /// <summary>
    /// The environment variable naming the secrets file for the entrypoint. It carries a path, not a
    /// credential, so it is safe on the container specification.
    /// </summary>
    public const string PathVariableName = "PLANNER_SECRETS_FILE";

    /// <summary>
    /// Renders secrets as a POSIX shell script the entrypoint sources.
    /// </summary>
    /// <param name="secrets">The secrets to render, keyed by environment variable name.</param>
    /// <returns>The file content.</returns>
    /// <exception cref="InvalidWorkerSecretName">Thrown when a name is not a usable shell variable name.</exception>
    /// <remarks>
    /// Values are single quoted with the only escape a single-quoted shell string has - ending the
    /// quote, emitting an escaped quote, and reopening it. That keeps multi-line values intact, which
    /// matters because a kubeconfig is YAML, and it means no value can terminate its own assignment
    /// and be read as script by the shell that sources the file.
    /// </remarks>
    public static string Render(IReadOnlyDictionary<string, string> secrets)
    {
        var builder = new StringBuilder();
        builder.Append("# Generated by the Cratis Planner - sourced by the worker entrypoint.\n");
        foreach (var (name, value) in secrets.OrderBy(secret => secret.Key, StringComparer.Ordinal))
        {
            ThrowIfNotAUsableName(name);
            builder.Append(name).Append("='").Append(value.Replace("'", "'\\''")).Append("'\n");
        }

        return builder.ToString();
    }

    static void ThrowIfNotAUsableName(string name)
    {
        if (name.Length == 0 || (!char.IsAsciiLetter(name[0]) && name[0] != '_'))
        {
            throw new InvalidWorkerSecretName(name);
        }

        foreach (var character in name)
        {
            if (!char.IsAsciiLetterOrDigit(character) && character != '_')
            {
                throw new InvalidWorkerSecretName(name);
            }
        }
    }
}

/// <summary>
/// Exception that gets thrown when a secret is named something the shell cannot assign to.
/// </summary>
/// <param name="name">The offending name.</param>
public class InvalidWorkerSecretName(string name)
    : Exception($"'{name}' is not a usable environment variable name for a worker secret.");
