// @generated by Cratis. Source: Planner.Alerts.RecordingInvestigation.StartAlertInvestigation, Planner.Alerts.RecordingInvestigation.ConcludeAlertInvestigation, Planner.Alerts.RecordingInvestigation.FailAlertInvestigation, Planner.Alerts.RecordingInvestigation.AlertInvestigationStarted, Planner.Alerts.RecordingInvestigation.AlertInvestigationFailed. Time: 2026-08-10T15:01:02.9193540Z. Hash: DE360BDFFFEA5237E924E47CAA8A8CE6DD05E2991F0E393C4511C603EB731341
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { Guid, field } from '@cratis/fundamentals';
import { AlertInvestigationOutcome } from '../AlertInvestigationOutcome';

/**
 * Command for recording that an agent has picked an alert up - executed when the unit of work investigating it starts running.
 */
export interface IStartAlertInvestigation {
    
    /**
     * The identity of the alert.
     */
    alert?: string;
    
    /**
     * The unit of work investigating it, so the alert can link to its console.
     */
    work?: Guid;
}


/**
 * Command for recording that an agent has picked an alert up - executed when the unit of work investigating it starts running.
 */
export class StartAlertInvestigation extends Command<IStartAlertInvestigation, AlertInvestigationStarted> implements IStartAlertInvestigation {
    readonly route: string = '/api/alerts/recording-investigation/start-alert-investigation';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('alert', String, false),
        new PropertyDescriptor('work', Guid, false),
    ];

    private _alert!: string;
    private _work!: Guid;

    constructor() {
        super(AlertInvestigationStarted, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The identity of the alert.
     */
    get alert(): string {
        return this._alert;
    }

    set alert(value: string) {
        this._alert = value;
        this.propertyChanged('alert');
    }
    /**
     * The unit of work investigating it, so the alert can link to its console.
     */
    get work(): Guid {
        return this._work;
    }

    set work(value: Guid) {
        this._work = value;
        this.propertyChanged('work');
    }

    static use(initialValues?: IStartAlertInvestigation): [StartAlertInvestigation, SetCommandValues<IStartAlertInvestigation>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<StartAlertInvestigation, IStartAlertInvestigation>(StartAlertInvestigation, initialValues);
    }
}

/**
 * Command for recording what an agent concluded about an alert.
 */
export interface IConcludeAlertInvestigation {
    
    /**
     * The identity of the alert.
     */
    alert?: string;
    
    /**
     * What the agent found, and what it did about it.
     */
    findings?: string;
    
    /**
     * Whether the agent resolved it or needs a person to take over.
     */
    outcome?: AlertInvestigationOutcome;
}


/**
 * Command for recording what an agent concluded about an alert.
 */
export class ConcludeAlertInvestigation extends Command<IConcludeAlertInvestigation, Record<string, unknown>> implements IConcludeAlertInvestigation {
    readonly route: string = '/api/alerts/recording-investigation/conclude-alert-investigation';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('alert', String, false),
        new PropertyDescriptor('findings', String, false),
        new PropertyDescriptor('outcome', Number, false),
    ];

    private _alert!: string;
    private _findings!: string;
    private _outcome!: AlertInvestigationOutcome;

    constructor() {
        super(Object, true);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The identity of the alert.
     */
    get alert(): string {
        return this._alert;
    }

    set alert(value: string) {
        this._alert = value;
        this.propertyChanged('alert');
    }
    /**
     * What the agent found, and what it did about it.
     */
    get findings(): string {
        return this._findings;
    }

    set findings(value: string) {
        this._findings = value;
        this.propertyChanged('findings');
    }
    /**
     * Whether the agent resolved it or needs a person to take over.
     */
    get outcome(): AlertInvestigationOutcome {
        return this._outcome;
    }

    set outcome(value: AlertInvestigationOutcome) {
        this._outcome = value;
        this.propertyChanged('outcome');
    }

    static use(initialValues?: IConcludeAlertInvestigation): [ConcludeAlertInvestigation, SetCommandValues<IConcludeAlertInvestigation>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<ConcludeAlertInvestigation, IConcludeAlertInvestigation>(ConcludeAlertInvestigation, initialValues);
    }
}

/**
 * Command for recording that the investigation of an alert never produced a conclusion - the agent's session failed or was stopped.
 */
export interface IFailAlertInvestigation {
    
    /**
     * The identity of the alert.
     */
    alert?: string;
    
    /**
     * Why the investigation did not conclude.
     */
    reason?: string;
}


/**
 * Command for recording that the investigation of an alert never produced a conclusion - the agent's session failed or was stopped.
 */
export class FailAlertInvestigation extends Command<IFailAlertInvestigation, AlertInvestigationFailed> implements IFailAlertInvestigation {
    readonly route: string = '/api/alerts/recording-investigation/fail-alert-investigation';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('alert', String, false),
        new PropertyDescriptor('reason', String, false),
    ];

    private _alert!: string;
    private _reason!: string;

    constructor() {
        super(AlertInvestigationFailed, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The identity of the alert.
     */
    get alert(): string {
        return this._alert;
    }

    set alert(value: string) {
        this._alert = value;
        this.propertyChanged('alert');
    }
    /**
     * Why the investigation did not conclude.
     */
    get reason(): string {
        return this._reason;
    }

    set reason(value: string) {
        this._reason = value;
        this.propertyChanged('reason');
    }

    static use(initialValues?: IFailAlertInvestigation): [FailAlertInvestigation, SetCommandValues<IFailAlertInvestigation>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<FailAlertInvestigation, IFailAlertInvestigation>(FailAlertInvestigation, initialValues);
    }
}

/**
 * Event raised when an agent started investigating an alert.
 */
export class AlertInvestigationStarted {

    /**
     * The unit of work doing the investigating.
     */
    @field(Guid)
    work!: Guid;
}

/**
 * Event raised when the investigation of an alert never produced a conclusion.
 */
export class AlertInvestigationFailed {

    /**
     * Why the investigation did not conclude.
     */
    @field(String)
    reason!: string;
}
