// @generated by Cratis. Source: Planner.Identity.for_DenyByDefaultAuthorization.when_executing_through_the_real_pipeline.given.AnonymousTestCommand, Planner.Identity.for_DenyByDefaultAuthorization.when_executing_through_the_real_pipeline.given.AnonymousTestCommandAccepted. Time: 2026-08-18T13:29:02.5413530Z. Hash: EA7C1B2F70314970EAF14E049FD7E182D6538413429FD807346BA24D697C0011
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';

/**
 * A command-shaped type that opts out of authorization - proving {@link DenyByDefaultAuthorization} does not interfere with a genuine {@link AllowAnonymousAttribute} escape hatch, should the Planner ever need one. No production command uses it today.
 */
export interface IAnonymousTestCommand {
}


/**
 * A command-shaped type that opts out of authorization - proving {@link DenyByDefaultAuthorization} does not interfere with a genuine {@link AllowAnonymousAttribute} escape hatch, should the Planner ever need one. No production command uses it today.
 */
export class AnonymousTestCommand extends Command<IAnonymousTestCommand, AnonymousTestCommandAccepted> implements IAnonymousTestCommand {
    readonly route: string = '/api/identity/for-deny-by-default-authorization/when-executing-through-the-real-pipeline/given';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
    ];


    constructor() {
        super(AnonymousTestCommandAccepted, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }


    static use(initialValues?: IAnonymousTestCommand): [AnonymousTestCommand, SetCommandValues<IAnonymousTestCommand>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<AnonymousTestCommand, IAnonymousTestCommand>(AnonymousTestCommand, initialValues);
    }
}

/**
 * Emitted when {@link AnonymousTestCommand} is accepted - test-only, proves nothing about production behavior beyond the [AllowAnonymous] escape hatch itself.
 */
export class AnonymousTestCommandAccepted {
}
