// @generated by Cratis. Source: Planner.Repositories.Groups.Listing.RepositoryGroup, Planner.Repositories.Groups.Listing.RepositoryGroup. Time: 2026-08-08T21:11:05.5434570Z. Hash: 1A3C45E08CCC0C4874211ED7D3CF00FBE501A4B7CFA22807A90533C6042B5729
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { ObservableQueryFor, QueryResultWithState, Sorting, Paging, ChangeSet } from '@cratis/arc/queries';
import { useObservableQuery, useObservableQueryWithPaging, useSuspenseObservableQuery, useSuspenseObservableQueryWithPaging, useChangeStream, SetSorting, SetPage, SetPageSize, ObservableQueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { field, Guid } from '@cratis/fundamentals';

class AllRepositoryGroupsSortBy {

    constructor(readonly query: AllRepositoryGroups) {
    }

}

class AllRepositoryGroupsSortByWithoutQuery {

}


/**
 * Observes all repository groups.
 */
export class AllRepositoryGroups extends ObservableQueryFor<RepositoryGroup[]> {
    readonly route: string = '/api/repositories/groups/listing/all-repository-groups';
    readonly queryName: string = 'Planner.Repositories.Groups.Listing.RepositoryGroup.AllRepositoryGroups';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: RepositoryGroup[] = [];
    private readonly _sortBy: AllRepositoryGroupsSortBy;
    private static readonly _sortBy: AllRepositoryGroupsSortByWithoutQuery = new AllRepositoryGroupsSortByWithoutQuery();

    constructor() {
        super(RepositoryGroup, true);
        this._sortBy = new AllRepositoryGroupsSortBy(this);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];


    get sortBy(): AllRepositoryGroupsSortBy {
        return this._sortBy;
    }

    static get sortBy(): AllRepositoryGroupsSortByWithoutQuery {
        return this._sortBy;
    }

    static use(sorting?: Sorting): [QueryResultWithState<RepositoryGroup[]>, SetSorting] {
        return useObservableQuery<RepositoryGroup[], AllRepositoryGroups>(AllRepositoryGroups, undefined, sorting);
    }

    static useWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<RepositoryGroup[]>, SetSorting, SetPage, SetPageSize] {
        return useObservableQueryWithPaging<RepositoryGroup[], AllRepositoryGroups>(AllRepositoryGroups, new Paging(0, pageSize), undefined, sorting);
    }

    static useSuspense(sorting?: Sorting): [QueryResultWithState<RepositoryGroup[]>, SetSorting] {
        return useSuspenseObservableQuery<RepositoryGroup[], AllRepositoryGroups>(AllRepositoryGroups, undefined, sorting);
    }

    static useSuspenseWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<RepositoryGroup[]>, SetSorting, SetPage, SetPageSize] {
        return useSuspenseObservableQueryWithPaging<RepositoryGroup[], AllRepositoryGroups>(AllRepositoryGroups, new Paging(0, pageSize), undefined, sorting);
    }

    static useChangeStream(getKey?: (item: RepositoryGroup) => unknown, sorting?: Sorting): ChangeSet<RepositoryGroup> {
        return useChangeStream<RepositoryGroup, AllRepositoryGroups>(AllRepositoryGroups, undefined, getKey, sorting);
    }

    static when(condition: boolean): ObservableQueryWhen<AllRepositoryGroups, RepositoryGroup[]> {
        return new ObservableQueryWhen<AllRepositoryGroups, RepositoryGroup[]>(AllRepositoryGroups, condition);
    }
}

/**
 * Read model for listing the named repository groups.
 */
export class RepositoryGroup {

    /**
     * The group identity.
     */
    @field(Guid)
    id!: Guid;

    /**
     * The display name of the group.
     */
    @field(String)
    name!: string;

    /**
     * The identities of the repositories in the group.
     */
    @field(String, true)
    repositories!: string[];
}
