// @generated by Cratis. Source: Planner.Repositories.Listing.Repository, Planner.Repositories.Listing.Repository, Planner.Repositories.Listing.Repository. Time: 2026-08-08T17:10:23.5744380Z. Hash: 2283CC99379990F2B6E577EBC73F84A5CD2AC55AFD224B5AD43927CF59142A21
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { QueryFor, QueryResultWithState, ObservableQueryFor, Sorting, Paging, ChangeSet } from '@cratis/arc/queries';
import { useQuery, useSuspenseQuery, PerformQuery, SetSorting, QueryWhen, useObservableQuery, useObservableQueryWithPaging, useSuspenseObservableQuery, useSuspenseObservableQueryWithPaging, useChangeStream, SetPage, SetPageSize, ObservableQueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { field } from '@cratis/fundamentals';

/**
 * Gets a single repository by its identity. The model carries {@link RemovedWithAttribute}, so an unknown or removed repository resolves to a default-initialized instance - check for an empty {@link Owner} rather than `null`.
 */
export interface RepositoryByIdParameters {
    
    /**
     * The repository identity.
    */
    id: string;
}


/**
 * Gets a single repository by its identity. The model carries {@link RemovedWithAttribute}, so an unknown or removed repository resolves to a default-initialized instance - check for an empty {@link Owner} rather than `null`.
 */
export class RepositoryById extends QueryFor<Repository, RepositoryByIdParameters> {
    readonly route: string = '/api/repositories/listing/repository-by-id';
    readonly queryName: string = 'Planner.Repositories.Listing.Repository.RepositoryById';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: Repository = {} as any;

    constructor() {
        super(Repository, false);
    }

    get requiredRequestParameters(): string[] {
        return [
            'id',
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
        new ParameterDescriptor('id', String, false),
    ];

    id!: string;


    static use(args?: RepositoryByIdParameters): [QueryResultWithState<Repository>, PerformQuery<RepositoryByIdParameters>, SetSorting] {
        return useQuery<Repository, RepositoryById, RepositoryByIdParameters>(RepositoryById, args);
    }

    static useSuspense(args?: RepositoryByIdParameters): [QueryResultWithState<Repository>, PerformQuery<RepositoryByIdParameters>, SetSorting] {
        return useSuspenseQuery<Repository, RepositoryById, RepositoryByIdParameters>(RepositoryById, args);
    }

    static when(condition: boolean): QueryWhen<RepositoryById, Repository, RepositoryByIdParameters> {
        return new QueryWhen<RepositoryById, Repository, RepositoryByIdParameters>(RepositoryById, condition);
    }
}

class AllRepositoriesSortBy {

    constructor(readonly query: AllRepositories) {
    }

}

class AllRepositoriesSortByWithoutQuery {

}


/**
 * Observes all tracked repositories.
 */
export class AllRepositories extends ObservableQueryFor<Repository[]> {
    readonly route: string = '/api/repositories/listing/all-repositories';
    readonly queryName: string = 'Planner.Repositories.Listing.Repository.AllRepositories';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: Repository[] = [];
    private readonly _sortBy: AllRepositoriesSortBy;
    private static readonly _sortBy: AllRepositoriesSortByWithoutQuery = new AllRepositoriesSortByWithoutQuery();

    constructor() {
        super(Repository, true);
        this._sortBy = new AllRepositoriesSortBy(this);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];


    get sortBy(): AllRepositoriesSortBy {
        return this._sortBy;
    }

    static get sortBy(): AllRepositoriesSortByWithoutQuery {
        return this._sortBy;
    }

    static use(sorting?: Sorting): [QueryResultWithState<Repository[]>, SetSorting] {
        return useObservableQuery<Repository[], AllRepositories>(AllRepositories, undefined, sorting);
    }

    static useWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<Repository[]>, SetSorting, SetPage, SetPageSize] {
        return useObservableQueryWithPaging<Repository[], AllRepositories>(AllRepositories, new Paging(0, pageSize), undefined, sorting);
    }

    static useSuspense(sorting?: Sorting): [QueryResultWithState<Repository[]>, SetSorting] {
        return useSuspenseObservableQuery<Repository[], AllRepositories>(AllRepositories, undefined, sorting);
    }

    static useSuspenseWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<Repository[]>, SetSorting, SetPage, SetPageSize] {
        return useSuspenseObservableQueryWithPaging<Repository[], AllRepositories>(AllRepositories, new Paging(0, pageSize), undefined, sorting);
    }

    static useChangeStream(getKey?: (item: Repository) => unknown, sorting?: Sorting): ChangeSet<Repository> {
        return useChangeStream<Repository, AllRepositories>(AllRepositories, undefined, getKey, sorting);
    }

    static when(condition: boolean): ObservableQueryWhen<AllRepositories, Repository[]> {
        return new ObservableQueryWhen<AllRepositories, Repository[]>(AllRepositories, condition);
    }
}

/**
 * Read model for listing the repositories the Planner tracks.
 */
export class Repository {

    /**
     * The repository identity.
     */
    @field(String)
    id!: string;

    /**
     * The organization owning the repository.
     */
    @field(String)
    owner!: string;

    /**
     * The name of the repository.
     */
    @field(String)
    name!: string;

    /**
     * The organization owning the mapped code repository - `null` when the code lives in the repository itself.
     */
    @field(String)
    codeOwner?: string;

    /**
     * The name of the mapped code repository - `null` when the code lives in the repository itself.
     */
    @field(String)
    codeName?: string;
}
