// @generated by Cratis. Source: Planner.Issues.AcceptingPullRequest.AcceptPullRequest, Planner.Issues.AcceptingPullRequest.PullRequestMerged. Time: 2026-08-08T17:17:47.5182270Z. Hash: 7A1E841843C08A079F3FAFEE1E0BB24DD7574B49EEA9E0EB6F9DEFD03821190A
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { field } from '@cratis/fundamentals';

/**
 * Command for accepting the pull request associated with an issue - merges it through the GitHub API.
 */
export interface IAcceptPullRequest {
    
    /**
     * The identity of the issue whose pull request is accepted.
     */
    issue?: string;
}


/**
 * Command for accepting the pull request associated with an issue - merges it through the GitHub API.
 */
export class AcceptPullRequest extends Command<IAcceptPullRequest, PullRequestMerged> implements IAcceptPullRequest {
    readonly route: string = '/api/issues/accepting-pull-request';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('issue', String, false),
    ];

    private _issue!: string;

    constructor() {
        super(PullRequestMerged, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The identity of the issue whose pull request is accepted.
     */
    get issue(): string {
        return this._issue;
    }

    set issue(value: string) {
        this._issue = value;
        this.propertyChanged('issue');
    }

    static use(initialValues?: IAcceptPullRequest): [AcceptPullRequest, SetCommandValues<IAcceptPullRequest>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<AcceptPullRequest, IAcceptPullRequest>(AcceptPullRequest, initialValues);
    }
}

/**
 * Event raised when the pull request associated with an issue has been merged through the Planner.
 */
export class PullRequestMerged {

    /**
     * The number of the merged pull request.
     */
    @field(Number)
    number!: number;
}
