// @generated by Cratis. Source: Planner.Common.AuthorAssociation. Time: 2026-08-08T17:17:47.5182270Z. Hash: 13D73432DA3C1CC7E3E4867CA1AD96C8959D64328EAE9F9600CEE42F3D657BF7
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

// eslint-disable-next-line header/header
/**
 * The association an issue author has with the repository the issue was created in, mirroring GitHub's `author_association` values.
 */
export enum AuthorAssociation {
    none = 0,
    owner = 1,
    member = 2,
    collaborator = 3,
    contributor = 4,
    external = 5,
}
