// @generated by Cratis. Source: Planner.Accounts.Usage.AccountUsage, Planner.Accounts.Usage.AccountUsage. Time: 2026-08-08T21:11:05.5434570Z. Hash: DF8A890853284FEF30D34556758901DCA2B769168A97B3980D91E97FBDD4FC64
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { QueryFor, QueryResultWithState, Sorting, Paging } from '@cratis/arc/queries';
import { useQuery, useQueryWithPaging, useSuspenseQuery, useSuspenseQueryWithPaging, PerformQuery, SetSorting, SetPage, SetPageSize, QueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { field, Guid } from '@cratis/fundamentals';
import { ClaudePlan } from '../ClaudePlan';

class AllAccountUsageSortBy {

    constructor(readonly query: AllAccountUsage) {
    }

}

class AllAccountUsageSortByWithoutQuery {

}


/**
 * Gets the usage statistics for every Claude account.
 */
export class AllAccountUsage extends QueryFor<AccountUsage[]> {
    readonly route: string = '/api/accounts/usage/all-account-usage';
    readonly queryName: string = 'Planner.Accounts.Usage.AccountUsage.AllAccountUsage';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: AccountUsage[] = [];
    private readonly _sortBy: AllAccountUsageSortBy;
    private static readonly _sortBy: AllAccountUsageSortByWithoutQuery = new AllAccountUsageSortByWithoutQuery();

    constructor() {
        super(AccountUsage, true);
        this._sortBy = new AllAccountUsageSortBy(this);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];


    get sortBy(): AllAccountUsageSortBy {
        return this._sortBy;
    }

    static get sortBy(): AllAccountUsageSortByWithoutQuery {
        return this._sortBy;
    }

    static use(sorting?: Sorting): [QueryResultWithState<AccountUsage[]>, PerformQuery, SetSorting] {
        return useQuery<AccountUsage[], AllAccountUsage>(AllAccountUsage, undefined, sorting);
    }

    static useWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<AccountUsage[]>, PerformQuery, SetSorting, SetPage, SetPageSize] {
        return useQueryWithPaging<AccountUsage[], AllAccountUsage>(AllAccountUsage, new Paging(0, pageSize), undefined, sorting);
    }

    static useSuspense(sorting?: Sorting): [QueryResultWithState<AccountUsage[]>, PerformQuery, SetSorting] {
        return useSuspenseQuery<AccountUsage[], AllAccountUsage>(AllAccountUsage, undefined, sorting);
    }

    static useSuspenseWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<AccountUsage[]>, PerformQuery, SetSorting, SetPage, SetPageSize] {
        return useSuspenseQueryWithPaging<AccountUsage[], AllAccountUsage>(AllAccountUsage, new Paging(0, pageSize), undefined, sorting);
    }

    static when(condition: boolean): QueryWhen<AllAccountUsage, AccountUsage[]> {
        return new QueryWhen<AllAccountUsage, AccountUsage[]>(AllAccountUsage, condition);
    }
}

/**
 * Read model for the usage statistics of a Claude account - computed on demand from the account's work sessions and the configured plan boundaries, mirroring what the scheduler enforces.
 */
export class AccountUsage {

    /**
     * The account identity.
     */
    @field(Guid)
    id!: Guid;

    /**
     * The display name of the account.
     */
    @field(String)
    name!: string;

    /**
     * The subscription plan of the account.
     */
    @field(Number)
    plan!: ClaudePlan;

    /**
     * Sessions started within the rolling five-hour window.
     */
    @field(Number)
    sessionsLastFiveHours!: number;

    /**
     * The plan's session limit for the five-hour window.
     */
    @field(Number)
    sessionsPerFiveHours!: number;

    /**
     * Sessions started within the rolling week.
     */
    @field(Number)
    sessionsLastWeek!: number;

    /**
     * The plan's session limit for the week.
     */
    @field(Number)
    sessionsPerWeek!: number;

    /**
     * When the oldest session in the five-hour window ages out - `null` when the window is empty.
     */
    @field(Date)
    fiveHourWindowResetsAt?: Date;

    /**
     * Input and output tokens the account's sessions used within the rolling week.
     */
    @field(Number)
    tokensUsedLastWeek!: number;

    /**
     * Input and output tokens the account's sessions have used in total.
     */
    @field(Number)
    tokensUsedTotal!: number;

    /**
     * The reported cost of the account's sessions within the rolling week, in USD.
     */
    @field(Number)
    costLastWeek!: number;

    /**
     * The reported cost of the account's sessions in total, in USD.
     */
    @field(Number)
    costTotal!: number;
}
