// @generated by Cratis. Source: Planner.Work.Failing.FailWork, Planner.Work.Failing.WorkFailed. Time: 2026-08-08T17:35:38.1733570Z. Hash: 9E0FE616107D7F6C96C00D94E40D955B1042EE7E65A8C10CB0EE11D30FA03373
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { Guid, field } from '@cratis/fundamentals';

/**
 * Command for recording that a unit of work failed - executed when the worker container reports a failure or terminates unexpectedly.
 */
export interface IFailWork {
    
    /**
     * The reason the work failed.
     */
    reason?: string;
    
    /**
     * The identity of the work.
     */
    work?: Guid;
}


/**
 * Command for recording that a unit of work failed - executed when the worker container reports a failure or terminates unexpectedly.
 */
export class FailWork extends Command<IFailWork, WorkFailed> implements IFailWork {
    readonly route: string = '/api/work/failing';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('reason', String, false),
        new PropertyDescriptor('work', Guid, false),
    ];

    private _reason!: string;
    private _work!: Guid;

    constructor() {
        super(WorkFailed, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The reason the work failed.
     */
    get reason(): string {
        return this._reason;
    }

    set reason(value: string) {
        this._reason = value;
        this.propertyChanged('reason');
    }
    /**
     * The identity of the work.
     */
    get work(): Guid {
        return this._work;
    }

    set work(value: Guid) {
        this._work = value;
        this.propertyChanged('work');
    }

    static use(initialValues?: IFailWork): [FailWork, SetCommandValues<IFailWork>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<FailWork, IFailWork>(FailWork, initialValues);
    }
}

/**
 * Event raised when a unit of work failed - the covered issues fall back to no status so a human can decide whether to mark them ready again.
 */
export class WorkFailed {

    /**
     * The reason the work failed.
     */
    @field(String)
    reason!: string;
}
