// @generated by Cratis. Source: Planner.Repositories.IssueSynchronizationStatus. Time: 2026-08-09T20:22:26.4216830Z. Hash: F4E3E9E4E241D409DFA71D39BE8C53D5BD0BE238C11E729B83C8C581208EC1A7
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

// eslint-disable-next-line header/header
/**
 * How far the Planner got mirroring the issues of a repository from GitHub.
 */
export enum IssueSynchronizationStatus {
    pending = 0,
    synchronized = 1,
    failed = 2,
}
