// @generated by Cratis. Source: Planner.Repositories.ReviewGatePolicy. Time: 2026-08-19T16:43:45.5809930Z. Hash: A5D3B89491086FFBAB8E781DE19CADB8D9C505A5900E48278040B41331489C57
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

// eslint-disable-next-line header/header
/**
 * Whether a pull request in a repository needs a person before it can merge, or an agent may merge it on its own once the language model classifies it as safe to.
 */
export enum ReviewGatePolicy {
    human = 0,
    auto = 1,
}
