// @generated by Cratis. Source: Planner.Repositories.Groups.Changing.ChangeRepositoryGroup, Planner.Repositories.Groups.Changing.RepositoryGroupMembersChanged. Time: 2026-08-08T21:11:05.5434570Z. Hash: 701E7330A1CF6C7C86718D47E0A1DC4C97C966E1794C149CB3928A85C9620889
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command, CommandValidator } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { Guid, field } from '@cratis/fundamentals';

/**
 * Command for changing the members of a repository group - the full member set travels as one fact.
 */
export interface IChangeRepositoryGroup {
    
    /**
     * The identity of the group.
     */
    group?: Guid;
    
    /**
     * The identities of the repositories the group now holds.
     */
    repositories?: string[];
}

export class ChangeRepositoryGroupValidator extends CommandValidator<IChangeRepositoryGroup> {
    constructor() {
        super();
        this.ruleFor(c => c.repositories).notEmpty().withMessage('A group needs at least one repository');
    }
}

/**
 * Command for changing the members of a repository group - the full member set travels as one fact.
 */
export class ChangeRepositoryGroup extends Command<IChangeRepositoryGroup, RepositoryGroupMembersChanged> implements IChangeRepositoryGroup {
    readonly route: string = '/api/repositories/groups/changing';
    readonly validation: CommandValidator = new ChangeRepositoryGroupValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('group', Guid, false),
        new PropertyDescriptor('repositories', String, false),
    ];

    private _group!: Guid;
    private _repositories!: string[];

    constructor() {
        super(RepositoryGroupMembersChanged, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The identity of the group.
     */
    get group(): Guid {
        return this._group;
    }

    set group(value: Guid) {
        this._group = value;
        this.propertyChanged('group');
    }
    /**
     * The identities of the repositories the group now holds.
     */
    get repositories(): string[] {
        return this._repositories;
    }

    set repositories(value: string[]) {
        this._repositories = value;
        this.propertyChanged('repositories');
    }

    static use(initialValues?: IChangeRepositoryGroup): [ChangeRepositoryGroup, SetCommandValues<IChangeRepositoryGroup>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<ChangeRepositoryGroup, IChangeRepositoryGroup>(ChangeRepositoryGroup, initialValues);
    }
}

/**
 * Event raised when the members of a repository group have changed - carries the full resulting set.
 */
export class RepositoryGroupMembersChanged {

    /**
     * The identities of the repositories the group now holds.
     */
    @field(String, true)
    repositories!: string[];
}
