// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

/**
 * Behavior fixtures for the write guard and the Pi bridge that drives it.
 *
 * A guard is only as trustworthy as the cases proven against it: every forbidden input must be refused, every
 * harmless look-alike must be allowed, the same target must resolve the same way however its path is spelled, and
 * a read-shaped call must never be refused for touching a protected file. Each table below pairs a case that must
 * block with the nearest case that must not, so a guard that blocks everything fails these tests just as surely
 * as one that blocks nothing.
 */

import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, relative, resolve } from 'node:path';
import test from 'node:test';
import type { ExtensionAPI } from '@earendil-works/pi-coding-agent';
import registerCratisHooks from '../../.cratis/ai/harnesses/pi/extensions/cratis-hooks/index.ts';

const repositoryRoot = resolve(import.meta.dirname, '..', '..');
const guard = join(repositoryRoot, '.cratis', 'ai', 'hooks', 'scripts', 'cratis-guard-writes.sh');

const BLOCK = 'block';
const ALLOW = 'allow';

function runGuard(payload: object, cwd: string, env: NodeJS.ProcessEnv = {}): { verdict: string; stderr: string } {
    const result = spawnSync('bash', [guard], {
        cwd,
        input: JSON.stringify(payload),
        encoding: 'utf8',
        env: { ...process.env, CRATIS_HOOKS_ALLOW_PROTECTED_WRITES: '0', ...env },
    });
    return { verdict: result.status === 2 ? BLOCK : ALLOW, stderr: result.stderr };
}

/** A throwaway repository holding one real generated proxy, one file that merely mentions the marker, and a manifest. */
function scratchRepository(): { root: string; generated: string; mention: string; manifest: string; dispose: () => void } {
    const root = mkdtempSync(join(tmpdir(), 'cratis-guard-'));
    spawnSync('git', ['init', '-q', root]);
    mkdirSync(join(root, 'Source', 'Accounts', 'Registration'), { recursive: true });
    const generated = join(root, 'Source', 'Accounts', 'Registration', 'Registration.ts');
    writeFileSync(generated, '// @generated by Cratis. DO NOT EDIT.\nexport class Register {}\n');
    const mention = join(root, 'Source', 'Accounts', 'Registration', 'notes.md');
    writeFileSync(mention, '# Notes\n\nProxies carry a `// @generated by Cratis` header; never edit them.\n');
    const manifest = join(root, 'Directory.Packages.props');
    writeFileSync(manifest, '<Project />\n');
    return { root, generated, mention, manifest, dispose: () => rmSync(root, { recursive: true, force: true }) };
}

test('the write guard refuses generated output and allows a file that merely mentions the marker', () => {
    const repo = scratchRepository();
    try {
        const cases: Array<[expected: string, name: string, payload: object]> = [
            [BLOCK, 'edit a generated proxy', { cwd: repo.root, tool_name: 'Edit', tool_input: { file_path: repo.generated, new_string: 'x' } }],
            [BLOCK, 'overwrite a generated proxy', { cwd: repo.root, tool_name: 'Write', tool_input: { file_path: repo.generated, content: 'x' } }],
            [ALLOW, 'edit a file that only mentions the marker in prose', { cwd: repo.root, tool_name: 'Edit', tool_input: { file_path: repo.mention, new_string: 'more prose' } }],
            [BLOCK, 'author a new file whose content opens with the generated header', { cwd: repo.root, tool_name: 'Write', tool_input: { file_path: join(repo.root, 'Source', 'New.ts'), content: '// @generated by Cratis\nexport {};\n' } }],
            [ALLOW, 'author a new file that quotes the header below its first lines', { cwd: repo.root, tool_name: 'Write', tool_input: { file_path: join(repo.root, 'Source', 'New.md'), content: '# Title\n\n\n\n\n\nThe header reads `// @generated by Cratis`.\n' } }],
            [BLOCK, 'edit a dependency manifest', { cwd: repo.root, tool_name: 'Edit', tool_input: { file_path: repo.manifest, new_string: 'x' } }],
            [ALLOW, 'edit an ordinary source file', { cwd: repo.root, tool_name: 'Edit', tool_input: { file_path: join(repo.root, 'Source', 'Accounts', 'Registration', 'Registration.cs'), new_string: 'x' } }],
            [ALLOW, 'a call with no file path is not the guard\u2019s business', { cwd: repo.root, tool_name: 'Bash', tool_input: { command: `cat ${repo.generated}` } }],
            [ALLOW, 'malformed input fails open', 'not json' as unknown as object],
        ];
        for (const [expected, name, payload] of cases) {
            const { verdict, stderr } = runGuard(payload, repo.root);
            assert.equal(verdict, expected, `${name}\n${stderr}`);
            if (expected === BLOCK) assert.match(stderr, /BLOCKED by cratis-guard-writes/);
        }
    } finally {
        repo.dispose();
    }
});

test('the write guard resolves every spelling of the same target to the same verdict', () => {
    const repo = scratchRepository();
    try {
        const nested = join(repo.root, 'Source', 'Accounts');
        const spellings: Array<[cwd: string, path: string]> = [
            [repo.root, repo.generated],
            [repo.root, relative(repo.root, repo.generated)],
            [nested, relative(nested, repo.generated)],
            [repo.root, `${repo.root}/Source/Accounts/../Accounts/Registration/Registration.ts`],
        ];
        for (const [cwd, path] of spellings) {
            const { verdict, stderr } = runGuard({ cwd, tool_name: 'Edit', tool_input: { file_path: path, new_string: 'x' } }, cwd);
            assert.equal(verdict, BLOCK, `${path} (cwd ${cwd})\n${stderr}`);
        }
    } finally {
        repo.dispose();
    }
});

test('the explicit escape hatch allows one protected write and nothing else changes', () => {
    const repo = scratchRepository();
    try {
        const payload = { cwd: repo.root, tool_name: 'Edit', tool_input: { file_path: repo.manifest, new_string: 'x' } };
        assert.equal(runGuard(payload, repo.root).verdict, BLOCK);
        assert.equal(runGuard(payload, repo.root, { CRATIS_HOOKS_ALLOW_PROTECTED_WRITES: '1' }).verdict, ALLOW);
    } finally {
        repo.dispose();
    }
});

test('the Pi bridge classifies write-shaped calls through the guard and never blocks a read of a protected file', async () => {
    const repo = scratchRepository();
    // The bridge prefers <cwd>/.cratis/ai/hooks/scripts when present; the scratch repo has none, so it falls back
    // to the bundled corpus scripts - the same ones the spec above exercised directly.
    const handlers = new Map<string, (event: unknown, ctx: unknown) => Promise<unknown> | unknown>();
    const api = { on: (event: string, handler: (event: unknown, ctx: unknown) => Promise<unknown> | unknown) => handlers.set(event, handler) } as unknown as ExtensionAPI;
    registerCratisHooks(api);
    const toolCall = handlers.get('tool_call');
    assert.ok(toolCall, 'the bridge registers a tool_call handler');
    const ctx = { cwd: repo.root, signal: undefined };
    try {
        const edit = await toolCall({ toolName: 'edit', input: { path: repo.generated, edits: [{ oldText: 'a', newText: 'b' }] } }, ctx) as { block?: boolean; reason?: string } | undefined;
        assert.equal(edit?.block, true, 'editing a generated proxy through Pi must be refused');
        assert.match(edit?.reason ?? '', /generated/);
        const write = await toolCall({ toolName: 'write', input: { path: repo.generated, content: 'x' } }, ctx) as { block?: boolean } | undefined;
        assert.equal(write?.block, true, 'overwriting a generated proxy through Pi must be refused');
        for (const toolName of ['read', 'grep', 'find', 'ls', 'bash']) {
            const read = await toolCall({ toolName, input: { path: repo.generated, command: `cat ${repo.generated}` } }, ctx);
            assert.equal(read, undefined, `${toolName} of a generated proxy must not be refused`);
        }
        const ordinary = await toolCall({ toolName: 'edit', input: { path: join(repo.root, 'Source', 'Ordinary.cs'), edits: [{ oldText: 'a', newText: 'b' }] } }, ctx);
        assert.equal(ordinary, undefined, 'an ordinary edit must pass through');
    } finally {
        repo.dispose();
    }
});
