// @generated by Cratis. Source: Planner.Issues.SettingPriority.SetIssuePriority, Planner.Issues.SettingPriority.IssuePrioritySet. Time: 2026-08-19T12:22:17.4930590Z. Hash: 0AD997055A05B2351F562E948272229FCB2E4D7B18C3589AADBC0B8E445E3744
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { Priority } from '../Priority';
import { field } from '@cratis/fundamentals';

/**
 * Command for setting how urgently an issue should be worked on - explicit and set by a person, so it takes precedence over anything triage suggests. Pass {@link NotSet} to clear it.
 */
export interface ISetIssuePriority {
    
    /**
     * The identity of the issue.
     */
    issue?: string;
    
    /**
     * The priority to set, or {@link NotSet} to clear it.
     */
    priority?: Priority;
}


/**
 * Command for setting how urgently an issue should be worked on - explicit and set by a person, so it takes precedence over anything triage suggests. Pass {@link NotSet} to clear it.
 */
export class SetIssuePriority extends Command<ISetIssuePriority, IssuePrioritySet> implements ISetIssuePriority {
    readonly route: string = '/api/issues/setting-priority';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('issue', String, false),
        new PropertyDescriptor('priority', Number, false),
    ];

    private _issue!: string;
    private _priority!: Priority;

    constructor() {
        super(IssuePrioritySet, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The identity of the issue.
     */
    get issue(): string {
        return this._issue;
    }

    set issue(value: string) {
        this._issue = value;
        this.propertyChanged('issue');
    }
    /**
     * The priority to set, or {@link NotSet} to clear it.
     */
    get priority(): Priority {
        return this._priority;
    }

    set priority(value: Priority) {
        this._priority = value;
        this.propertyChanged('priority');
    }

    static use(initialValues?: ISetIssuePriority): [SetIssuePriority, SetCommandValues<ISetIssuePriority>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<SetIssuePriority, ISetIssuePriority>(SetIssuePriority, initialValues);
    }
}

/**
 * Event raised when an issue's priority has been explicitly set (or cleared, when {@link Priority} is {@link NotSet}).
 */
export class IssuePrioritySet {

    /**
     * The priority that was set.
     */
    @field(Number)
    priority!: Priority;
}
