// @generated by Cratis. Source: Planner.Issues.Comments.Removing.RemoveIssueComment, Planner.Issues.Comments.Removing.IssueCommentRemoved. Time: 2026-08-08T21:11:05.5434570Z. Hash: C1D090E930860BCE3A9CD0263BA20F104A3FFBF2EDE8E45CE53FAA5295CCD0C2
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { field } from '@cratis/fundamentals';

/**
 * Command for removing a comment from an issue - mirroring a comment deletion on GitHub.
 */
export interface IRemoveIssueComment {
    
    /**
     * The identity of the comment on GitHub.
     */
    comment?: number;
    
    /**
     * The identity of the issue.
     */
    issue?: string;
}


/**
 * Command for removing a comment from an issue - mirroring a comment deletion on GitHub.
 */
export class RemoveIssueComment extends Command<IRemoveIssueComment, IssueCommentRemoved> implements IRemoveIssueComment {
    readonly route: string = '/api/issues/comments/removing';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('comment', Number, false),
        new PropertyDescriptor('issue', String, false),
    ];

    private _comment!: number;
    private _issue!: string;

    constructor() {
        super(IssueCommentRemoved, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The identity of the comment on GitHub.
     */
    get comment(): number {
        return this._comment;
    }

    set comment(value: number) {
        this._comment = value;
        this.propertyChanged('comment');
    }
    /**
     * The identity of the issue.
     */
    get issue(): string {
        return this._issue;
    }

    set issue(value: string) {
        this._issue = value;
        this.propertyChanged('issue');
    }

    static use(initialValues?: IRemoveIssueComment): [RemoveIssueComment, SetCommandValues<IRemoveIssueComment>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<RemoveIssueComment, IRemoveIssueComment>(RemoveIssueComment, initialValues);
    }
}

/**
 * Event raised when a comment has been removed from an issue on GitHub.
 */
export class IssueCommentRemoved {

    /**
     * The identity of the comment on GitHub.
     */
    @field(Number)
    comment!: number;
}
