// @generated by Cratis. Source: Planner.Issues.Classifying.ClassifyIssue, Planner.Issues.Classifying.IssueClassified. Time: 2026-08-19T14:32:49.9784910Z. Hash: 681FAB86C79095E2F3BB3BE4F3F922E3111DB7F353BF101B33287E7948AE7846
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { IssueFeasibility } from '../IssueFeasibility';
import { IssueKind } from '../IssueKind';
import { Priority } from '../Priority';
import { field } from '@cratis/fundamentals';

/**
 * Command for recording how triage classified an issue - executed by the triage reactor once a language model has produced a structured verdict for a newly registered issue.
 */
export interface IClassifyIssue {
    
    /**
     * The affected area, in the project's own words (e.g. &quot;Chronicle kernel&quot;).
     */
    area?: string;
    
    /**
     * Whether an agent can act on it.
     */
    feasibility?: IssueFeasibility;
    
    /**
     * The identity of the issue.
     */
    issue?: string;
    
    /**
     * What kind of issue this is.
     */
    kind?: IssueKind;
    
    /**
     * Labels triage suggests from the repository's existing label vocabulary.
     */
    suggestedLabels?: string[];
    
    /**
     * The model triage suggests for implementation.
     */
    suggestedModel?: string;
    
    /**
     * The priority triage suggests - {@link NotSet} when it has no opinion.
     */
    suggestedPriority?: Priority;
}


/**
 * Command for recording how triage classified an issue - executed by the triage reactor once a language model has produced a structured verdict for a newly registered issue.
 */
export class ClassifyIssue extends Command<IClassifyIssue, IssueClassified> implements IClassifyIssue {
    readonly route: string = '/api/issues/classifying';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('area', String, false),
        new PropertyDescriptor('feasibility', Number, false),
        new PropertyDescriptor('issue', String, false),
        new PropertyDescriptor('kind', Number, false),
        new PropertyDescriptor('suggestedLabels', String, false),
        new PropertyDescriptor('suggestedModel', String, false),
        new PropertyDescriptor('suggestedPriority', Number, false),
    ];

    private _area!: string;
    private _feasibility!: IssueFeasibility;
    private _issue!: string;
    private _kind!: IssueKind;
    private _suggestedLabels!: string[];
    private _suggestedModel!: string;
    private _suggestedPriority!: Priority;

    constructor() {
        super(IssueClassified, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The affected area, in the project's own words (e.g. &quot;Chronicle kernel&quot;).
     */
    get area(): string {
        return this._area;
    }

    set area(value: string) {
        this._area = value;
        this.propertyChanged('area');
    }
    /**
     * Whether an agent can act on it.
     */
    get feasibility(): IssueFeasibility {
        return this._feasibility;
    }

    set feasibility(value: IssueFeasibility) {
        this._feasibility = value;
        this.propertyChanged('feasibility');
    }
    /**
     * The identity of the issue.
     */
    get issue(): string {
        return this._issue;
    }

    set issue(value: string) {
        this._issue = value;
        this.propertyChanged('issue');
    }
    /**
     * What kind of issue this is.
     */
    get kind(): IssueKind {
        return this._kind;
    }

    set kind(value: IssueKind) {
        this._kind = value;
        this.propertyChanged('kind');
    }
    /**
     * Labels triage suggests from the repository's existing label vocabulary.
     */
    get suggestedLabels(): string[] {
        return this._suggestedLabels;
    }

    set suggestedLabels(value: string[]) {
        this._suggestedLabels = value;
        this.propertyChanged('suggestedLabels');
    }
    /**
     * The model triage suggests for implementation.
     */
    get suggestedModel(): string {
        return this._suggestedModel;
    }

    set suggestedModel(value: string) {
        this._suggestedModel = value;
        this.propertyChanged('suggestedModel');
    }
    /**
     * The priority triage suggests - {@link NotSet} when it has no opinion.
     */
    get suggestedPriority(): Priority {
        return this._suggestedPriority;
    }

    set suggestedPriority(value: Priority) {
        this._suggestedPriority = value;
        this.propertyChanged('suggestedPriority');
    }

    static use(initialValues?: IClassifyIssue): [ClassifyIssue, SetCommandValues<IClassifyIssue>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<ClassifyIssue, IClassifyIssue>(ClassifyIssue, initialValues);
    }
}

/**
 * Event raised when triage has classified an issue.
 */
export class IssueClassified {

    /**
     * What kind of issue this is.
     */
    @field(Number)
    kind!: IssueKind;

    /**
     * Whether an agent can act on it.
     */
    @field(Number)
    feasibility!: IssueFeasibility;

    /**
     * The priority triage suggests.
     */
    @field(Number)
    suggestedPriority!: Priority;

    /**
     * Labels triage suggests from the repository's existing label vocabulary.
     */
    @field(String, true)
    suggestedLabels!: string[];

    /**
     * The affected area, in the project's own words.
     */
    @field(String)
    area!: string;

    /**
     * The model triage suggests for implementation.
     */
    @field(String)
    suggestedModel!: string;
}
