// @generated by Cratis. Source: Planner.GitHub.App.Installations.GitHubAppInstallation, Planner.GitHub.App.Installations.GitHubAppInstallation. Time: 2026-08-09T09:18:49.3333770Z. Hash: D2377E3F80F56A9D79218327793CC5AEF7270BB418B9DCACE7EE4DA4ECD69A7B
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { ObservableQueryFor, QueryResultWithState, Sorting, Paging, ChangeSet } from '@cratis/arc/queries';
import { useObservableQuery, useObservableQueryWithPaging, useSuspenseObservableQuery, useSuspenseObservableQueryWithPaging, useChangeStream, SetSorting, SetPage, SetPageSize, ObservableQueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { field } from '@cratis/fundamentals';

class AllGitHubAppInstallationsSortBy {

    constructor(readonly query: AllGitHubAppInstallations) {
    }

}

class AllGitHubAppInstallationsSortByWithoutQuery {

}


/**
 * Observes every account the GitHub App is installed on.
 */
export class AllGitHubAppInstallations extends ObservableQueryFor<GitHubAppInstallation[]> {
    readonly route: string = '/api/git-hub/app/installations/all-git-hub-app-installations';
    readonly queryName: string = 'Planner.GitHub.App.Installations.GitHubAppInstallation.AllGitHubAppInstallations';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: GitHubAppInstallation[] = [];
    private readonly _sortBy: AllGitHubAppInstallationsSortBy;
    private static readonly _sortBy: AllGitHubAppInstallationsSortByWithoutQuery = new AllGitHubAppInstallationsSortByWithoutQuery();

    constructor() {
        super(GitHubAppInstallation, true);
        this._sortBy = new AllGitHubAppInstallationsSortBy(this);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];


    get sortBy(): AllGitHubAppInstallationsSortBy {
        return this._sortBy;
    }

    static get sortBy(): AllGitHubAppInstallationsSortByWithoutQuery {
        return this._sortBy;
    }

    static use(sorting?: Sorting): [QueryResultWithState<GitHubAppInstallation[]>, SetSorting] {
        return useObservableQuery<GitHubAppInstallation[], AllGitHubAppInstallations>(AllGitHubAppInstallations, undefined, sorting);
    }

    static useWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<GitHubAppInstallation[]>, SetSorting, SetPage, SetPageSize] {
        return useObservableQueryWithPaging<GitHubAppInstallation[], AllGitHubAppInstallations>(AllGitHubAppInstallations, new Paging(0, pageSize), undefined, sorting);
    }

    static useSuspense(sorting?: Sorting): [QueryResultWithState<GitHubAppInstallation[]>, SetSorting] {
        return useSuspenseObservableQuery<GitHubAppInstallation[], AllGitHubAppInstallations>(AllGitHubAppInstallations, undefined, sorting);
    }

    static useSuspenseWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<GitHubAppInstallation[]>, SetSorting, SetPage, SetPageSize] {
        return useSuspenseObservableQueryWithPaging<GitHubAppInstallation[], AllGitHubAppInstallations>(AllGitHubAppInstallations, new Paging(0, pageSize), undefined, sorting);
    }

    static useChangeStream(getKey?: (item: GitHubAppInstallation) => unknown, sorting?: Sorting): ChangeSet<GitHubAppInstallation> {
        return useChangeStream<GitHubAppInstallation, AllGitHubAppInstallations>(AllGitHubAppInstallations, undefined, getKey, sorting);
    }

    static when(condition: boolean): ObservableQueryWhen<AllGitHubAppInstallations, GitHubAppInstallation[]> {
        return new ObservableQueryWhen<AllGitHubAppInstallations, GitHubAppInstallation[]>(AllGitHubAppInstallations, condition);
    }
}

/**
 * Read model for the accounts the GitHub App is installed on. Safe to expose to the frontend - it carries no secret material, only which accounts have installed the App.
 */
export class GitHubAppInstallation {

    /**
     * The installation identity.
     */
    @field(Number)
    id!: number;

    /**
     * The login of the account the App is installed on.
     */
    @field(String)
    account!: string;
}
