// @generated by Cratis. Source: Planner.GitHub.App.Installations.RemoveGitHubAppInstallation, Planner.GitHub.App.Installations.GitHubAppUninstalled. Time: 2026-08-09T09:18:49.3333770Z. Hash: 34FC6150CD32C9CEB8BB46B1568F0206E5BB395EBE8BA4F4F8EDDA54AD87C898
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';

/**
 * Command for recording that the GitHub App has been uninstalled from an account - triggered from the `installation` webhook event's `deleted` action.
 */
export interface IRemoveGitHubAppInstallation {
    
    /**
     * The identity of the installation that was removed.
     */
    installation?: number;
}


/**
 * Command for recording that the GitHub App has been uninstalled from an account - triggered from the `installation` webhook event's `deleted` action.
 */
export class RemoveGitHubAppInstallation extends Command<IRemoveGitHubAppInstallation, GitHubAppUninstalled> implements IRemoveGitHubAppInstallation {
    readonly route: string = '/api/git-hub/app/installations/remove-git-hub-app-installation';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('installation', Number, false),
    ];

    private _installation!: number;

    constructor() {
        super(GitHubAppUninstalled, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The identity of the installation that was removed.
     */
    get installation(): number {
        return this._installation;
    }

    set installation(value: number) {
        this._installation = value;
        this.propertyChanged('installation');
    }

    static use(initialValues?: IRemoveGitHubAppInstallation): [RemoveGitHubAppInstallation, SetCommandValues<IRemoveGitHubAppInstallation>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<RemoveGitHubAppInstallation, IRemoveGitHubAppInstallation>(RemoveGitHubAppInstallation, initialValues);
    }
}

/**
 * Event raised when the GitHub App has been uninstalled from an account.
 */
export class GitHubAppUninstalled {
}
