// @generated by Cratis. Source: Planner.Roadmap.SettingVision.SetVision, Planner.Roadmap.SettingVision.VisionSet. Time: 2026-08-19T16:54:23.5546910Z. Hash: 180C60C3A9477775E895E354A81925EBEE9372FC2C1696B3488F0583DD7778B7
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { field } from '@cratis/fundamentals';

/**
 * Command for setting the Planner's vision document - where the team is going, maintained by hand and given to agents as context. One setting shared across the whole deployment; every change is its own event, so the vision has history.
 */
export interface ISetVision {
    
    /**
     * The markdown content of the vision.
     */
    content?: string;
}


/**
 * Command for setting the Planner's vision document - where the team is going, maintained by hand and given to agents as context. One setting shared across the whole deployment; every change is its own event, so the vision has history.
 */
export class SetVision extends Command<ISetVision, VisionSet> implements ISetVision {
    readonly route: string = '/api/roadmap/setting-vision';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('content', String, false),
    ];

    private _content!: string;

    constructor() {
        super(VisionSet, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The markdown content of the vision.
     */
    get content(): string {
        return this._content;
    }

    set content(value: string) {
        this._content = value;
        this.propertyChanged('content');
    }

    static use(initialValues?: ISetVision): [SetVision, SetCommandValues<ISetVision>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<SetVision, ISetVision>(SetVision, initialValues);
    }
}

/**
 * Event raised when the Planner's vision document has been set.
 */
export class VisionSet {

    /**
     * The markdown content of the vision.
     */
    @field(String)
    content!: string;
}
