// @generated by Cratis. Source: Planner.GitHub.App.GitHubAppStatus, Planner.GitHub.App.GitHubAppStatus. Time: 2026-08-09T09:20:42.9908020Z. Hash: 6CD06FD141193701B129B25BB40C78B09D7070EB465A7CF3281A16A8C80639D3
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { QueryFor, QueryResultWithState } from '@cratis/arc/queries';
import { useQuery, useSuspenseQuery, PerformQuery, SetSorting, QueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { field } from '@cratis/fundamentals';

/**
 * Gets the current GitHub App configuration status.
 */
export class Current extends QueryFor<GitHubAppStatus> {
    readonly route: string = '/api/git-hub/app/current';
    readonly queryName: string = 'Planner.GitHub.App.GitHubAppStatus.Current';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: GitHubAppStatus = {} as any;

    constructor() {
        super(GitHubAppStatus, false);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];



    static use(): [QueryResultWithState<GitHubAppStatus>, PerformQuery, SetSorting] {
        return useQuery<GitHubAppStatus, Current>(Current);
    }

    static useSuspense(): [QueryResultWithState<GitHubAppStatus>, PerformQuery, SetSorting] {
        return useSuspenseQuery<GitHubAppStatus, Current>(Current);
    }

    static when(condition: boolean): QueryWhen<Current, GitHubAppStatus> {
        return new QueryWhen<Current, GitHubAppStatus>(Current, condition);
    }
}

/**
 * The GitHub App's own configuration status - whether it has been configured, and the non-secret details needed to build its installation URL. A plain configuration snapshot, not a Chronicle projection - carries no secret material.
 */
export class GitHubAppStatus {

    /**
     * Whether the App has been configured with the minimum required to authenticate.
     */
    @field(Boolean)
    isConfigured!: boolean;

    /**
     * The App's URL-friendly slug.
     */
    @field(String)
    slug!: string;

    /**
     * The display name of the App.
     */
    @field(String)
    name!: string;
}
