// @generated by Cratis. Source: Planner.Roadmap.RequestingPlan.RequestPlan. Time: 2026-08-19T16:55:58.0712010Z. Hash: 61A386A417234A6B8607BB94AE944C8CBEA78B31615973C0750AC4AE83FAB11A
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command, CommandValidator } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { Guid } from '@cratis/fundamentals';

/**
 * Command for requesting a plan covering a set of selected issues - ordering, grouping, dependencies, suggested priorities and models, open questions, produced by the Planner's own language model rather than a worker container (this is reasoning about the issues, not implementation work).
 */
export interface IRequestPlan {
    
    /**
     * Extra, free-form instructions for the plan - optional.
     */
    instructions?: string;
    
    /**
     * The identities of the issues to plan across.
     */
    issues?: string[];
}

export class RequestPlanValidator extends CommandValidator<IRequestPlan> {
    constructor() {
        super();
        this.ruleFor(c => c.issues).notEmpty().withMessage('Select at least one issue to plan');
    }
}

/**
 * Command for requesting a plan covering a set of selected issues - ordering, grouping, dependencies, suggested priorities and models, open questions, produced by the Planner's own language model rather than a worker container (this is reasoning about the issues, not implementation work).
 */
export class RequestPlan extends Command<IRequestPlan, Guid> implements IRequestPlan {
    readonly route: string = '/api/roadmap/requesting-plan';
    readonly validation: CommandValidator = new RequestPlanValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('instructions', String, true),
        new PropertyDescriptor('issues', String, false),
    ];

    private _instructions?: string;
    private _issues!: string[];

    constructor() {
        super(Guid, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * Extra, free-form instructions for the plan - optional.
     */
    get instructions(): string | undefined {
        return this._instructions;
    }

    set instructions(value: string | undefined) {
        this._instructions = value;
        this.propertyChanged('instructions');
    }
    /**
     * The identities of the issues to plan across.
     */
    get issues(): string[] {
        return this._issues;
    }

    set issues(value: string[]) {
        this._issues = value;
        this.propertyChanged('issues');
    }

    static use(initialValues?: IRequestPlan): [RequestPlan, SetCommandValues<IRequestPlan>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<RequestPlan, IRequestPlan>(RequestPlan, initialValues);
    }
}
