// @generated by Cratis. Source: Planner.Issues.ChangingAssignees.ChangeIssueAssignees, Planner.Issues.ChangingAssignees.IssueAssigneesChanged. Time: 2026-08-18T12:07:51.5752680Z. Hash: B1A59F5A21D286082B00FE962BA9D783A8B24A6E63BFF6087A85B2ADD5EDD475
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { field } from '@cratis/fundamentals';

/**
 * Command for changing the assignees of an issue - mirroring assignment on GitHub. The full assignee set travels as one fact; GitHub's assigned/unassigned deliveries both carry the resulting set.
 */
export interface IChangeIssueAssignees {
    
    /**
     * The GitHub logins the issue is now assigned to.
     */
    assignees?: string[];
    
    /**
     * The identity of the issue.
     */
    issue?: string;
}


/**
 * Command for changing the assignees of an issue - mirroring assignment on GitHub. The full assignee set travels as one fact; GitHub's assigned/unassigned deliveries both carry the resulting set.
 */
export class ChangeIssueAssignees extends Command<IChangeIssueAssignees, IssueAssigneesChanged> implements IChangeIssueAssignees {
    readonly route: string = '/api/issues/changing-assignees';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('assignees', String, false),
        new PropertyDescriptor('issue', String, false),
    ];

    private _assignees!: string[];
    private _issue!: string;

    constructor() {
        super(IssueAssigneesChanged, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The GitHub logins the issue is now assigned to.
     */
    get assignees(): string[] {
        return this._assignees;
    }

    set assignees(value: string[]) {
        this._assignees = value;
        this.propertyChanged('assignees');
    }
    /**
     * The identity of the issue.
     */
    get issue(): string {
        return this._issue;
    }

    set issue(value: string) {
        this._issue = value;
        this.propertyChanged('issue');
    }

    static use(initialValues?: IChangeIssueAssignees): [ChangeIssueAssignees, SetCommandValues<IChangeIssueAssignees>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<ChangeIssueAssignees, IChangeIssueAssignees>(ChangeIssueAssignees, initialValues);
    }
}

/**
 * Event raised when the assignees of an issue have changed on GitHub - carries the full resulting set.
 */
export class IssueAssigneesChanged {

    /**
     * The GitHub logins the issue is now assigned to.
     */
    @field(String, true)
    assignees!: string[];
}
