// @generated by Cratis. Source: Planner.Repositories.MappingCodeRepository.MapCodeRepository, Planner.Repositories.MappingCodeRepository.CodeRepositoryMapped. Time: 2026-08-08T17:09:59.4947360Z. Hash: B4CB7B84F1BC1536D10D6F19E47EA6C7FB51E38AECEF9ECB1BEF5F08E406313F
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command, CommandValidator } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { field } from '@cratis/fundamentals';

/**
 * Command for mapping the repository the code lives in for a repository that only tracks issues. Some issue repositories are public fronts for private code repositories - for instance the public StudioIssues repository tracking issues for the private Studio repository.
 */
export interface IMapCodeRepository {
    
    /**
     * The name of the code repository.
     */
    codeName?: string;
    
    /**
     * The organization owning the code repository.
     */
    codeOwner?: string;
    
    /**
     * The identity of the issues repository.
     */
    repository?: string;
}

export class MapCodeRepositoryValidator extends CommandValidator<IMapCodeRepository> {
    constructor() {
        super();
        this.ruleFor(c => c.codeName).notEmpty().withMessage('A code repository name is required');
        this.ruleFor(c => c.codeOwner).notEmpty().withMessage('A code repository owner is required');
    }
}

/**
 * Command for mapping the repository the code lives in for a repository that only tracks issues. Some issue repositories are public fronts for private code repositories - for instance the public StudioIssues repository tracking issues for the private Studio repository.
 */
export class MapCodeRepository extends Command<IMapCodeRepository, CodeRepositoryMapped> implements IMapCodeRepository {
    readonly route: string = '/api/repositories/mapping-code-repository';
    readonly validation: CommandValidator = new MapCodeRepositoryValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('codeName', String, false),
        new PropertyDescriptor('codeOwner', String, false),
        new PropertyDescriptor('repository', String, false),
    ];

    private _codeName!: string;
    private _codeOwner!: string;
    private _repository!: string;

    constructor() {
        super(CodeRepositoryMapped, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The name of the code repository.
     */
    get codeName(): string {
        return this._codeName;
    }

    set codeName(value: string) {
        this._codeName = value;
        this.propertyChanged('codeName');
    }
    /**
     * The organization owning the code repository.
     */
    get codeOwner(): string {
        return this._codeOwner;
    }

    set codeOwner(value: string) {
        this._codeOwner = value;
        this.propertyChanged('codeOwner');
    }
    /**
     * The identity of the issues repository.
     */
    get repository(): string {
        return this._repository;
    }

    set repository(value: string) {
        this._repository = value;
        this.propertyChanged('repository');
    }

    static use(initialValues?: IMapCodeRepository): [MapCodeRepository, SetCommandValues<IMapCodeRepository>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<MapCodeRepository, IMapCodeRepository>(MapCodeRepository, initialValues);
    }
}

/**
 * Event raised when the code repository has been mapped for an issues repository - work scheduled for issues in this repository clones and operates on the mapped code repository instead.
 */
export class CodeRepositoryMapped {

    /**
     * The organization owning the code repository.
     */
    @field(String)
    codeOwner!: string;

    /**
     * The name of the code repository.
     */
    @field(String)
    codeName!: string;
}
