// @generated by Cratis. Source: Planner.Alerts.Listing.Alert, Planner.Alerts.Listing.Alert, Planner.Alerts.Listing.Alert, Planner.Alerts.Listing.AlertNoteEntry. Time: 2026-08-19T12:13:16.9919440Z. Hash: DD688AF2D6D6CF50A6D6C2D11DA3D5B86C634CB4E9F6CD8A97B6A45493156C9D
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { ObservableQueryFor, QueryResultWithState, Sorting, Paging, ChangeSet } from '@cratis/arc/queries';
import { useObservableQuery, useObservableQueryWithPaging, useSuspenseObservableQuery, useSuspenseObservableQueryWithPaging, useChangeStream, SetSorting, SetPage, SetPageSize, ObservableQueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { field, Guid } from '@cratis/fundamentals';
import { AlertSeverity } from '../AlertSeverity';
import { AlertStatus } from '../AlertStatus';

class AllAlertsSortBy {

    constructor(readonly query: AllAlerts) {
    }

}

class AllAlertsSortByWithoutQuery {

}


/**
 * Observes every alert on the board, resolved ones included - the history view behind the &quot;Show done&quot; toggle. {@link ActiveAlerts} is what the default view uses.
 */
export class AllAlerts extends ObservableQueryFor<Alert[]> {
    readonly route: string = '/api/alerts/listing/all-alerts';
    readonly queryName: string = 'Planner.Alerts.Listing.Alert.AllAlerts';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: Alert[] = [];
    private readonly _sortBy: AllAlertsSortBy;
    private static readonly _sortBy: AllAlertsSortByWithoutQuery = new AllAlertsSortByWithoutQuery();

    constructor() {
        super(Alert, true);
        this._sortBy = new AllAlertsSortBy(this);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];


    get sortBy(): AllAlertsSortBy {
        return this._sortBy;
    }

    static get sortBy(): AllAlertsSortByWithoutQuery {
        return this._sortBy;
    }

    static use(sorting?: Sorting): [QueryResultWithState<Alert[]>, SetSorting] {
        return useObservableQuery<Alert[], AllAlerts>(AllAlerts, undefined, sorting);
    }

    static useWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<Alert[]>, SetSorting, SetPage, SetPageSize] {
        return useObservableQueryWithPaging<Alert[], AllAlerts>(AllAlerts, new Paging(0, pageSize), undefined, sorting);
    }

    static useSuspense(sorting?: Sorting): [QueryResultWithState<Alert[]>, SetSorting] {
        return useSuspenseObservableQuery<Alert[], AllAlerts>(AllAlerts, undefined, sorting);
    }

    static useSuspenseWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<Alert[]>, SetSorting, SetPage, SetPageSize] {
        return useSuspenseObservableQueryWithPaging<Alert[], AllAlerts>(AllAlerts, new Paging(0, pageSize), undefined, sorting);
    }

    static useChangeStream(getKey?: (item: Alert) => unknown, sorting?: Sorting): ChangeSet<Alert> {
        return useChangeStream<Alert, AllAlerts>(AllAlerts, undefined, getKey, sorting);
    }

    static when(condition: boolean): ObservableQueryWhen<AllAlerts, Alert[]> {
        return new ObservableQueryWhen<AllAlerts, Alert[]>(AllAlerts, condition);
    }
}

class ActiveAlertsSortBy {

    constructor(readonly query: ActiveAlerts) {
    }

}

class ActiveAlertsSortByWithoutQuery {

}


/**
 * Observes the alerts that are not resolved yet - the default view, so a resolved alert disappears from the board the moment it is resolved.
 */
export class ActiveAlerts extends ObservableQueryFor<Alert[]> {
    readonly route: string = '/api/alerts/listing/active-alerts';
    readonly queryName: string = 'Planner.Alerts.Listing.Alert.ActiveAlerts';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: Alert[] = [];
    private readonly _sortBy: ActiveAlertsSortBy;
    private static readonly _sortBy: ActiveAlertsSortByWithoutQuery = new ActiveAlertsSortByWithoutQuery();

    constructor() {
        super(Alert, true);
        this._sortBy = new ActiveAlertsSortBy(this);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];


    get sortBy(): ActiveAlertsSortBy {
        return this._sortBy;
    }

    static get sortBy(): ActiveAlertsSortByWithoutQuery {
        return this._sortBy;
    }

    static use(sorting?: Sorting): [QueryResultWithState<Alert[]>, SetSorting] {
        return useObservableQuery<Alert[], ActiveAlerts>(ActiveAlerts, undefined, sorting);
    }

    static useWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<Alert[]>, SetSorting, SetPage, SetPageSize] {
        return useObservableQueryWithPaging<Alert[], ActiveAlerts>(ActiveAlerts, new Paging(0, pageSize), undefined, sorting);
    }

    static useSuspense(sorting?: Sorting): [QueryResultWithState<Alert[]>, SetSorting] {
        return useSuspenseObservableQuery<Alert[], ActiveAlerts>(ActiveAlerts, undefined, sorting);
    }

    static useSuspenseWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<Alert[]>, SetSorting, SetPage, SetPageSize] {
        return useSuspenseObservableQueryWithPaging<Alert[], ActiveAlerts>(ActiveAlerts, new Paging(0, pageSize), undefined, sorting);
    }

    static useChangeStream(getKey?: (item: Alert) => unknown, sorting?: Sorting): ChangeSet<Alert> {
        return useChangeStream<Alert, ActiveAlerts>(ActiveAlerts, undefined, getKey, sorting);
    }

    static when(condition: boolean): ObservableQueryWhen<ActiveAlerts, Alert[]> {
        return new ObservableQueryWhen<ActiveAlerts, Alert[]>(ActiveAlerts, condition);
    }
}

/**
 * A note recorded against an alert.
 */
export class AlertNoteEntry {

    /**
     * The identity of the note.
     */
    @field(Guid)
    id!: Guid;

    /**
     * What was recorded.
     */
    @field(String)
    text!: string;

    /**
     * The login of the user that recorded it - {@link NotSet} for automation.
     */
    @field(String)
    addedBy!: string;
}

/**
 * Read model for the alert board - everything reported from running systems, where each alert stands, what an agent made of it, and what people have added since.
 */
export class Alert {

    /**
     * The alert identity - derived from the source and fingerprint.
     */
    @field(String)
    id!: string;

    /**
     * The system the alert came from.
     */
    @field(String)
    source!: string;

    /**
     * The one-line headline.
     */
    @field(String)
    title!: string;

    /**
     * What the sending system had to say, as of the most recent sighting.
     */
    @field(String)
    summary!: string;

    /**
     * How serious the sending system considers it, as of the most recent sighting.
     */
    @field(Number)
    severity!: AlertSeverity;

    /**
     * The sending system's stable key for the condition.
     */
    @field(String)
    fingerprint!: string;

    /**
     * Where the alert stands.
     */
    @field(Number)
    status!: AlertStatus;

    /**
     * How many times the condition has been reported.
     */
    @field(Number)
    occurrences!: number;

    /**
     * When this occurrence of the alert started.
     */
    @field(Date)
    raisedAt?: Date;

    /**
     * When the condition was last reported.
     */
    @field(Date)
    lastObservedAt?: Date;

    /**
     * The unit of work investigating it - `null` until an agent picks it up.
     */
    @field(Guid)
    work?: Guid;

    /**
     * What the agent concluded - `null` until an investigation finishes.
     */
    @field(String)
    findings?: string;

    /**
     * How a person resolved it - `null` unless one did.
     */
    @field(String)
    resolution?: string;

    /**
     * The login of the user that resolved it.
     */
    @field(String)
    resolvedBy?: string;

    /**
     * The issue this alert was turned into - `null` unless it was.
     */
    @field(Number)
    issue?: number;

    /**
     * The html URL of that issue.
     */
    @field(String)
    issueUrl?: string;

    /**
     * The organization owning the repository the issue was created in.
     */
    @field(String)
    issueOwner?: string;

    /**
     * The repository the issue was created in.
     */
    @field(String)
    issueRepository?: string;

    /**
     * The notes recorded against the alert.
     */
    @field(AlertNoteEntry, true)
    notes?: AlertNoteEntry[];
}
