// @generated by Cratis. Source: Planner.Issues.SettingPrompt.SetIssuePrompt, Planner.Issues.SettingPrompt.IssuePromptSet. Time: 2026-08-08T21:11:05.5434570Z. Hash: 87396F13FF1ED5599A45509AD9290430E6405AE5A7FB35BF4B7FA8F5DC55F457
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { field } from '@cratis/fundamentals';

/**
 * Command for setting the extra instructions that travel with an issue when an agent works on it.
 */
export interface ISetIssuePrompt {
    
    /**
     * The identity of the issue.
     */
    issue?: string;
    
    /**
     * The instructions - an empty prompt clears them.
     */
    prompt?: string;
}


/**
 * Command for setting the extra instructions that travel with an issue when an agent works on it.
 */
export class SetIssuePrompt extends Command<ISetIssuePrompt, IssuePromptSet> implements ISetIssuePrompt {
    readonly route: string = '/api/issues/setting-prompt';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('issue', String, false),
        new PropertyDescriptor('prompt', String, false),
    ];

    private _issue!: string;
    private _prompt!: string;

    constructor() {
        super(IssuePromptSet, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The identity of the issue.
     */
    get issue(): string {
        return this._issue;
    }

    set issue(value: string) {
        this._issue = value;
        this.propertyChanged('issue');
    }
    /**
     * The instructions - an empty prompt clears them.
     */
    get prompt(): string {
        return this._prompt;
    }

    set prompt(value: string) {
        this._prompt = value;
        this.propertyChanged('prompt');
    }

    static use(initialValues?: ISetIssuePrompt): [SetIssuePrompt, SetCommandValues<ISetIssuePrompt>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<SetIssuePrompt, ISetIssuePrompt>(SetIssuePrompt, initialValues);
    }
}

/**
 * Event raised when the extra instructions for an issue have been set - they are appended to the prompt the agent gets when working on the issue.
 */
export class IssuePromptSet {

    /**
     * The instructions - the not-set sentinel when cleared.
     */
    @field(String)
    prompt!: string;
}
