// @generated by Cratis. Source: Planner.Builds.RecordingStatus.RecordBuildStatus, Planner.Builds.RecordingStatus.BuildStatusRecorded. Time: 2026-08-19T13:18:47.1489210Z. Hash: 3DD4CA537006370A81D0692A8B78930B3A2440CE62C52B41D656253C9F242C2D
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { BuildConclusion } from '../BuildConclusion';
import { field } from '@cratis/fundamentals';

/**
 * Command for recording the most recent conclusion of a repository's workflow - executed by the daily consolidation for every workflow it finds runs for. The full current fact travels every time, so this doubles as &quot;still failing&quot; and &quot;recovered&quot; without a separate event for either.
 */
export interface IRecordBuildStatus {
    
    /**
     * How the most recent run concluded.
     */
    conclusion?: BuildConclusion;
    
    /**
     * The organization owning the repository.
     */
    owner?: string;
    
    /**
     * When the most recent run finished.
     */
    ranAt?: Date;
    
    /**
     * The repository the workflow belongs to.
     */
    repository?: string;
    
    /**
     * The html URL of the most recent run.
     */
    runUrl?: string;
    
    /**
     * The workflow's name.
     */
    workflow?: string;
}


/**
 * Command for recording the most recent conclusion of a repository's workflow - executed by the daily consolidation for every workflow it finds runs for. The full current fact travels every time, so this doubles as &quot;still failing&quot; and &quot;recovered&quot; without a separate event for either.
 */
export class RecordBuildStatus extends Command<IRecordBuildStatus, BuildStatusRecorded> implements IRecordBuildStatus {
    readonly route: string = '/api/builds/recording-status';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('conclusion', Number, false),
        new PropertyDescriptor('owner', String, false),
        new PropertyDescriptor('ranAt', Date, false),
        new PropertyDescriptor('repository', String, false),
        new PropertyDescriptor('runUrl', String, false),
        new PropertyDescriptor('workflow', String, false),
    ];

    private _conclusion!: BuildConclusion;
    private _owner!: string;
    private _ranAt!: Date;
    private _repository!: string;
    private _runUrl!: string;
    private _workflow!: string;

    constructor() {
        super(BuildStatusRecorded, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * How the most recent run concluded.
     */
    get conclusion(): BuildConclusion {
        return this._conclusion;
    }

    set conclusion(value: BuildConclusion) {
        this._conclusion = value;
        this.propertyChanged('conclusion');
    }
    /**
     * The organization owning the repository.
     */
    get owner(): string {
        return this._owner;
    }

    set owner(value: string) {
        this._owner = value;
        this.propertyChanged('owner');
    }
    /**
     * When the most recent run finished.
     */
    get ranAt(): Date {
        return this._ranAt;
    }

    set ranAt(value: Date) {
        this._ranAt = value;
        this.propertyChanged('ranAt');
    }
    /**
     * The repository the workflow belongs to.
     */
    get repository(): string {
        return this._repository;
    }

    set repository(value: string) {
        this._repository = value;
        this.propertyChanged('repository');
    }
    /**
     * The html URL of the most recent run.
     */
    get runUrl(): string {
        return this._runUrl;
    }

    set runUrl(value: string) {
        this._runUrl = value;
        this.propertyChanged('runUrl');
    }
    /**
     * The workflow's name.
     */
    get workflow(): string {
        return this._workflow;
    }

    set workflow(value: string) {
        this._workflow = value;
        this.propertyChanged('workflow');
    }

    static use(initialValues?: IRecordBuildStatus): [RecordBuildStatus, SetCommandValues<IRecordBuildStatus>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<RecordBuildStatus, IRecordBuildStatus>(RecordBuildStatus, initialValues);
    }
}

/**
 * Event raised when the most recent conclusion of a repository's workflow has been recorded.
 */
export class BuildStatusRecorded {

    /**
     * The organization owning the repository.
     */
    @field(String)
    owner!: string;

    /**
     * The repository the workflow belongs to.
     */
    @field(String)
    repository!: string;

    /**
     * The workflow's name.
     */
    @field(String)
    workflow!: string;

    /**
     * How the most recent run concluded.
     */
    @field(Number)
    conclusion!: BuildConclusion;

    /**
     * The html URL of the most recent run.
     */
    @field(String)
    runUrl!: string;

    /**
     * When the most recent run finished.
     */
    @field(Date)
    ranAt!: Date;
}
