// @generated by Cratis. Source: Cratis.Chronicle.EventSequences.EventForEventSourceId. Time: 2026-08-08T17:17:47.5182270Z. Hash: 95372DC1CCABDAB1FDEDCAEC44152FCCAE99DF4FFC14705C8DA606E8AC56439C
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { field } from '@cratis/fundamentals';
import { Causation } from '../Auditing/Causation';

export class EventForEventSourceId {
    @field(String)
    eventSourceId!: string;
    @field(Object)
    event!: Record<string, unknown>;
    @field(Causation)
    causation?: Causation;
    @field(String)
    subject?: string;
    @field(String)
    eventStreamType!: string;
    @field(String)
    eventStreamId!: string;
    @field(String)
    eventSourceType!: string;
    @field(Date)
    occurred?: Date;
    @field(String, true)
    tags!: string[];
}
