// @generated by Cratis. Source: Planner.Accounts.ChangingPlan.ChangeAccountPlan, Planner.Accounts.ChangingPlan.ClaudeAccountPlanChanged. Time: 2026-08-08T17:20:55.2325870Z. Hash: 67815EA6A8D7DB6AD5AB1BE258DEB1BBD1C5FD7D6AA63F1753CD3105D2256E96
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { ClaudePlan } from '../ClaudePlan';
import { Guid, field } from '@cratis/fundamentals';

/**
 * Command for changing the subscription plan of a Claude account.
 */
export interface IChangeAccountPlan {
    
    /**
     * The identity of the account.
     */
    account?: Guid;
    
    /**
     * The new plan.
     */
    plan?: ClaudePlan;
}


/**
 * Command for changing the subscription plan of a Claude account.
 */
export class ChangeAccountPlan extends Command<IChangeAccountPlan, ClaudeAccountPlanChanged> implements IChangeAccountPlan {
    readonly route: string = '/api/accounts/changing-plan';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('account', Guid, false),
        new PropertyDescriptor('plan', Number, false),
    ];

    private _account!: Guid;
    private _plan!: ClaudePlan;

    constructor() {
        super(ClaudeAccountPlanChanged, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The identity of the account.
     */
    get account(): Guid {
        return this._account;
    }

    set account(value: Guid) {
        this._account = value;
        this.propertyChanged('account');
    }
    /**
     * The new plan.
     */
    get plan(): ClaudePlan {
        return this._plan;
    }

    set plan(value: ClaudePlan) {
        this._plan = value;
        this.propertyChanged('plan');
    }

    static use(initialValues?: IChangeAccountPlan): [ChangeAccountPlan, SetCommandValues<IChangeAccountPlan>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<ChangeAccountPlan, IChangeAccountPlan>(ChangeAccountPlan, initialValues);
    }
}

/**
 * Event raised when the subscription plan of a Claude account has changed - the scheduler adjusts its usage boundaries accordingly.
 */
export class ClaudeAccountPlanChanged {

    /**
     * The new plan.
     */
    @field(Number)
    plan!: ClaudePlan;
}
