// @generated by Cratis. Source: Planner.Issues.Grouping.Listing.Group, Planner.Issues.Grouping.Listing.Group. Time: 2026-08-08T21:11:05.5434570Z. Hash: 18690DAABCF01B6AB393D068732A7CCD03FD32C51DACB7951E402F1DEF20D79B
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { ObservableQueryFor, QueryResultWithState, Sorting, Paging, ChangeSet } from '@cratis/arc/queries';
import { useObservableQuery, useObservableQueryWithPaging, useSuspenseObservableQuery, useSuspenseObservableQueryWithPaging, useChangeStream, SetSorting, SetPage, SetPageSize, ObservableQueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { field } from '@cratis/fundamentals';

class AllGroupsSortBy {

    constructor(readonly query: AllGroups) {
    }

}

class AllGroupsSortByWithoutQuery {

}


/**
 * Observes all groups.
 */
export class AllGroups extends ObservableQueryFor<Group[]> {
    readonly route: string = '/api/issues/grouping/listing/all-groups';
    readonly queryName: string = 'Planner.Issues.Grouping.Listing.Group.AllGroups';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: Group[] = [];
    private readonly _sortBy: AllGroupsSortBy;
    private static readonly _sortBy: AllGroupsSortByWithoutQuery = new AllGroupsSortByWithoutQuery();

    constructor() {
        super(Group, true);
        this._sortBy = new AllGroupsSortBy(this);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];


    get sortBy(): AllGroupsSortBy {
        return this._sortBy;
    }

    static get sortBy(): AllGroupsSortByWithoutQuery {
        return this._sortBy;
    }

    static use(sorting?: Sorting): [QueryResultWithState<Group[]>, SetSorting] {
        return useObservableQuery<Group[], AllGroups>(AllGroups, undefined, sorting);
    }

    static useWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<Group[]>, SetSorting, SetPage, SetPageSize] {
        return useObservableQueryWithPaging<Group[], AllGroups>(AllGroups, new Paging(0, pageSize), undefined, sorting);
    }

    static useSuspense(sorting?: Sorting): [QueryResultWithState<Group[]>, SetSorting] {
        return useSuspenseObservableQuery<Group[], AllGroups>(AllGroups, undefined, sorting);
    }

    static useSuspenseWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<Group[]>, SetSorting, SetPage, SetPageSize] {
        return useSuspenseObservableQueryWithPaging<Group[], AllGroups>(AllGroups, new Paging(0, pageSize), undefined, sorting);
    }

    static useChangeStream(getKey?: (item: Group) => unknown, sorting?: Sorting): ChangeSet<Group> {
        return useChangeStream<Group, AllGroups>(AllGroups, undefined, getKey, sorting);
    }

    static when(condition: boolean): ObservableQueryWhen<AllGroups, Group[]> {
        return new ObservableQueryWhen<AllGroups, Group[]>(AllGroups, condition);
    }
}

/**
 * Read model for listing the issue groups.
 */
export class Group {

    /**
     * The group identity.
     */
    @field(String)
    id!: string;

    /**
     * The display name of the group.
     */
    @field(String)
    name!: string;

    /**
     * Extra instructions attached to the group for the agent working on it.
     */
    @field(String)
    prompt?: string;
}
