// @generated by Cratis. Source: Planner.Issues.Grouping.Creating.CreateGroup, Planner.Issues.Grouping.Creating.IssueAddedToGroup. Time: 2026-08-08T17:17:47.5182270Z. Hash: DA0037B033A6E3D12A209045D8DCFBC3F79FE358CE1916F62A6E6C23946233D3
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command, CommandValidator } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { EventForEventSourceId } from '../../../Chronicle/EventSequences/EventForEventSourceId';
import { field } from '@cratis/fundamentals';

/**
 * Command for creating a group of issues - typically by dropping one issue onto another. The issues in a group are scheduled together: work starts only when every issue in the group is ready for development.
 */
export interface ICreateGroup {
    
    /**
     * The identities of the issues forming the group.
     */
    issues?: string[];
    
    /**
     * The display name of the group.
     */
    name?: string;
}

export class CreateGroupValidator extends CommandValidator<ICreateGroup> {
    constructor() {
        super();
        this.ruleFor(c => c.issues).notEmpty().withMessage('A group needs at least one issue');
        this.ruleFor(c => c.name).notEmpty().withMessage('A group name is required');
    }
}

/**
 * Command for creating a group of issues - typically by dropping one issue onto another. The issues in a group are scheduled together: work starts only when every issue in the group is ready for development.
 */
export class CreateGroup extends Command<ICreateGroup, EventForEventSourceId> implements ICreateGroup {
    readonly route: string = '/api/issues/grouping/creating';
    readonly validation: CommandValidator = new CreateGroupValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('issues', String, false),
        new PropertyDescriptor('name', String, false),
    ];

    private _issues!: string[];
    private _name!: string;

    constructor() {
        super(EventForEventSourceId, true);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The identities of the issues forming the group.
     */
    get issues(): string[] {
        return this._issues;
    }

    set issues(value: string[]) {
        this._issues = value;
        this.propertyChanged('issues');
    }
    /**
     * The display name of the group.
     */
    get name(): string {
        return this._name;
    }

    set name(value: string) {
        this._name = value;
        this.propertyChanged('name');
    }

    static use(initialValues?: ICreateGroup): [CreateGroup, SetCommandValues<ICreateGroup>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<CreateGroup, ICreateGroup>(CreateGroup, initialValues);
    }
}

/**
 * Event raised when an issue has been added to a group - appended to the issue's own stream.
 */
export class IssueAddedToGroup {

    /**
     * The identity of the group the issue was added to.
     */
    @field(String)
    group!: string;
}
