// @generated by Cratis. Source: Planner.Issues.Renaming.RenameIssue, Planner.Issues.Renaming.IssueRenamed. Time: 2026-08-08T17:17:47.5182270Z. Hash: 0B94FBE31C6EE45F38EFE7288A579A21513D78B1EA66BD83E35CC8BD4C052009
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command, CommandValidator } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { field } from '@cratis/fundamentals';

/**
 * Command for renaming an issue - mirroring a title edit on GitHub.
 */
export interface IRenameIssue {
    
    /**
     * The identity of the issue.
     */
    issue?: string;
    
    /**
     * The new title.
     */
    title?: string;
}

export class RenameIssueValidator extends CommandValidator<IRenameIssue> {
    constructor() {
        super();
        this.ruleFor(c => c.title).notEmpty().withMessage('A title is required');
    }
}

/**
 * Command for renaming an issue - mirroring a title edit on GitHub.
 */
export class RenameIssue extends Command<IRenameIssue, IssueRenamed> implements IRenameIssue {
    readonly route: string = '/api/issues/renaming';
    readonly validation: CommandValidator = new RenameIssueValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('issue', String, false),
        new PropertyDescriptor('title', String, false),
    ];

    private _issue!: string;
    private _title!: string;

    constructor() {
        super(IssueRenamed, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The identity of the issue.
     */
    get issue(): string {
        return this._issue;
    }

    set issue(value: string) {
        this._issue = value;
        this.propertyChanged('issue');
    }
    /**
     * The new title.
     */
    get title(): string {
        return this._title;
    }

    set title(value: string) {
        this._title = value;
        this.propertyChanged('title');
    }

    static use(initialValues?: IRenameIssue): [RenameIssue, SetCommandValues<IRenameIssue>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<RenameIssue, IRenameIssue>(RenameIssue, initialValues);
    }
}

/**
 * Event raised when an issue's title has changed on GitHub.
 */
export class IssueRenamed {

    /**
     * The new title.
     */
    @field(String)
    title!: string;
}
