// @generated by Cratis. Source: Planner.Issues.Grouping.AddingIssue.AddIssueToGroup. Time: 2026-08-08T17:17:47.5182270Z. Hash: 244E1CD9709CAAC203F82A71C32500D2E8DECCE59941CD8BB4C83B09998825DF
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { IssueAddedToGroup } from '../Creating/Creating';

/**
 * Command for adding an issue to an existing group - dragging an issue into the group.
 */
export interface IAddIssueToGroup {
    
    /**
     * The identity of the group.
     */
    group?: string;
    
    /**
     * The identity of the issue to add.
     */
    issue?: string;
}


/**
 * Command for adding an issue to an existing group - dragging an issue into the group.
 */
export class AddIssueToGroup extends Command<IAddIssueToGroup, IssueAddedToGroup> implements IAddIssueToGroup {
    readonly route: string = '/api/issues/grouping/adding-issue';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('group', String, false),
        new PropertyDescriptor('issue', String, false),
    ];

    private _group!: string;
    private _issue!: string;

    constructor() {
        super(IssueAddedToGroup, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The identity of the group.
     */
    get group(): string {
        return this._group;
    }

    set group(value: string) {
        this._group = value;
        this.propertyChanged('group');
    }
    /**
     * The identity of the issue to add.
     */
    get issue(): string {
        return this._issue;
    }

    set issue(value: string) {
        this._issue = value;
        this.propertyChanged('issue');
    }

    static use(initialValues?: IAddIssueToGroup): [AddIssueToGroup, SetCommandValues<IAddIssueToGroup>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<AddIssueToGroup, IAddIssueToGroup>(AddIssueToGroup, initialValues);
    }
}
