// @generated by Cratis. Source: Planner.Repositories.Groups.Creating.CreateRepositoryGroup. Time: 2026-08-08T21:11:05.5434570Z. Hash: C38D649C7A30E232D07E2FCDA8EB87A3589B19B5AB7F791E3E03AAC5AE4AB4EC
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command, CommandValidator } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { Guid } from '@cratis/fundamentals';

/**
 * Command for creating a named group of repositories - selectable as a unit when scheduling ad-hoc work.
 */
export interface ICreateRepositoryGroup {
    
    /**
     * The display name of the group.
     */
    name?: string;
    
    /**
     * The identities of the repositories in the group.
     */
    repositories?: string[];
}

export class CreateRepositoryGroupValidator extends CommandValidator<ICreateRepositoryGroup> {
    constructor() {
        super();
        this.ruleFor(c => c.name).notEmpty().withMessage('A group name is required');
        this.ruleFor(c => c.repositories).notEmpty().withMessage('A group needs at least one repository');
    }
}

/**
 * Command for creating a named group of repositories - selectable as a unit when scheduling ad-hoc work.
 */
export class CreateRepositoryGroup extends Command<ICreateRepositoryGroup, Guid> implements ICreateRepositoryGroup {
    readonly route: string = '/api/repositories/groups/creating';
    readonly validation: CommandValidator = new CreateRepositoryGroupValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('name', String, false),
        new PropertyDescriptor('repositories', String, false),
    ];

    private _name!: string;
    private _repositories!: string[];

    constructor() {
        super(Guid, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The display name of the group.
     */
    get name(): string {
        return this._name;
    }

    set name(value: string) {
        this._name = value;
        this.propertyChanged('name');
    }
    /**
     * The identities of the repositories in the group.
     */
    get repositories(): string[] {
        return this._repositories;
    }

    set repositories(value: string[]) {
        this._repositories = value;
        this.propertyChanged('repositories');
    }

    static use(initialValues?: ICreateRepositoryGroup): [CreateRepositoryGroup, SetCommandValues<ICreateRepositoryGroup>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<CreateRepositoryGroup, ICreateRepositoryGroup>(CreateRepositoryGroup, initialValues);
    }
}
