// @generated by Cratis. Source: Planner.Issues.Grouping.RemovingIssue.RemoveIssueFromGroup, Planner.Issues.Grouping.RemovingIssue.IssueRemovedFromGroup. Time: 2026-08-08T17:17:47.5182270Z. Hash: F271DB1772DD18669A20FD6B41B84B0387992212690DDADCE7097A5561199EFD
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';

/**
 * Command for removing an issue from its group - dragging an issue out of the group.
 */
export interface IRemoveIssueFromGroup {
    
    /**
     * The identity of the issue to remove from its group.
     */
    issue?: string;
}


/**
 * Command for removing an issue from its group - dragging an issue out of the group.
 */
export class RemoveIssueFromGroup extends Command<IRemoveIssueFromGroup, IssueRemovedFromGroup> implements IRemoveIssueFromGroup {
    readonly route: string = '/api/issues/grouping/removing-issue';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('issue', String, false),
    ];

    private _issue!: string;

    constructor() {
        super(IssueRemovedFromGroup, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The identity of the issue to remove from its group.
     */
    get issue(): string {
        return this._issue;
    }

    set issue(value: string) {
        this._issue = value;
        this.propertyChanged('issue');
    }

    static use(initialValues?: IRemoveIssueFromGroup): [RemoveIssueFromGroup, SetCommandValues<IRemoveIssueFromGroup>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<RemoveIssueFromGroup, IRemoveIssueFromGroup>(RemoveIssueFromGroup, initialValues);
    }
}

/**
 * Event raised when an issue has been removed from its group.
 */
export class IssueRemovedFromGroup {
}
