// @generated by Cratis. Source: Planner.Repositories.Organizations.Listing.Organization, Planner.Repositories.Organizations.Listing.Organization. Time: 2026-08-08T17:09:59.4947360Z. Hash: 2E7A7EA3944C8178D53A82A6D17F03ADB2A495634B61933FE7D12CF07B75A9CA
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { ObservableQueryFor, QueryResultWithState, Sorting, Paging, ChangeSet } from '@cratis/arc/queries';
import { useObservableQuery, useObservableQueryWithPaging, useSuspenseObservableQuery, useSuspenseObservableQueryWithPaging, useChangeStream, SetSorting, SetPage, SetPageSize, ObservableQueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { field } from '@cratis/fundamentals';

class AllOrganizationsSortBy {

    constructor(readonly query: AllOrganizations) {
    }

}

class AllOrganizationsSortByWithoutQuery {

}


/**
 * Observes all organizations.
 */
export class AllOrganizations extends ObservableQueryFor<Organization[]> {
    readonly route: string = '/api/repositories/organizations/listing/all-organizations';
    readonly queryName: string = 'Planner.Repositories.Organizations.Listing.Organization.AllOrganizations';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: Organization[] = [];
    private readonly _sortBy: AllOrganizationsSortBy;
    private static readonly _sortBy: AllOrganizationsSortByWithoutQuery = new AllOrganizationsSortByWithoutQuery();

    constructor() {
        super(Organization, true);
        this._sortBy = new AllOrganizationsSortBy(this);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];


    get sortBy(): AllOrganizationsSortBy {
        return this._sortBy;
    }

    static get sortBy(): AllOrganizationsSortByWithoutQuery {
        return this._sortBy;
    }

    static use(sorting?: Sorting): [QueryResultWithState<Organization[]>, SetSorting] {
        return useObservableQuery<Organization[], AllOrganizations>(AllOrganizations, undefined, sorting);
    }

    static useWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<Organization[]>, SetSorting, SetPage, SetPageSize] {
        return useObservableQueryWithPaging<Organization[], AllOrganizations>(AllOrganizations, new Paging(0, pageSize), undefined, sorting);
    }

    static useSuspense(sorting?: Sorting): [QueryResultWithState<Organization[]>, SetSorting] {
        return useSuspenseObservableQuery<Organization[], AllOrganizations>(AllOrganizations, undefined, sorting);
    }

    static useSuspenseWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<Organization[]>, SetSorting, SetPage, SetPageSize] {
        return useSuspenseObservableQueryWithPaging<Organization[], AllOrganizations>(AllOrganizations, new Paging(0, pageSize), undefined, sorting);
    }

    static useChangeStream(getKey?: (item: Organization) => unknown, sorting?: Sorting): ChangeSet<Organization> {
        return useChangeStream<Organization, AllOrganizations>(AllOrganizations, undefined, getKey, sorting);
    }

    static when(condition: boolean): ObservableQueryWhen<AllOrganizations, Organization[]> {
        return new ObservableQueryWhen<AllOrganizations, Organization[]>(AllOrganizations, condition);
    }
}

/**
 * Read model for listing the organizations the Planner tracks.
 */
export class Organization {

    /**
     * The organization identity.
     */
    @field(String)
    id!: string;

    /**
     * The name of the organization.
     */
    @field(String)
    name!: string;
}
