// @generated by Cratis. Source: Planner.Repositories.Organizations.Listing.Organization, Planner.Repositories.Organizations.Listing.Organization. Time: 2026-08-19T16:32:25.3218460Z. Hash: 761E0C077F276358E968E77312424997B12B206E37EA5B9D22DEF30C7C163B3A
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { ObservableQueryFor, QueryResultWithState, Sorting, Paging, ChangeSet } from '@cratis/arc/queries';
import { useObservableQuery, useObservableQueryWithPaging, useSuspenseObservableQuery, useSuspenseObservableQueryWithPaging, useChangeStream, SetSorting, SetPage, SetPageSize, ObservableQueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { field } from '@cratis/fundamentals';
import { OrganizationTrackingPolicy } from '../OrganizationTrackingPolicy';
import { RepositoryDiscoveryStatus } from '../RepositoryDiscoveryStatus';

class AllOrganizationsSortBy {

    constructor(readonly query: AllOrganizations) {
    }

}

class AllOrganizationsSortByWithoutQuery {

}


/**
 * Observes all organizations.
 */
export class AllOrganizations extends ObservableQueryFor<Organization[]> {
    readonly route: string = '/api/repositories/organizations/listing/all-organizations';
    readonly queryName: string = 'Planner.Repositories.Organizations.Listing.Organization.AllOrganizations';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: Organization[] = [];
    private readonly _sortBy: AllOrganizationsSortBy;
    private static readonly _sortBy: AllOrganizationsSortByWithoutQuery = new AllOrganizationsSortByWithoutQuery();

    constructor() {
        super(Organization, true);
        this._sortBy = new AllOrganizationsSortBy(this);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];


    get sortBy(): AllOrganizationsSortBy {
        return this._sortBy;
    }

    static get sortBy(): AllOrganizationsSortByWithoutQuery {
        return this._sortBy;
    }

    static use(sorting?: Sorting): [QueryResultWithState<Organization[]>, SetSorting] {
        return useObservableQuery<Organization[], AllOrganizations>(AllOrganizations, undefined, sorting);
    }

    static useWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<Organization[]>, SetSorting, SetPage, SetPageSize] {
        return useObservableQueryWithPaging<Organization[], AllOrganizations>(AllOrganizations, new Paging(0, pageSize), undefined, sorting);
    }

    static useSuspense(sorting?: Sorting): [QueryResultWithState<Organization[]>, SetSorting] {
        return useSuspenseObservableQuery<Organization[], AllOrganizations>(AllOrganizations, undefined, sorting);
    }

    static useSuspenseWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<Organization[]>, SetSorting, SetPage, SetPageSize] {
        return useSuspenseObservableQueryWithPaging<Organization[], AllOrganizations>(AllOrganizations, new Paging(0, pageSize), undefined, sorting);
    }

    static useChangeStream(getKey?: (item: Organization) => unknown, sorting?: Sorting): ChangeSet<Organization> {
        return useChangeStream<Organization, AllOrganizations>(AllOrganizations, undefined, getKey, sorting);
    }

    static when(condition: boolean): ObservableQueryWhen<AllOrganizations, Organization[]> {
        return new ObservableQueryWhen<AllOrganizations, Organization[]>(AllOrganizations, condition);
    }
}

/**
 * Read model for listing the organizations the Planner tracks, together with how discovering their repositories went - an organization whose repositories could never be looked up has to say so rather than sit in the list looking like every other one.
 */
export class Organization {

    /**
     * The organization identity.
     */
    @field(String)
    id!: string;

    /**
     * The name of the organization.
     */
    @field(String)
    name!: string;

    /**
     * How far repository discovery got.
     */
    @field(Number)
    discoveryStatus!: RepositoryDiscoveryStatus;

    /**
     * Whether every repository is tracked automatically, or only ones explicitly selected.
     */
    @field(Number)
    trackingPolicy!: OrganizationTrackingPolicy;

    /**
     * The names of every repository discovery found - the pool a &quot;Selected&quot; organization picks from.
     */
    @field(String, true)
    discoveredRepositories?: string[];

    /**
     * Why discovery failed - empty unless {@link DiscoveryStatus} is {@link Failed}.
     */
    @field(String)
    discoveryFailure!: string;

    /**
     * The number of repositories discovery found - `0` until it succeeds.
     */
    @field(Number)
    repositoryCount!: number;
}
