// @generated by Cratis. Source: Planner.PullRequests.Listing.PullRequest, Planner.PullRequests.Listing.PullRequest, Planner.PullRequests.Listing.PullRequest. Time: 2026-08-19T12:35:46.4721490Z. Hash: 553F8DB076997B2ECAF06665B5C066D074C613ADACC1AADF8B85934BA0260BB9
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { ObservableQueryFor, QueryResultWithState, Sorting, Paging, ChangeSet } from '@cratis/arc/queries';
import { useObservableQuery, useObservableQueryWithPaging, useSuspenseObservableQuery, useSuspenseObservableQueryWithPaging, useChangeStream, SetSorting, SetPage, SetPageSize, ObservableQueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { field } from '@cratis/fundamentals';

class AllPullRequestsSortBy {

    constructor(readonly query: AllPullRequests) {
    }

}

class AllPullRequestsSortByWithoutQuery {

}


/**
 * Observes every pull request mirrored across every tracked repository, open, merged and closed alike - the history view behind the &quot;Show done&quot; toggle. {@link OpenPullRequests} is what the default view uses.
 */
export class AllPullRequests extends ObservableQueryFor<PullRequest[]> {
    readonly route: string = '/api/pull-requests/listing/all-pull-requests';
    readonly queryName: string = 'Planner.PullRequests.Listing.PullRequest.AllPullRequests';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: PullRequest[] = [];
    private readonly _sortBy: AllPullRequestsSortBy;
    private static readonly _sortBy: AllPullRequestsSortByWithoutQuery = new AllPullRequestsSortByWithoutQuery();

    constructor() {
        super(PullRequest, true);
        this._sortBy = new AllPullRequestsSortBy(this);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];


    get sortBy(): AllPullRequestsSortBy {
        return this._sortBy;
    }

    static get sortBy(): AllPullRequestsSortByWithoutQuery {
        return this._sortBy;
    }

    static use(sorting?: Sorting): [QueryResultWithState<PullRequest[]>, SetSorting] {
        return useObservableQuery<PullRequest[], AllPullRequests>(AllPullRequests, undefined, sorting);
    }

    static useWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<PullRequest[]>, SetSorting, SetPage, SetPageSize] {
        return useObservableQueryWithPaging<PullRequest[], AllPullRequests>(AllPullRequests, new Paging(0, pageSize), undefined, sorting);
    }

    static useSuspense(sorting?: Sorting): [QueryResultWithState<PullRequest[]>, SetSorting] {
        return useSuspenseObservableQuery<PullRequest[], AllPullRequests>(AllPullRequests, undefined, sorting);
    }

    static useSuspenseWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<PullRequest[]>, SetSorting, SetPage, SetPageSize] {
        return useSuspenseObservableQueryWithPaging<PullRequest[], AllPullRequests>(AllPullRequests, new Paging(0, pageSize), undefined, sorting);
    }

    static useChangeStream(getKey?: (item: PullRequest) => unknown, sorting?: Sorting): ChangeSet<PullRequest> {
        return useChangeStream<PullRequest, AllPullRequests>(AllPullRequests, undefined, getKey, sorting);
    }

    static when(condition: boolean): ObservableQueryWhen<AllPullRequests, PullRequest[]> {
        return new ObservableQueryWhen<AllPullRequests, PullRequest[]>(AllPullRequests, condition);
    }
}

class OpenPullRequestsSortBy {

    constructor(readonly query: OpenPullRequests) {
    }

}

class OpenPullRequestsSortByWithoutQuery {

}


/**
 * Observes the pull requests that are still open on GitHub - the default view, so a merged or closed pull request disappears the moment the mirror learns about it.
 */
export class OpenPullRequests extends ObservableQueryFor<PullRequest[]> {
    readonly route: string = '/api/pull-requests/listing/open-pull-requests';
    readonly queryName: string = 'Planner.PullRequests.Listing.PullRequest.OpenPullRequests';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: PullRequest[] = [];
    private readonly _sortBy: OpenPullRequestsSortBy;
    private static readonly _sortBy: OpenPullRequestsSortByWithoutQuery = new OpenPullRequestsSortByWithoutQuery();

    constructor() {
        super(PullRequest, true);
        this._sortBy = new OpenPullRequestsSortBy(this);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];


    get sortBy(): OpenPullRequestsSortBy {
        return this._sortBy;
    }

    static get sortBy(): OpenPullRequestsSortByWithoutQuery {
        return this._sortBy;
    }

    static use(sorting?: Sorting): [QueryResultWithState<PullRequest[]>, SetSorting] {
        return useObservableQuery<PullRequest[], OpenPullRequests>(OpenPullRequests, undefined, sorting);
    }

    static useWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<PullRequest[]>, SetSorting, SetPage, SetPageSize] {
        return useObservableQueryWithPaging<PullRequest[], OpenPullRequests>(OpenPullRequests, new Paging(0, pageSize), undefined, sorting);
    }

    static useSuspense(sorting?: Sorting): [QueryResultWithState<PullRequest[]>, SetSorting] {
        return useSuspenseObservableQuery<PullRequest[], OpenPullRequests>(OpenPullRequests, undefined, sorting);
    }

    static useSuspenseWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<PullRequest[]>, SetSorting, SetPage, SetPageSize] {
        return useSuspenseObservableQueryWithPaging<PullRequest[], OpenPullRequests>(OpenPullRequests, new Paging(0, pageSize), undefined, sorting);
    }

    static useChangeStream(getKey?: (item: PullRequest) => unknown, sorting?: Sorting): ChangeSet<PullRequest> {
        return useChangeStream<PullRequest, OpenPullRequests>(OpenPullRequests, undefined, getKey, sorting);
    }

    static when(condition: boolean): ObservableQueryWhen<OpenPullRequests, PullRequest[]> {
        return new ObservableQueryWhen<OpenPullRequests, PullRequest[]>(OpenPullRequests, condition);
    }
}

/**
 * Read model for the pull request list - every pull request mirrored from GitHub across the Planner's tracked repositories, kept current by the GitHub webhook.
 */
export class PullRequest {

    /**
     * The pull request identity - the predictable `{org}-{repo}-{number}` key.
     */
    @field(String)
    id!: string;

    /**
     * The organization owning the repository the pull request lives in.
     */
    @field(String)
    owner!: string;

    /**
     * The repository the pull request lives in.
     */
    @field(String)
    repository!: string;

    /**
     * The pull request number.
     */
    @field(Number)
    number!: number;

    /**
     * The pull request title.
     */
    @field(String)
    title!: string;

    /**
     * The login of the user that opened the pull request.
     */
    @field(String)
    createdBy!: string;

    /**
     * When the pull request was opened on GitHub.
     */
    @field(Date)
    createdAt!: Date;

    /**
     * The URL of the pull request on GitHub.
     */
    @field(String)
    url!: string;

    /**
     * Whether the pull request is currently open.
     */
    @field(Boolean)
    isOpen!: boolean;

    /**
     * Whether the pull request was merged - `null` until it closes.
     */
    @field(Boolean)
    merged?: boolean;

    /**
     * The markdown body of the pull request.
     */
    @field(String)
    body?: string;

    /**
     * The labels on the pull request.
     */
    @field(String, true)
    labels?: string[];

    /**
     * Whether the pull request is a draft - `null` until a detail update reports it.
     */
    @field(Boolean)
    draft?: boolean;

    /**
     * The branch the pull request merges from.
     */
    @field(String)
    headBranch?: string;

    /**
     * The branch the pull request merges into.
     */
    @field(String)
    baseBranch?: string;
}
