// @generated by Cratis. Source: Planner.Accounts.SettingToken.SetAccountToken, Planner.Accounts.SettingToken.ClaudeAccountTokenSet. Time: 2026-08-08T17:20:55.2325870Z. Hash: 6706DCA6F7CDB0ADF9C3A8D352A7017AC267C49DFD39DF7F4AF5FE8A4CBCF945
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command, CommandValidator } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { Guid, field } from '@cratis/fundamentals';

/**
 * Command for setting (or rotating) the Claude CLI token of an account.
 */
export interface ISetAccountToken {
    
    /**
     * The identity of the account.
     */
    account?: Guid;
    
    /**
     * The token the Claude CLI authenticates with.
     */
    token?: string;
}

export class SetAccountTokenValidator extends CommandValidator<ISetAccountToken> {
    constructor() {
        super();
        this.ruleFor(c => c.token).notEmpty().withMessage('A token is required');
    }
}

/**
 * Command for setting (or rotating) the Claude CLI token of an account.
 */
export class SetAccountToken extends Command<ISetAccountToken, ClaudeAccountTokenSet> implements ISetAccountToken {
    readonly route: string = '/api/accounts/setting-token';
    readonly validation: CommandValidator = new SetAccountTokenValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('account', Guid, false),
        new PropertyDescriptor('token', String, false),
    ];

    private _account!: Guid;
    private _token!: string;

    constructor() {
        super(ClaudeAccountTokenSet, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The identity of the account.
     */
    get account(): Guid {
        return this._account;
    }

    set account(value: Guid) {
        this._account = value;
        this.propertyChanged('account');
    }
    /**
     * The token the Claude CLI authenticates with.
     */
    get token(): string {
        return this._token;
    }

    set token(value: string) {
        this._token = value;
        this.propertyChanged('token');
    }

    static use(initialValues?: ISetAccountToken): [SetAccountToken, SetCommandValues<ISetAccountToken>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<SetAccountToken, ISetAccountToken>(SetAccountToken, initialValues);
    }
}

/**
 * Event raised when the Claude CLI token of an account has been set - workers scheduled on the account authenticate with the most recently set token.
 */
export class ClaudeAccountTokenSet {

    /**
     * The token.
     */
    @field(String)
    token!: string;
}
