// @generated by Cratis. Source: Planner.Roadmap.GeneratingPlan.GeneratePlan, Planner.Roadmap.GeneratingPlan.FailPlanGeneration, Planner.Roadmap.GeneratingPlan.PlanGenerated, Planner.Roadmap.GeneratingPlan.PlanGenerationFailed. Time: 2026-08-19T16:55:58.0712010Z. Hash: 3AB5BF4EEFD5A69E289FA82DFA22396A0689945166923A63EEF044A6451871BF
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { Guid, field } from '@cratis/fundamentals';

/**
 * Command for recording a generated plan - executed by the plan generation reactor once the language model has produced one.
 */
export interface IGeneratePlan {
    
    /**
     * The markdown content of the plan.
     */
    content?: string;
    
    /**
     * The identity of the plan.
     */
    plan?: Guid;
}


/**
 * Command for recording a generated plan - executed by the plan generation reactor once the language model has produced one.
 */
export class GeneratePlan extends Command<IGeneratePlan, PlanGenerated> implements IGeneratePlan {
    readonly route: string = '/api/roadmap/generating-plan/generate-plan';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('content', String, false),
        new PropertyDescriptor('plan', Guid, false),
    ];

    private _content!: string;
    private _plan!: Guid;

    constructor() {
        super(PlanGenerated, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The markdown content of the plan.
     */
    get content(): string {
        return this._content;
    }

    set content(value: string) {
        this._content = value;
        this.propertyChanged('content');
    }
    /**
     * The identity of the plan.
     */
    get plan(): Guid {
        return this._plan;
    }

    set plan(value: Guid) {
        this._plan = value;
        this.propertyChanged('plan');
    }

    static use(initialValues?: IGeneratePlan): [GeneratePlan, SetCommandValues<IGeneratePlan>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<GeneratePlan, IGeneratePlan>(GeneratePlan, initialValues);
    }
}

/**
 * Command for recording that generating a plan failed.
 */
export interface IFailPlanGeneration {
    
    /**
     * The identity of the plan.
     */
    plan?: Guid;
    
    /**
     * Why it failed.
     */
    reason?: string;
}


/**
 * Command for recording that generating a plan failed.
 */
export class FailPlanGeneration extends Command<IFailPlanGeneration, PlanGenerationFailed> implements IFailPlanGeneration {
    readonly route: string = '/api/roadmap/generating-plan/fail-plan-generation';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('plan', Guid, false),
        new PropertyDescriptor('reason', String, false),
    ];

    private _plan!: Guid;
    private _reason!: string;

    constructor() {
        super(PlanGenerationFailed, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The identity of the plan.
     */
    get plan(): Guid {
        return this._plan;
    }

    set plan(value: Guid) {
        this._plan = value;
        this.propertyChanged('plan');
    }
    /**
     * Why it failed.
     */
    get reason(): string {
        return this._reason;
    }

    set reason(value: string) {
        this._reason = value;
        this.propertyChanged('reason');
    }

    static use(initialValues?: IFailPlanGeneration): [FailPlanGeneration, SetCommandValues<IFailPlanGeneration>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<FailPlanGeneration, IFailPlanGeneration>(FailPlanGeneration, initialValues);
    }
}

/**
 * Event raised when a plan has been generated.
 */
export class PlanGenerated {

    /**
     * The markdown content of the plan.
     */
    @field(String)
    content!: string;
}

/**
 * Event raised when generating a plan failed - most commonly, no language model is configured.
 */
export class PlanGenerationFailed {

    /**
     * Why it failed.
     */
    @field(String)
    reason!: string;
}
