// @generated by Cratis. Source: Planner.Issues.Grouping.Deleting.DeleteGroup. Time: 2026-08-14T07:09:17.3663546Z. Hash: 3BD21E41652D1E7CC4FF4EECAA218E1B84B23B135AF168FE9619D1875C7B7AA1
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';

/**
 * Command for deleting a group, releasing all its member issues. The caller supplies the current members - the frontend already holds them from the issue list.
 */
export interface IDeleteGroup {
    
    /**
     * The identity of the group to delete.
     */
    group?: string;
    
    /**
     * The identities of the issues currently in the group.
     */
    issues?: string[];
}


/**
 * Command for deleting a group, releasing all its member issues. The caller supplies the current members - the frontend already holds them from the issue list.
 */
export class DeleteGroup extends Command<IDeleteGroup> implements IDeleteGroup {
    readonly route: string = '/api/issues/grouping/deleting';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('group', String, false),
        new PropertyDescriptor('issues', String, false),
    ];

    private _group!: string;
    private _issues!: string[];

    constructor() {
        super(Object, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The identity of the group to delete.
     */
    get group(): string {
        return this._group;
    }

    set group(value: string) {
        this._group = value;
        this.propertyChanged('group');
    }
    /**
     * The identities of the issues currently in the group.
     */
    get issues(): string[] {
        return this._issues;
    }

    set issues(value: string[]) {
        this._issues = value;
        this.propertyChanged('issues');
    }

    static use(initialValues?: IDeleteGroup): [DeleteGroup, SetCommandValues<IDeleteGroup>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<DeleteGroup, IDeleteGroup>(DeleteGroup, initialValues);
    }
}
