// @generated by Cratis. Source: Planner.Work.Starting.StartWork, Planner.Work.Starting.WorkStarted. Time: 2026-08-08T17:35:38.1733570Z. Hash: 91966E9573A191C557453B7B6C7BA91BCCC7DA9572390707D3BA50409EE79030
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { Guid, field } from '@cratis/fundamentals';

/**
 * Command for recording that a unit of work has been dispatched to a worker - executed by the scheduler after it launched the container.
 */
export interface IStartWork {
    
    /**
     * The Claude account the work runs on.
     */
    account?: Guid;
    
    /**
     * The model the work runs with.
     */
    model?: string;
    
    /**
     * The identity of the work.
     */
    work?: Guid;
}


/**
 * Command for recording that a unit of work has been dispatched to a worker - executed by the scheduler after it launched the container.
 */
export class StartWork extends Command<IStartWork, WorkStarted> implements IStartWork {
    readonly route: string = '/api/work/starting';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('account', Guid, false),
        new PropertyDescriptor('model', String, false),
        new PropertyDescriptor('work', Guid, false),
    ];

    private _account!: Guid;
    private _model!: string;
    private _work!: Guid;

    constructor() {
        super(WorkStarted, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The Claude account the work runs on.
     */
    get account(): Guid {
        return this._account;
    }

    set account(value: Guid) {
        this._account = value;
        this.propertyChanged('account');
    }
    /**
     * The model the work runs with.
     */
    get model(): string {
        return this._model;
    }

    set model(value: string) {
        this._model = value;
        this.propertyChanged('model');
    }
    /**
     * The identity of the work.
     */
    get work(): Guid {
        return this._work;
    }

    set work(value: Guid) {
        this._work = value;
        this.propertyChanged('work');
    }

    static use(initialValues?: IStartWork): [StartWork, SetCommandValues<IStartWork>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<StartWork, IStartWork>(StartWork, initialValues);
    }
}

/**
 * Event raised when a unit of work has started running on a worker - it counts against the account's usage boundaries from this moment.
 */
export class WorkStarted {

    /**
     * The Claude account the work runs on.
     */
    @field(Guid)
    account!: Guid;

    /**
     * The model the work runs with.
     */
    @field(String)
    model!: string;
}
