// @generated by Cratis. Source: Planner.Alerts.Resolving.ResolveAlert, Planner.Alerts.Resolving.AlertResolved. Time: 2026-08-10T15:01:02.9193540Z. Hash: 765508984D154196834F2B5DA829F3734AE44D6B1CB76BC0A632479363D6AA1D
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { field } from '@cratis/fundamentals';

/**
 * Command for closing an alert a person dealt with - the counterpart to an agent resolving one itself.
 */
export interface IResolveAlert {
    
    /**
     * The identity of the alert.
     */
    alert?: string;
    
    /**
     * How it was resolved.
     */
    resolution?: string;
}


/**
 * Command for closing an alert a person dealt with - the counterpart to an agent resolving one itself.
 */
export class ResolveAlert extends Command<IResolveAlert, AlertResolved> implements IResolveAlert {
    readonly route: string = '/api/alerts/resolving';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('alert', String, false),
        new PropertyDescriptor('resolution', String, false),
    ];

    private _alert!: string;
    private _resolution!: string;

    constructor() {
        super(AlertResolved, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The identity of the alert.
     */
    get alert(): string {
        return this._alert;
    }

    set alert(value: string) {
        this._alert = value;
        this.propertyChanged('alert');
    }
    /**
     * How it was resolved.
     */
    get resolution(): string {
        return this._resolution;
    }

    set resolution(value: string) {
        this._resolution = value;
        this.propertyChanged('resolution');
    }

    static use(initialValues?: IResolveAlert): [ResolveAlert, SetCommandValues<IResolveAlert>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<ResolveAlert, IResolveAlert>(ResolveAlert, initialValues);
    }
}

/**
 * Event raised when a person resolved an alert.
 */
export class AlertResolved {

    /**
     * How it was resolved.
     */
    @field(String)
    resolution!: string;

    /**
     * The login of the user that resolved it.
     */
    @field(String)
    resolvedBy!: string;
}
