// @generated by Cratis. Source: Planner.Repositories.Groups.Deleting.DeleteRepositoryGroup, Planner.Repositories.Groups.Deleting.RepositoryGroupDeleted. Time: 2026-08-08T21:11:05.5434570Z. Hash: 0344768B2C46B9DB95964D772409CBA646027EB5865AD3EDA8377190605593A1
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { Guid } from '@cratis/fundamentals';

/**
 * Command for deleting a repository group.
 */
export interface IDeleteRepositoryGroup {
    
    /**
     * The identity of the group to delete.
     */
    group?: Guid;
}


/**
 * Command for deleting a repository group.
 */
export class DeleteRepositoryGroup extends Command<IDeleteRepositoryGroup, RepositoryGroupDeleted> implements IDeleteRepositoryGroup {
    readonly route: string = '/api/repositories/groups/deleting';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('group', Guid, false),
    ];

    private _group!: Guid;

    constructor() {
        super(RepositoryGroupDeleted, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The identity of the group to delete.
     */
    get group(): Guid {
        return this._group;
    }

    set group(value: Guid) {
        this._group = value;
        this.propertyChanged('group');
    }

    static use(initialValues?: IDeleteRepositoryGroup): [DeleteRepositoryGroup, SetCommandValues<IDeleteRepositoryGroup>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<DeleteRepositoryGroup, IDeleteRepositoryGroup>(DeleteRepositoryGroup, initialValues);
    }
}

/**
 * Event raised when a repository group has been deleted.
 */
export class RepositoryGroupDeleted {
}
