// @generated by Cratis. Source: Planner.Work.Listing.WorkItem, Planner.Work.Listing.WorkItem, Planner.Work.Listing.WorkItem. Time: 2026-08-19T12:13:16.9919440Z. Hash: 3C57ED3FACFB5E86E4F2DA8C27647A0781B683DFC98383FFDC80A8CEAD5254B7
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { ObservableQueryFor, QueryResultWithState, Sorting, Paging, ChangeSet } from '@cratis/arc/queries';
import { useObservableQuery, useObservableQueryWithPaging, useSuspenseObservableQuery, useSuspenseObservableQueryWithPaging, useChangeStream, SetSorting, SetPage, SetPageSize, ObservableQueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { field, Guid } from '@cratis/fundamentals';
import { WorkPurpose } from '../WorkPurpose';
import { WorkStatus } from '../WorkStatus';

class AllWorkSortBy {

    constructor(readonly query: AllWork) {
    }

}

class AllWorkSortByWithoutQuery {

}


/**
 * Observes all units of work, finished ones included - the history view behind the &quot;Show done&quot; toggle. {@link ActiveWork} is what the default view uses.
 */
export class AllWork extends ObservableQueryFor<WorkItem[]> {
    readonly route: string = '/api/work/listing/all-work';
    readonly queryName: string = 'Planner.Work.Listing.WorkItem.AllWork';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: WorkItem[] = [];
    private readonly _sortBy: AllWorkSortBy;
    private static readonly _sortBy: AllWorkSortByWithoutQuery = new AllWorkSortByWithoutQuery();

    constructor() {
        super(WorkItem, true);
        this._sortBy = new AllWorkSortBy(this);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];


    get sortBy(): AllWorkSortBy {
        return this._sortBy;
    }

    static get sortBy(): AllWorkSortByWithoutQuery {
        return this._sortBy;
    }

    static use(sorting?: Sorting): [QueryResultWithState<WorkItem[]>, SetSorting] {
        return useObservableQuery<WorkItem[], AllWork>(AllWork, undefined, sorting);
    }

    static useWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<WorkItem[]>, SetSorting, SetPage, SetPageSize] {
        return useObservableQueryWithPaging<WorkItem[], AllWork>(AllWork, new Paging(0, pageSize), undefined, sorting);
    }

    static useSuspense(sorting?: Sorting): [QueryResultWithState<WorkItem[]>, SetSorting] {
        return useSuspenseObservableQuery<WorkItem[], AllWork>(AllWork, undefined, sorting);
    }

    static useSuspenseWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<WorkItem[]>, SetSorting, SetPage, SetPageSize] {
        return useSuspenseObservableQueryWithPaging<WorkItem[], AllWork>(AllWork, new Paging(0, pageSize), undefined, sorting);
    }

    static useChangeStream(getKey?: (item: WorkItem) => unknown, sorting?: Sorting): ChangeSet<WorkItem> {
        return useChangeStream<WorkItem, AllWork>(AllWork, undefined, getKey, sorting);
    }

    static when(condition: boolean): ObservableQueryWhen<AllWork, WorkItem[]> {
        return new ObservableQueryWhen<AllWork, WorkItem[]>(AllWork, condition);
    }
}

class ActiveWorkSortBy {

    constructor(readonly query: ActiveWork) {
    }

}

class ActiveWorkSortByWithoutQuery {

}


/**
 * Observes the units of work that have not reached a terminal state yet - the default view, so completed, failed and stopped work disappears from the board once it is done.
 */
export class ActiveWork extends ObservableQueryFor<WorkItem[]> {
    readonly route: string = '/api/work/listing/active-work';
    readonly queryName: string = 'Planner.Work.Listing.WorkItem.ActiveWork';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: WorkItem[] = [];
    private readonly _sortBy: ActiveWorkSortBy;
    private static readonly _sortBy: ActiveWorkSortByWithoutQuery = new ActiveWorkSortByWithoutQuery();

    constructor() {
        super(WorkItem, true);
        this._sortBy = new ActiveWorkSortBy(this);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];


    get sortBy(): ActiveWorkSortBy {
        return this._sortBy;
    }

    static get sortBy(): ActiveWorkSortByWithoutQuery {
        return this._sortBy;
    }

    static use(sorting?: Sorting): [QueryResultWithState<WorkItem[]>, SetSorting] {
        return useObservableQuery<WorkItem[], ActiveWork>(ActiveWork, undefined, sorting);
    }

    static useWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<WorkItem[]>, SetSorting, SetPage, SetPageSize] {
        return useObservableQueryWithPaging<WorkItem[], ActiveWork>(ActiveWork, new Paging(0, pageSize), undefined, sorting);
    }

    static useSuspense(sorting?: Sorting): [QueryResultWithState<WorkItem[]>, SetSorting] {
        return useSuspenseObservableQuery<WorkItem[], ActiveWork>(ActiveWork, undefined, sorting);
    }

    static useSuspenseWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<WorkItem[]>, SetSorting, SetPage, SetPageSize] {
        return useSuspenseObservableQueryWithPaging<WorkItem[], ActiveWork>(ActiveWork, new Paging(0, pageSize), undefined, sorting);
    }

    static useChangeStream(getKey?: (item: WorkItem) => unknown, sorting?: Sorting): ChangeSet<WorkItem> {
        return useChangeStream<WorkItem, ActiveWork>(ActiveWork, undefined, getKey, sorting);
    }

    static when(condition: boolean): ObservableQueryWhen<ActiveWork, WorkItem[]> {
        return new ObservableQueryWhen<ActiveWork, WorkItem[]>(ActiveWork, condition);
    }
}

/**
 * Read model for the units of agent work - scheduled, running and finished.
 */
export class WorkItem {

    /**
     * The work identity.
     */
    @field(Guid)
    id!: Guid;

    /**
     * What the work is for.
     */
    @field(Number)
    purpose!: WorkPurpose;

    /**
     * The identities of the issues the work covers.
     */
    @field(String, true)
    issues!: string[];

    /**
     * The model the work was scheduled with - {@link NotSet} when the scheduler decides.
     */
    @field(String)
    model!: string;

    /**
     * The login of the user that scheduled the work - {@link NotSet} for automation.
     */
    @field(String)
    requestedBy!: string;

    /**
     * The lifecycle status.
     */
    @field(Number)
    status!: WorkStatus;

    /**
     * The Claude account the work runs on - `null` until dispatched.
     */
    @field(Guid)
    account?: Guid;

    /**
     * When the work started running - `null` until dispatched.
     */
    @field(Date)
    startedAt?: Date;

    /**
     * The summary the worker reported - `null` until completed.
     */
    @field(String)
    summary?: string;

    /**
     * The investigation findings - `null` unless investigation work completed.
     */
    @field(String)
    findings?: string;

    /**
     * The failure reason - `null` unless the work failed.
     */
    @field(String)
    reason?: string;

    /**
     * The input tokens the session consumed - `null` until reported.
     */
    @field(Number)
    inputTokens?: number;

    /**
     * The output tokens the session produced - `null` until reported.
     */
    @field(Number)
    outputTokens?: number;

    /**
     * The cost of the session in USD - `null` until reported.
     */
    @field(Number)
    cost?: number;

    /**
     * How long the session ran, in milliseconds - `null` until reported.
     */
    @field(Number)
    durationMs?: number;

    /**
     * The repositories ad-hoc work covers - `null` for issue work.
     */
    @field(String, true)
    repositories?: string[];

    /**
     * The free-form prompt of ad-hoc work - `null` for issue work.
     */
    @field(String)
    prompt?: string;

    /**
     * The alert the work investigates - `null` for every other purpose.
     */
    @field(String)
    alert?: string;
}
