// @generated by Cratis. Source: Planner.Issues.Registration.RegisterIssue. Time: 2026-08-08T21:11:05.5434570Z. Hash: E3C4E79E9526E375F99808FF031374370F442385B0EA64D3C96AF1588D68B04D
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command, CommandValidator } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { AuthorAssociation } from '../../Common/AuthorAssociation';

/**
 * Command for registering an issue from GitHub in the Planner - the event-sourced mirror of the issue, executed by the webhook receiver and the daily consolidation.
 */
export interface IRegisterIssue {
    
    /**
     * The author's association with the repository.
     */
    authorAssociation?: AuthorAssociation;
    
    /**
     * The markdown body of the issue - optional.
     */
    body?: string;
    
    /**
     * When the issue was created on GitHub.
     */
    createdAt?: Date;
    
    /**
     * The login of the user that created the issue.
     */
    createdBy?: string;
    
    /**
     * Whether the issue is open on GitHub.
     */
    isOpen?: boolean;
    
    /**
     * The labels on the issue - optional.
     */
    labels?: string[];
    
    /**
     * The issue number.
     */
    number?: number;
    
    /**
     * The organization owning the repository the issue lives in.
     */
    owner?: string;
    
    /**
     * The repository the issue lives in.
     */
    repository?: string;
    
    /**
     * The issue title.
     */
    title?: string;
    
    /**
     * The issue type as classified on GitHub.
     */
    type?: string;
}

export class RegisterIssueValidator extends CommandValidator<IRegisterIssue> {
    constructor() {
        super();
        this.ruleFor(c => c.number).greaterThan(0).withMessage('An issue number is required');
        this.ruleFor(c => c.owner).notEmpty().withMessage('An owner is required');
        this.ruleFor(c => c.repository).notEmpty().withMessage('A repository is required');
    }
}

/**
 * Command for registering an issue from GitHub in the Planner - the event-sourced mirror of the issue, executed by the webhook receiver and the daily consolidation.
 */
export class RegisterIssue extends Command<IRegisterIssue, string> implements IRegisterIssue {
    readonly route: string = '/api/issues/registration';
    readonly validation: CommandValidator = new RegisterIssueValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('authorAssociation', Number, false),
        new PropertyDescriptor('body', String, true),
        new PropertyDescriptor('createdAt', Date, false),
        new PropertyDescriptor('createdBy', String, false),
        new PropertyDescriptor('isOpen', Boolean, false),
        new PropertyDescriptor('labels', String, true),
        new PropertyDescriptor('number', Number, false),
        new PropertyDescriptor('owner', String, false),
        new PropertyDescriptor('repository', String, false),
        new PropertyDescriptor('title', String, false),
        new PropertyDescriptor('type', String, false),
    ];

    private _authorAssociation!: AuthorAssociation;
    private _body!: string;
    private _createdAt!: Date;
    private _createdBy!: string;
    private _isOpen!: boolean;
    private _labels!: string[];
    private _number!: number;
    private _owner!: string;
    private _repository!: string;
    private _title!: string;
    private _type!: string;

    constructor() {
        super(String, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The author's association with the repository.
     */
    get authorAssociation(): AuthorAssociation {
        return this._authorAssociation;
    }

    set authorAssociation(value: AuthorAssociation) {
        this._authorAssociation = value;
        this.propertyChanged('authorAssociation');
    }
    /**
     * The markdown body of the issue - optional.
     */
    get body(): string {
        return this._body;
    }

    set body(value: string) {
        this._body = value;
        this.propertyChanged('body');
    }
    /**
     * When the issue was created on GitHub.
     */
    get createdAt(): Date {
        return this._createdAt;
    }

    set createdAt(value: Date) {
        this._createdAt = value;
        this.propertyChanged('createdAt');
    }
    /**
     * The login of the user that created the issue.
     */
    get createdBy(): string {
        return this._createdBy;
    }

    set createdBy(value: string) {
        this._createdBy = value;
        this.propertyChanged('createdBy');
    }
    /**
     * Whether the issue is open on GitHub.
     */
    get isOpen(): boolean {
        return this._isOpen;
    }

    set isOpen(value: boolean) {
        this._isOpen = value;
        this.propertyChanged('isOpen');
    }
    /**
     * The labels on the issue - optional.
     */
    get labels(): string[] {
        return this._labels;
    }

    set labels(value: string[]) {
        this._labels = value;
        this.propertyChanged('labels');
    }
    /**
     * The issue number.
     */
    get number(): number {
        return this._number;
    }

    set number(value: number) {
        this._number = value;
        this.propertyChanged('number');
    }
    /**
     * The organization owning the repository the issue lives in.
     */
    get owner(): string {
        return this._owner;
    }

    set owner(value: string) {
        this._owner = value;
        this.propertyChanged('owner');
    }
    /**
     * The repository the issue lives in.
     */
    get repository(): string {
        return this._repository;
    }

    set repository(value: string) {
        this._repository = value;
        this.propertyChanged('repository');
    }
    /**
     * The issue title.
     */
    get title(): string {
        return this._title;
    }

    set title(value: string) {
        this._title = value;
        this.propertyChanged('title');
    }
    /**
     * The issue type as classified on GitHub.
     */
    get type(): string {
        return this._type;
    }

    set type(value: string) {
        this._type = value;
        this.propertyChanged('type');
    }

    static use(initialValues?: IRegisterIssue): [RegisterIssue, SetCommandValues<IRegisterIssue>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<RegisterIssue, IRegisterIssue>(RegisterIssue, initialValues);
    }
}
