// @generated by Cratis. Source: Planner.Work.SchedulingAlertInvestigation.ScheduleAlertInvestigation. Time: 2026-08-10T15:01:02.9193540Z. Hash: 490EB4FFC274AFF44996D28AAFEE7F3778636932B671C44AFF1D5858E3A04CAC
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { Guid } from '@cratis/fundamentals';

/**
 * Command for putting an agent on an alert - it looks at the running system, works out what is wrong, and either fixes it or hands back what it found. The scheduler dispatches it to a worker container as soon as an account with capacity is available, exactly like every other unit of work.
 */
export interface IScheduleAlertInvestigation {
    
    /**
     * The identity of the alert to investigate.
     */
    alert?: string;
    
    /**
     * The model to use - optional; the scheduler falls back to the configured alert model.
     */
    model?: string;
}


/**
 * Command for putting an agent on an alert - it looks at the running system, works out what is wrong, and either fixes it or hands back what it found. The scheduler dispatches it to a worker container as soon as an account with capacity is available, exactly like every other unit of work.
 */
export class ScheduleAlertInvestigation extends Command<IScheduleAlertInvestigation, Guid> implements IScheduleAlertInvestigation {
    readonly route: string = '/api/work/scheduling-alert-investigation';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('alert', String, false),
        new PropertyDescriptor('model', String, true),
    ];

    private _alert!: string;
    private _model!: string;

    constructor() {
        super(Guid, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The identity of the alert to investigate.
     */
    get alert(): string {
        return this._alert;
    }

    set alert(value: string) {
        this._alert = value;
        this.propertyChanged('alert');
    }
    /**
     * The model to use - optional; the scheduler falls back to the configured alert model.
     */
    get model(): string {
        return this._model;
    }

    set model(value: string) {
        this._model = value;
        this.propertyChanged('model');
    }

    static use(initialValues?: IScheduleAlertInvestigation): [ScheduleAlertInvestigation, SetCommandValues<IScheduleAlertInvestigation>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<ScheduleAlertInvestigation, IScheduleAlertInvestigation>(ScheduleAlertInvestigation, initialValues);
    }
}
