// @generated by Cratis. Source: Planner.Issues.Reordering.ReorderIssue, Planner.Issues.Reordering.IssueReordered. Time: 2026-08-08T17:17:47.5182270Z. Hash: 1217D6E364BE75594F438990BBA2A503432E7702C0F2ECBC60B578E78501A551
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { field } from '@cratis/fundamentals';

/**
 * Command for placing an issue at a new position in the manually sorted issue list.
 */
export interface IReorderIssue {
    
    /**
     * The identity of the issue.
     */
    issue?: string;
    
    /**
     * The new sort position - fractional values place an issue between two others.
     */
    order?: number;
}


/**
 * Command for placing an issue at a new position in the manually sorted issue list.
 */
export class ReorderIssue extends Command<IReorderIssue, IssueReordered> implements IReorderIssue {
    readonly route: string = '/api/issues/reordering';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('issue', String, false),
        new PropertyDescriptor('order', Number, false),
    ];

    private _issue!: string;
    private _order!: number;

    constructor() {
        super(IssueReordered, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The identity of the issue.
     */
    get issue(): string {
        return this._issue;
    }

    set issue(value: string) {
        this._issue = value;
        this.propertyChanged('issue');
    }
    /**
     * The new sort position - fractional values place an issue between two others.
     */
    get order(): number {
        return this._order;
    }

    set order(value: number) {
        this._order = value;
        this.propertyChanged('order');
    }

    static use(initialValues?: IReorderIssue): [ReorderIssue, SetCommandValues<IReorderIssue>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<ReorderIssue, IReorderIssue>(ReorderIssue, initialValues);
    }
}

/**
 * Event raised when an issue has been placed at a new position in the manually sorted issue list.
 */
export class IssueReordered {

    /**
     * The sort position.
     */
    @field(Number)
    order!: number;
}
