// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

import { existsSync, lstatSync, mkdirSync, readFileSync, readlinkSync, readdirSync, rmSync, symlinkSync, unlinkSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { checkOpenCodeAgents, generateOpenCodeAgents, generatedAgentMarkerPrefix, openCodeAgentsDirectory } from './opencode-agents.ts';

type Link = { path: string; target: string; type: 'file' | 'dir' };

const check = process.argv.includes('--check');
const rootArgument = process.argv.slice(2).find(argument => !argument.startsWith('-'));
const root = resolve(rootArgument ?? join(import.meta.dirname, '..', '..'));
const corpus = join(root, '.cratis', 'ai');
if (!existsSync(corpus)) throw new Error(`No canonical corpus exists at ${corpus}.`);

// OpenCode cannot consume the canonical agent shape through a symlink (see opencode-agents.ts), so its
// adapters are generated into the corpus before the link plan runs, and verified in --check mode.
if (check) {
    const stale = checkOpenCodeAgents(corpus);
    if (stale.length > 0) throw new Error(`OpenCode agent adapters are out of date:\n${stale.join('\n')}`);
} else {
    const generated = generateOpenCodeAgents(corpus);
    const directory = join(corpus, openCodeAgentsDirectory);
    mkdirSync(directory, { recursive: true });
    const expected = new Set(generated.map(file => file.path.split('/').pop()));
    for (const name of readdirSync(directory)) {
        if (expected.has(name)) continue;
        // Only a file this generator wrote is ours to remove; anything else in the directory is refused.
        const path = join(directory, name);
        if (!isGeneratedAgent(path)) throw new Error(`${openCodeAgentsDirectory}/${name} was not generated by this setup; remove or move it yourself.`);
        unlinkSync(path);
    }
    for (const file of generated) writeFileSync(join(corpus, file.path), file.content);
}

function isGeneratedAgent(path: string): boolean {
    try {
        return readFileSync(path, 'utf8').includes(generatedAgentMarkerPrefix);
    } catch {
        return false;
    }
}

const links = new Map<string, Link>();
function add(path: string, target: string, type: Link['type']): void {
    const existing = links.get(path);
    if (existing && (existing.target !== target || existing.type !== type)) throw new Error(`Conflicting integration plan for ${path}.`);
    links.set(path, { path, target, type });
}
function commands(directory: string): void {
    for (const prompt of readdirSync(join(corpus, 'prompts')).filter(name => name.endsWith('.prompt.md')).sort()) {
        add(`${directory}/${prompt.slice(0, -'.prompt.md'.length)}.md`, `../../.cratis/ai/prompts/${prompt}`, 'file');
    }
}
function agents(directory: string, suffix = '.md'): void {
    for (const agent of readdirSync(join(corpus, 'agents')).filter(name => name.endsWith('.md')).sort()) {
        add(`${directory}/${agent.slice(0, -3)}${suffix}`, `../../.cratis/ai/agents/${agent}`, 'file');
    }
}

add('AGENTS.md', '.cratis/ai/rules/general.md', 'file');
add('CLAUDE.md', '.cratis/ai/rules/general.md', 'file');
add('.agents/skills', '../.cratis/ai/skills', 'dir');
add('.claude/CLAUDE.md', '../.cratis/ai/rules/general.md', 'file');
add('.claude/agents', '../.cratis/ai/agents', 'dir');
add('.claude/hooks', '../.cratis/ai/hooks', 'dir');
add('.claude/prompts', '../.cratis/ai/prompts', 'dir');
add('.claude/rules', '../.cratis/ai/rules', 'dir');
add('.claude/skills', '../.cratis/ai/skills', 'dir');
commands('.claude/commands');
add('.github/copilot-instructions.md', '../.cratis/ai/rules/general.md', 'file');
add('.github/instructions', '../.cratis/ai/rules', 'dir');
add('.github/prompts', '../.cratis/ai/prompts', 'dir');
add('.github/skills', '../.cratis/ai/skills', 'dir');
agents('.github/agents', '.agent.md');
add('.pi/agents', '../.cratis/ai/agents', 'dir');
add('.pi/extensions', '../.cratis/ai/harnesses/pi/extensions', 'dir');
add('.pi/skills', '../.cratis/ai/skills', 'dir');
commands('.pi/prompts');
add('.cursor/agents', '../.cratis/ai/agents', 'dir');
add('.cursor/rules', '../.cratis/ai/harnesses/cursor/rules', 'dir');
add('.cursor/skills', '../.cratis/ai/skills', 'dir');
commands('.cursor/commands');
add('.opencode/agents', `../.cratis/ai/${openCodeAgentsDirectory}`, 'dir');
add('.opencode/skills', '../.cratis/ai/skills', 'dir');
commands('.opencode/commands');

const failures: string[] = [];
for (const link of links.values()) {
    const path = join(root, link.path);
    let actual: string | undefined;
    try {
        actual = lstatSync(path).isSymbolicLink() ? readlinkSync(path) : undefined;
    } catch {
        actual = undefined;
    }
    if (actual === link.target) continue;
    if (check) {
        failures.push(`${link.path}: expected symbolic link to ${link.target}`);
        continue;
    }
    rmSync(path, { recursive: true, force: true });
    mkdirSync(dirname(path), { recursive: true });
    symlinkSync(link.target, path, link.type === 'dir' ? 'dir' : 'file');
}

if (failures.length > 0) throw new Error(`Harness setup is out of date:\n${failures.join('\n')}`);
console.log(`${check ? 'Verified' : 'Configured'} ${links.size} harness integrations.`);
