// @generated by Cratis. Source: Planner.Work.Completing.CompleteWork, Planner.Work.Completing.WorkCompleted. Time: 2026-08-08T17:46:50.8954840Z. Hash: C41A2DF43ACE4F7F7406DEC546C293466841AB1EF9A4211A32EE3B1D3BE581DA
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command, CommandValidator } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { Guid, field } from '@cratis/fundamentals';

/**
 * Command for recording that a unit of implementation work completed - executed when the worker container reports back.
 */
export interface ICompleteWork {
    
    /**
     * The pull request the work produced - optional; not all work ends in one.
     */
    pullRequest?: number;
    
    /**
     * The organization owning the repository the pull request was opened in.
     */
    pullRequestOwner?: string;
    
    /**
     * The repository the pull request was opened in.
     */
    pullRequestRepository?: string;
    
    /**
     * The html URL of the pull request.
     */
    pullRequestUrl?: string;
    
    /**
     * The summary the worker reported.
     */
    summary?: string;
    
    /**
     * The identity of the work.
     */
    work?: Guid;
}

export class CompleteWorkValidator extends CommandValidator<ICompleteWork> {
    constructor() {
        super();
        this.ruleFor(c => c.pullRequest).greaterThan(0).withMessage('A pull request number is required');
    }
}

/**
 * Command for recording that a unit of implementation work completed - executed when the worker container reports back.
 */
export class CompleteWork extends Command<ICompleteWork, WorkCompleted> implements ICompleteWork {
    readonly route: string = '/api/work/completing';
    readonly validation: CommandValidator = new CompleteWorkValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('pullRequest', Number, true),
        new PropertyDescriptor('pullRequestOwner', String, true),
        new PropertyDescriptor('pullRequestRepository', String, true),
        new PropertyDescriptor('pullRequestUrl', String, true),
        new PropertyDescriptor('summary', String, false),
        new PropertyDescriptor('work', Guid, false),
    ];

    private _pullRequest!: number;
    private _pullRequestOwner!: string;
    private _pullRequestRepository!: string;
    private _pullRequestUrl!: string;
    private _summary!: string;
    private _work!: Guid;

    constructor() {
        super(WorkCompleted, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The pull request the work produced - optional; not all work ends in one.
     */
    get pullRequest(): number {
        return this._pullRequest;
    }

    set pullRequest(value: number) {
        this._pullRequest = value;
        this.propertyChanged('pullRequest');
    }
    /**
     * The organization owning the repository the pull request was opened in.
     */
    get pullRequestOwner(): string {
        return this._pullRequestOwner;
    }

    set pullRequestOwner(value: string) {
        this._pullRequestOwner = value;
        this.propertyChanged('pullRequestOwner');
    }
    /**
     * The repository the pull request was opened in.
     */
    get pullRequestRepository(): string {
        return this._pullRequestRepository;
    }

    set pullRequestRepository(value: string) {
        this._pullRequestRepository = value;
        this.propertyChanged('pullRequestRepository');
    }
    /**
     * The html URL of the pull request.
     */
    get pullRequestUrl(): string {
        return this._pullRequestUrl;
    }

    set pullRequestUrl(value: string) {
        this._pullRequestUrl = value;
        this.propertyChanged('pullRequestUrl');
    }
    /**
     * The summary the worker reported.
     */
    get summary(): string {
        return this._summary;
    }

    set summary(value: string) {
        this._summary = value;
        this.propertyChanged('summary');
    }
    /**
     * The identity of the work.
     */
    get work(): Guid {
        return this._work;
    }

    set work(value: Guid) {
        this._work = value;
        this.propertyChanged('work');
    }

    static use(initialValues?: ICompleteWork): [CompleteWork, SetCommandValues<ICompleteWork>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<CompleteWork, ICompleteWork>(CompleteWork, initialValues);
    }
}

/**
 * Event raised when a unit of implementation work completed. When the work produced a pull request, its coordinates travel on the event so the covered issues can be marked for review.
 */
export class WorkCompleted {

    /**
     * The summary the worker reported.
     */
    @field(String)
    summary!: string;

    /**
     * The pull request number - {@link NotSet} when none was produced.
     */
    @field(Number)
    pullRequest!: number;

    /**
     * The html URL of the pull request.
     */
    @field(String)
    pullRequestUrl!: string;

    /**
     * The organization owning the repository the pull request was opened in.
     */
    @field(String)
    pullRequestOwner!: string;

    /**
     * The repository the pull request was opened in.
     */
    @field(String)
    pullRequestRepository!: string;
}
