// @generated by Cratis. Source: Planner.Work.Completing.CompleteWork, Planner.Work.Completing.WorkCompleted. Time: 2026-08-12T07:08:37.6375883Z. Hash: 0F29172E1AA0C665DA6BE2A4DDF134B283F8FEE56B3F3B8A04BACC4CE06F0923
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command, CommandValidator } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { Guid, field } from '@cratis/fundamentals';

/**
 * Command for recording that a unit of implementation work completed - executed when the worker container reports back.
 */
export interface ICompleteWork {
    
    /**
     * The cost of the session in USD as the Claude CLI reported it - optional.
     */
    cost?: number;
    
    /**
     * How long the session ran, in milliseconds - optional.
     */
    durationMs?: number;
    
    /**
     * The input tokens the session consumed - optional.
     */
    inputTokens?: number;
    
    /**
     * The output tokens the session produced - optional.
     */
    outputTokens?: number;
    
    /**
     * The pull request the work produced - optional; not all work ends in one.
     */
    pullRequest?: number;
    
    /**
     * The organization owning the repository the pull request was opened in.
     */
    pullRequestOwner?: string;
    
    /**
     * The repository the pull request was opened in.
     */
    pullRequestRepository?: string;
    
    /**
     * The html URL of the pull request.
     */
    pullRequestUrl?: string;
    
    /**
     * The summary the worker reported.
     */
    summary?: string;
    
    /**
     * The identity of the work.
     */
    work?: Guid;
}

export class CompleteWorkValidator extends CommandValidator<ICompleteWork> {
    constructor() {
        super();
        this.ruleFor(c => c.pullRequest).greaterThan(0).withMessage('A pull request number is required');
    }
}

/**
 * Command for recording that a unit of implementation work completed - executed when the worker container reports back.
 */
export class CompleteWork extends Command<ICompleteWork, WorkCompleted> implements ICompleteWork {
    readonly route: string = '/api/work/completing';
    readonly validation: CommandValidator = new CompleteWorkValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('cost', Number, true),
        new PropertyDescriptor('durationMs', Number, false),
        new PropertyDescriptor('inputTokens', Number, true),
        new PropertyDescriptor('outputTokens', Number, true),
        new PropertyDescriptor('pullRequest', Number, true),
        new PropertyDescriptor('pullRequestOwner', String, true),
        new PropertyDescriptor('pullRequestRepository', String, true),
        new PropertyDescriptor('pullRequestUrl', String, true),
        new PropertyDescriptor('summary', String, false),
        new PropertyDescriptor('work', Guid, false),
    ];

    private _cost?: number;
    private _durationMs!: number;
    private _inputTokens?: number;
    private _outputTokens?: number;
    private _pullRequest?: number;
    private _pullRequestOwner?: string;
    private _pullRequestRepository?: string;
    private _pullRequestUrl?: string;
    private _summary!: string;
    private _work!: Guid;

    constructor() {
        super(WorkCompleted, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The cost of the session in USD as the Claude CLI reported it - optional.
     */
    get cost(): number | undefined {
        return this._cost;
    }

    set cost(value: number | undefined) {
        this._cost = value;
        this.propertyChanged('cost');
    }
    /**
     * How long the session ran, in milliseconds - optional.
     */
    get durationMs(): number {
        return this._durationMs;
    }

    set durationMs(value: number) {
        this._durationMs = value;
        this.propertyChanged('durationMs');
    }
    /**
     * The input tokens the session consumed - optional.
     */
    get inputTokens(): number | undefined {
        return this._inputTokens;
    }

    set inputTokens(value: number | undefined) {
        this._inputTokens = value;
        this.propertyChanged('inputTokens');
    }
    /**
     * The output tokens the session produced - optional.
     */
    get outputTokens(): number | undefined {
        return this._outputTokens;
    }

    set outputTokens(value: number | undefined) {
        this._outputTokens = value;
        this.propertyChanged('outputTokens');
    }
    /**
     * The pull request the work produced - optional; not all work ends in one.
     */
    get pullRequest(): number | undefined {
        return this._pullRequest;
    }

    set pullRequest(value: number | undefined) {
        this._pullRequest = value;
        this.propertyChanged('pullRequest');
    }
    /**
     * The organization owning the repository the pull request was opened in.
     */
    get pullRequestOwner(): string | undefined {
        return this._pullRequestOwner;
    }

    set pullRequestOwner(value: string | undefined) {
        this._pullRequestOwner = value;
        this.propertyChanged('pullRequestOwner');
    }
    /**
     * The repository the pull request was opened in.
     */
    get pullRequestRepository(): string | undefined {
        return this._pullRequestRepository;
    }

    set pullRequestRepository(value: string | undefined) {
        this._pullRequestRepository = value;
        this.propertyChanged('pullRequestRepository');
    }
    /**
     * The html URL of the pull request.
     */
    get pullRequestUrl(): string | undefined {
        return this._pullRequestUrl;
    }

    set pullRequestUrl(value: string | undefined) {
        this._pullRequestUrl = value;
        this.propertyChanged('pullRequestUrl');
    }
    /**
     * The summary the worker reported.
     */
    get summary(): string {
        return this._summary;
    }

    set summary(value: string) {
        this._summary = value;
        this.propertyChanged('summary');
    }
    /**
     * The identity of the work.
     */
    get work(): Guid {
        return this._work;
    }

    set work(value: Guid) {
        this._work = value;
        this.propertyChanged('work');
    }

    static use(initialValues?: ICompleteWork): [CompleteWork, SetCommandValues<ICompleteWork>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<CompleteWork, ICompleteWork>(CompleteWork, initialValues);
    }
}

/**
 * Event raised when a unit of implementation work completed. When the work produced a pull request, its coordinates travel on the event so the covered issues can be marked for review; the session's usage travels along for the account usage statistics.
 */
export class WorkCompleted {

    /**
     * The summary the worker reported.
     */
    @field(String)
    summary!: string;

    /**
     * The pull request number - {@link NotSet} when none was produced.
     */
    @field(Number)
    pullRequest!: number;

    /**
     * The html URL of the pull request.
     */
    @field(String)
    pullRequestUrl!: string;

    /**
     * The organization owning the repository the pull request was opened in.
     */
    @field(String)
    pullRequestOwner!: string;

    /**
     * The repository the pull request was opened in.
     */
    @field(String)
    pullRequestRepository!: string;

    /**
     * The input tokens the session consumed.
     */
    @field(Number)
    inputTokens!: number;

    /**
     * The output tokens the session produced.
     */
    @field(Number)
    outputTokens!: number;

    /**
     * The cost of the session in USD as the Claude CLI reported it.
     */
    @field(Number)
    cost!: number;

    /**
     * How long the session ran, in milliseconds.
     */
    @field(Number)
    durationMs!: number;
}
