// @generated by Cratis. Source: Planner.Issues.ChangingMilestone.ChangeIssueMilestone, Planner.Issues.ChangingMilestone.IssueMilestoneChanged. Time: 2026-08-19T12:35:46.4721490Z. Hash: 5F8F8399F9C37A61E9E577D3D86D8FC5BB3A4E4738C40B5BF9CA4B262E3F7423
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { field } from '@cratis/fundamentals';

/**
 * Command for changing the milestone of an issue - mirroring milestoning on GitHub. Every issue webhook delivery carries the current milestone (or none), regardless of which action triggered it, so this is applied unconditionally rather than only on `milestoned`/`demilestoned`.
 */
export interface IChangeIssueMilestone {
    
    /**
     * The identity of the issue.
     */
    issue?: string;
    
    /**
     * The milestone the issue is now attached to, or {@link NotSet} for none.
     */
    milestone?: string;
}


/**
 * Command for changing the milestone of an issue - mirroring milestoning on GitHub. Every issue webhook delivery carries the current milestone (or none), regardless of which action triggered it, so this is applied unconditionally rather than only on `milestoned`/`demilestoned`.
 */
export class ChangeIssueMilestone extends Command<IChangeIssueMilestone, IssueMilestoneChanged> implements IChangeIssueMilestone {
    readonly route: string = '/api/issues/changing-milestone';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('issue', String, false),
        new PropertyDescriptor('milestone', String, false),
    ];

    private _issue!: string;
    private _milestone!: string;

    constructor() {
        super(IssueMilestoneChanged, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The identity of the issue.
     */
    get issue(): string {
        return this._issue;
    }

    set issue(value: string) {
        this._issue = value;
        this.propertyChanged('issue');
    }
    /**
     * The milestone the issue is now attached to, or {@link NotSet} for none.
     */
    get milestone(): string {
        return this._milestone;
    }

    set milestone(value: string) {
        this._milestone = value;
        this.propertyChanged('milestone');
    }

    static use(initialValues?: IChangeIssueMilestone): [ChangeIssueMilestone, SetCommandValues<IChangeIssueMilestone>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<ChangeIssueMilestone, IChangeIssueMilestone>(ChangeIssueMilestone, initialValues);
    }
}

/**
 * Event raised when the milestone of an issue has changed on GitHub.
 */
export class IssueMilestoneChanged {

    /**
     * The milestone the issue is now attached to, or {@link NotSet} for none.
     */
    @field(String)
    milestone!: string;
}
