// @generated by Cratis. Source: Planner.Work.Stopping.StopWork, Planner.Work.Stopping.WorkStopped. Time: 2026-08-08T21:11:05.5434570Z. Hash: E939D2193BB1AEFBE6472D00083BA26232785DEF3C48BAFA29C1E1A47EE91BB3
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { Guid } from '@cratis/fundamentals';

/**
 * Command for stopping a unit of work - kills the worker container when one is running and takes scheduled work out of the queue.
 */
export interface IStopWork {
    
    /**
     * The identity of the work to stop.
     */
    work?: Guid;
}


/**
 * Command for stopping a unit of work - kills the worker container when one is running and takes scheduled work out of the queue.
 */
export class StopWork extends Command<IStopWork, WorkStopped> implements IStopWork {
    readonly route: string = '/api/work/stopping';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('work', Guid, false),
    ];

    private _work!: Guid;

    constructor() {
        super(WorkStopped, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The identity of the work to stop.
     */
    get work(): Guid {
        return this._work;
    }

    set work(value: Guid) {
        this._work = value;
        this.propertyChanged('work');
    }

    static use(initialValues?: IStopWork): [StopWork, SetCommandValues<IStopWork>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<StopWork, IStopWork>(StopWork, initialValues);
    }
}

/**
 * Event raised when a unit of work has been stopped deliberately - the covered issues fall back to no status so a human decides what happens next.
 */
export class WorkStopped {
}
