// @generated by Cratis. Source: Planner.Alerts.AlertStatus. Time: 2026-08-10T15:01:02.9193540Z. Hash: B0A48BF649F123CCED14702576C38E8FC0CA4B0CBCCB822FD9A439A649CF32E5
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

// eslint-disable-next-line header/header
/**
 * Where an alert stands in its lifecycle.
 */
export enum AlertStatus {
    none = 0,
    received = 1,
    investigating = 2,
    needsAttention = 3,
    investigationFailed = 4,
    resolved = 5,
}
