// @generated by Cratis. Source: Planner.Alerts.AlertInvestigationOutcome. Time: 2026-08-10T15:01:02.9193540Z. Hash: 9C74DE224ACE99036B9B462D3A793A8D85B1AA92FC23FD658BD0E9DC0FBF2350
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

// eslint-disable-next-line header/header
/**
 * What an agent concluded after investigating an alert.
 */
export enum AlertInvestigationOutcome {
    needsAttention = 0,
    resolved = 1,
}
