// @generated by Cratis. Source: Planner.PullRequests.Closing.ClosePullRequest, Planner.PullRequests.Closing.PullRequestClosed. Time: 2026-08-09T09:18:49.3333770Z. Hash: 8842A4DF889F6E20B61D21E7013C3B6F6C860BBF7A959AD55250E4FFC8B60F64
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { field } from '@cratis/fundamentals';

/**
 * Command for closing a pull request mirrored from GitHub - executed by the webhook receiver when one is closed, whether merged or abandoned.
 */
export interface IClosePullRequest {
    
    /**
     * Whether the pull request was merged rather than simply closed.
     */
    merged?: boolean;
    
    /**
     * The identity of the pull request.
     */
    pullRequest?: string;
}


/**
 * Command for closing a pull request mirrored from GitHub - executed by the webhook receiver when one is closed, whether merged or abandoned.
 */
export class ClosePullRequest extends Command<IClosePullRequest, PullRequestClosed> implements IClosePullRequest {
    readonly route: string = '/api/pull-requests/closing';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('merged', Boolean, false),
        new PropertyDescriptor('pullRequest', String, false),
    ];

    private _merged!: boolean;
    private _pullRequest!: string;

    constructor() {
        super(PullRequestClosed, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * Whether the pull request was merged rather than simply closed.
     */
    get merged(): boolean {
        return this._merged;
    }

    set merged(value: boolean) {
        this._merged = value;
        this.propertyChanged('merged');
    }
    /**
     * The identity of the pull request.
     */
    get pullRequest(): string {
        return this._pullRequest;
    }

    set pullRequest(value: string) {
        this._pullRequest = value;
        this.propertyChanged('pullRequest');
    }

    static use(initialValues?: IClosePullRequest): [ClosePullRequest, SetCommandValues<IClosePullRequest>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<ClosePullRequest, IClosePullRequest>(ClosePullRequest, initialValues);
    }
}

/**
 * Event raised when a pull request mirrored from GitHub has been closed.
 */
export class PullRequestClosed {

    /**
     * Whether the pull request was merged rather than simply closed.
     */
    @field(Boolean)
    merged!: boolean;
}
