// @generated by Cratis. Source: Planner.Issues.ChangingStatus.ChangeIssueStatus. Time: 2026-08-08T17:17:47.5182270Z. Hash: 3E91B143AA8D3C3DA0AB1467BDCFCA93F88E6B4E2E52C9BD0E98675EB6A740D2
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { IssueStatus } from '../IssueStatus';

/**
 * Command for changing the Planner's internal status of an issue. One command serves the UI and the orchestration; the log records a precise fact per transition.
 */
export interface IChangeIssueStatus {
    
    /**
     * The identity of the issue.
     */
    issue?: string;
    
    /**
     * The status to change to.
     */
    status?: IssueStatus;
}


/**
 * Command for changing the Planner's internal status of an issue. One command serves the UI and the orchestration; the log records a precise fact per transition.
 */
export class ChangeIssueStatus extends Command<IChangeIssueStatus, Record<string, unknown>> implements IChangeIssueStatus {
    readonly route: string = '/api/issues/changing-status';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('issue', String, false),
        new PropertyDescriptor('status', Number, false),
    ];

    private _issue!: string;
    private _status!: IssueStatus;

    constructor() {
        super(Object, true);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The identity of the issue.
     */
    get issue(): string {
        return this._issue;
    }

    set issue(value: string) {
        this._issue = value;
        this.propertyChanged('issue');
    }
    /**
     * The status to change to.
     */
    get status(): IssueStatus {
        return this._status;
    }

    set status(value: IssueStatus) {
        this._status = value;
        this.propertyChanged('status');
    }

    static use(initialValues?: IChangeIssueStatus): [ChangeIssueStatus, SetCommandValues<IChangeIssueStatus>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<ChangeIssueStatus, IChangeIssueStatus>(ChangeIssueStatus, initialValues);
    }
}
