// @generated by Cratis. Source: Planner.Work.Scheduling.ScheduleWork. Time: 2026-08-08T17:35:38.1733570Z. Hash: 9A55251616CC083C8C96C8755F7B4EEABDCB9E19CA0C8AACCB516FF2CF494335
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command, CommandValidator } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { WorkPurpose } from '../WorkPurpose';
import { Guid } from '@cratis/fundamentals';

/**
 * Command for scheduling a unit of agent work covering one or more issues - either an investigation or an implementation. The scheduler dispatches it to a worker container as soon as an account with capacity is available.
 */
export interface IScheduleWork {
    
    /**
     * The identities of the issues the work covers.
     */
    issues?: string[];
    
    /**
     * The model to use - optional; the scheduler falls back to the issue's suggested model or the configured default.
     */
    model?: string;
    
    /**
     * What the work is for.
     */
    purpose?: WorkPurpose;
}

export class ScheduleWorkValidator extends CommandValidator<IScheduleWork> {
    constructor() {
        super();
        this.ruleFor(c => c.issues).notEmpty().withMessage('Work needs at least one issue');
    }
}

/**
 * Command for scheduling a unit of agent work covering one or more issues - either an investigation or an implementation. The scheduler dispatches it to a worker container as soon as an account with capacity is available.
 */
export class ScheduleWork extends Command<IScheduleWork, Guid> implements IScheduleWork {
    readonly route: string = '/api/work/scheduling';
    readonly validation: CommandValidator = new ScheduleWorkValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('issues', String, false),
        new PropertyDescriptor('model', String, true),
        new PropertyDescriptor('purpose', Number, false),
    ];

    private _issues!: string[];
    private _model!: string;
    private _purpose!: WorkPurpose;

    constructor() {
        super(Guid, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The identities of the issues the work covers.
     */
    get issues(): string[] {
        return this._issues;
    }

    set issues(value: string[]) {
        this._issues = value;
        this.propertyChanged('issues');
    }
    /**
     * The model to use - optional; the scheduler falls back to the issue's suggested model or the configured default.
     */
    get model(): string {
        return this._model;
    }

    set model(value: string) {
        this._model = value;
        this.propertyChanged('model');
    }
    /**
     * What the work is for.
     */
    get purpose(): WorkPurpose {
        return this._purpose;
    }

    set purpose(value: WorkPurpose) {
        this._purpose = value;
        this.propertyChanged('purpose');
    }

    static use(initialValues?: IScheduleWork): [ScheduleWork, SetCommandValues<IScheduleWork>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<ScheduleWork, IScheduleWork>(ScheduleWork, initialValues);
    }
}
