// @generated by Cratis. Source: Planner.Builds.RecordingDiagnosis.RecordBuildDiagnosis, Planner.Builds.RecordingDiagnosis.BuildDiagnosisRecorded. Time: 2026-08-19T16:05:40.3285460Z. Hash: 97CCA5EF482842D0EAFD4301ACB4E60346A53D3D4AE7B2BC955200EAF15F5227
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { field } from '@cratis/fundamentals';

/**
 * Command for recording what the language model made of a newly failing build - executed by the build failure analysis reactor.
 */
export interface IRecordBuildDiagnosis {
    
    /**
     * What the language model thinks is wrong.
     */
    diagnosis?: string;
    
    /**
     * Whether the language model judged an agent could plausibly fix it.
     */
    fixable?: boolean;
    
    /**
     * The identity of the workflow.
     */
    workflow?: string;
}


/**
 * Command for recording what the language model made of a newly failing build - executed by the build failure analysis reactor.
 */
export class RecordBuildDiagnosis extends Command<IRecordBuildDiagnosis, BuildDiagnosisRecorded> implements IRecordBuildDiagnosis {
    readonly route: string = '/api/builds/recording-diagnosis';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('diagnosis', String, false),
        new PropertyDescriptor('fixable', Boolean, false),
        new PropertyDescriptor('workflow', String, false),
    ];

    private _diagnosis!: string;
    private _fixable!: boolean;
    private _workflow!: string;

    constructor() {
        super(BuildDiagnosisRecorded, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * What the language model thinks is wrong.
     */
    get diagnosis(): string {
        return this._diagnosis;
    }

    set diagnosis(value: string) {
        this._diagnosis = value;
        this.propertyChanged('diagnosis');
    }
    /**
     * Whether the language model judged an agent could plausibly fix it.
     */
    get fixable(): boolean {
        return this._fixable;
    }

    set fixable(value: boolean) {
        this._fixable = value;
        this.propertyChanged('fixable');
    }
    /**
     * The identity of the workflow.
     */
    get workflow(): string {
        return this._workflow;
    }

    set workflow(value: string) {
        this._workflow = value;
        this.propertyChanged('workflow');
    }

    static use(initialValues?: IRecordBuildDiagnosis): [RecordBuildDiagnosis, SetCommandValues<IRecordBuildDiagnosis>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<RecordBuildDiagnosis, IRecordBuildDiagnosis>(RecordBuildDiagnosis, initialValues);
    }
}

/**
 * Event raised when the language model has diagnosed a newly failing build.
 */
export class BuildDiagnosisRecorded {

    /**
     * What the language model thinks is wrong.
     */
    @field(String)
    diagnosis!: string;

    /**
     * Whether the language model judged an agent could plausibly fix it.
     */
    @field(Boolean)
    fixable!: boolean;
}
