// @generated by Cratis. Source: Planner.GitHub.GitIdentity.Listing.ConfiguredGitIdentity, Planner.GitHub.GitIdentity.Listing.ConfiguredGitIdentity. Time: 2026-08-09T10:49:01.8295570Z. Hash: 3AA0804761A03465442D304207C18FC521E502273F86227ECBF9D84F40150FB5
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { ObservableQueryFor, QueryResultWithState, Sorting, Paging, ChangeSet } from '@cratis/arc/queries';
import { useObservableQuery, useObservableQueryWithPaging, useSuspenseObservableQuery, useSuspenseObservableQueryWithPaging, useChangeStream, SetSorting, SetPage, SetPageSize, ObservableQueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { field } from '@cratis/fundamentals';

class CurrentGitIdentitySortBy {

    constructor(readonly query: CurrentGitIdentity) {
    }

}

class CurrentGitIdentitySortByWithoutQuery {

}


/**
 * Observes the configured git identity.
 */
export class CurrentGitIdentity extends ObservableQueryFor<ConfiguredGitIdentity[]> {
    readonly route: string = '/api/git-hub/git-identity/listing/current-git-identity';
    readonly queryName: string = 'Planner.GitHub.GitIdentity.Listing.ConfiguredGitIdentity.CurrentGitIdentity';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: ConfiguredGitIdentity[] = [];
    private readonly _sortBy: CurrentGitIdentitySortBy;
    private static readonly _sortBy: CurrentGitIdentitySortByWithoutQuery = new CurrentGitIdentitySortByWithoutQuery();

    constructor() {
        super(ConfiguredGitIdentity, true);
        this._sortBy = new CurrentGitIdentitySortBy(this);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];


    get sortBy(): CurrentGitIdentitySortBy {
        return this._sortBy;
    }

    static get sortBy(): CurrentGitIdentitySortByWithoutQuery {
        return this._sortBy;
    }

    static use(sorting?: Sorting): [QueryResultWithState<ConfiguredGitIdentity[]>, SetSorting] {
        return useObservableQuery<ConfiguredGitIdentity[], CurrentGitIdentity>(CurrentGitIdentity, undefined, sorting);
    }

    static useWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<ConfiguredGitIdentity[]>, SetSorting, SetPage, SetPageSize] {
        return useObservableQueryWithPaging<ConfiguredGitIdentity[], CurrentGitIdentity>(CurrentGitIdentity, new Paging(0, pageSize), undefined, sorting);
    }

    static useSuspense(sorting?: Sorting): [QueryResultWithState<ConfiguredGitIdentity[]>, SetSorting] {
        return useSuspenseObservableQuery<ConfiguredGitIdentity[], CurrentGitIdentity>(CurrentGitIdentity, undefined, sorting);
    }

    static useSuspenseWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<ConfiguredGitIdentity[]>, SetSorting, SetPage, SetPageSize] {
        return useSuspenseObservableQueryWithPaging<ConfiguredGitIdentity[], CurrentGitIdentity>(CurrentGitIdentity, new Paging(0, pageSize), undefined, sorting);
    }

    static useChangeStream(getKey?: (item: ConfiguredGitIdentity) => unknown, sorting?: Sorting): ChangeSet<ConfiguredGitIdentity> {
        return useChangeStream<ConfiguredGitIdentity, CurrentGitIdentity>(CurrentGitIdentity, undefined, getKey, sorting);
    }

    static when(condition: boolean): ObservableQueryWhen<CurrentGitIdentity, ConfiguredGitIdentity[]> {
        return new ObservableQueryWhen<CurrentGitIdentity, ConfiguredGitIdentity[]>(CurrentGitIdentity, condition);
    }
}

/**
 * Read model for the git identity worker containers commit as. There is exactly one per deployment - the frontend and the work dispatcher both take the first (and only) item.
 */
export class ConfiguredGitIdentity {

    /**
     * The fixed git identity id.
     */
    @field(String)
    id!: string;

    /**
     * The `git config user.name` to commit as.
     */
    @field(String)
    name!: string;

    /**
     * The `git config user.email` to commit as.
     */
    @field(String)
    email!: string;
}
