// @generated by Cratis. Source: Planner.Alerts.AutoConvertingToIssue.AutoConvertAlertToIssue. Time: 2026-08-19T13:04:27.8735060Z. Hash: 5BC42ADB4521DBABC1A07F700B75C45E0921988562090D0BA6844603B5D39018
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command, CommandValidator } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { AlertConvertedToIssue } from '../ConvertingToIssue/ConvertingToIssue';

/**
 * Command for turning an alert an agent could not resolve into a GitHub issue automatically, in the deployment's configured operational repository - which is not necessarily one the Planner tracks (an infrastructure repository, say), so unlike {@link ConvertAlertToIssue} this writes straight to GitHub instead of requiring a tracked repository.
 */
export interface IAutoConvertAlertToIssue {
    
    /**
     * The identity of the alert.
     */
    alert?: string;
    
    /**
     * The markdown body - the alert's own detail and what the agent found.
     */
    body?: string;
    
    /**
     * The organization owning the repository to create the issue in.
     */
    owner?: string;
    
    /**
     * The repository to create the issue in.
     */
    repository?: string;
    
    /**
     * The issue title.
     */
    title?: string;
}

export class AutoConvertAlertToIssueValidator extends CommandValidator<IAutoConvertAlertToIssue> {
    constructor() {
        super();
        this.ruleFor(c => c.owner).notEmpty().withMessage('An owner is required');
        this.ruleFor(c => c.repository).notEmpty().withMessage('A repository is required');
    }
}

/**
 * Command for turning an alert an agent could not resolve into a GitHub issue automatically, in the deployment's configured operational repository - which is not necessarily one the Planner tracks (an infrastructure repository, say), so unlike {@link ConvertAlertToIssue} this writes straight to GitHub instead of requiring a tracked repository.
 */
export class AutoConvertAlertToIssue extends Command<IAutoConvertAlertToIssue, AlertConvertedToIssue> implements IAutoConvertAlertToIssue {
    readonly route: string = '/api/alerts/auto-converting-to-issue';
    readonly validation: CommandValidator = new AutoConvertAlertToIssueValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('alert', String, false),
        new PropertyDescriptor('body', String, false),
        new PropertyDescriptor('owner', String, false),
        new PropertyDescriptor('repository', String, false),
        new PropertyDescriptor('title', String, false),
    ];

    private _alert!: string;
    private _body!: string;
    private _owner!: string;
    private _repository!: string;
    private _title!: string;

    constructor() {
        super(AlertConvertedToIssue, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The identity of the alert.
     */
    get alert(): string {
        return this._alert;
    }

    set alert(value: string) {
        this._alert = value;
        this.propertyChanged('alert');
    }
    /**
     * The markdown body - the alert's own detail and what the agent found.
     */
    get body(): string {
        return this._body;
    }

    set body(value: string) {
        this._body = value;
        this.propertyChanged('body');
    }
    /**
     * The organization owning the repository to create the issue in.
     */
    get owner(): string {
        return this._owner;
    }

    set owner(value: string) {
        this._owner = value;
        this.propertyChanged('owner');
    }
    /**
     * The repository to create the issue in.
     */
    get repository(): string {
        return this._repository;
    }

    set repository(value: string) {
        this._repository = value;
        this.propertyChanged('repository');
    }
    /**
     * The issue title.
     */
    get title(): string {
        return this._title;
    }

    set title(value: string) {
        this._title = value;
        this.propertyChanged('title');
    }

    static use(initialValues?: IAutoConvertAlertToIssue): [AutoConvertAlertToIssue, SetCommandValues<IAutoConvertAlertToIssue>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<AutoConvertAlertToIssue, IAutoConvertAlertToIssue>(AutoConvertAlertToIssue, initialValues);
    }
}
