// @generated by Cratis. Source: Planner.Issues.Comments.Recording.RecordIssueComment, Planner.Issues.Comments.Recording.IssueCommentAdded. Time: 2026-08-08T21:11:05.5434570Z. Hash: 83A9D5C1488730B22FCA9BC634908CA00CD66ED2B5CCD4D91B3FE02D4E3B410D
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { field } from '@cratis/fundamentals';

/**
 * Command for recording a comment on an issue - mirroring a comment created on GitHub.
 */
export interface IRecordIssueComment {
    
    /**
     * The login of the user that wrote the comment.
     */
    author?: string;
    
    /**
     * The markdown body of the comment.
     */
    body?: string;
    
    /**
     * The identity of the comment on GitHub.
     */
    comment?: number;
    
    /**
     * When the comment was written on GitHub.
     */
    commentedAt?: Date;
    
    /**
     * The identity of the issue.
     */
    issue?: string;
}


/**
 * Command for recording a comment on an issue - mirroring a comment created on GitHub.
 */
export class RecordIssueComment extends Command<IRecordIssueComment, IssueCommentAdded> implements IRecordIssueComment {
    readonly route: string = '/api/issues/comments/recording';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('author', String, false),
        new PropertyDescriptor('body', String, false),
        new PropertyDescriptor('comment', Number, false),
        new PropertyDescriptor('commentedAt', Date, false),
        new PropertyDescriptor('issue', String, false),
    ];

    private _author!: string;
    private _body!: string;
    private _comment!: number;
    private _commentedAt!: Date;
    private _issue!: string;

    constructor() {
        super(IssueCommentAdded, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The login of the user that wrote the comment.
     */
    get author(): string {
        return this._author;
    }

    set author(value: string) {
        this._author = value;
        this.propertyChanged('author');
    }
    /**
     * The markdown body of the comment.
     */
    get body(): string {
        return this._body;
    }

    set body(value: string) {
        this._body = value;
        this.propertyChanged('body');
    }
    /**
     * The identity of the comment on GitHub.
     */
    get comment(): number {
        return this._comment;
    }

    set comment(value: number) {
        this._comment = value;
        this.propertyChanged('comment');
    }
    /**
     * When the comment was written on GitHub.
     */
    get commentedAt(): Date {
        return this._commentedAt;
    }

    set commentedAt(value: Date) {
        this._commentedAt = value;
        this.propertyChanged('commentedAt');
    }
    /**
     * The identity of the issue.
     */
    get issue(): string {
        return this._issue;
    }

    set issue(value: string) {
        this._issue = value;
        this.propertyChanged('issue');
    }

    static use(initialValues?: IRecordIssueComment): [RecordIssueComment, SetCommandValues<IRecordIssueComment>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<RecordIssueComment, IRecordIssueComment>(RecordIssueComment, initialValues);
    }
}

/**
 * Event raised when a comment has been added to an issue on GitHub.
 */
export class IssueCommentAdded {

    /**
     * The identity of the comment on GitHub.
     */
    @field(Number)
    comment!: number;

    /**
     * The login of the user that wrote the comment.
     */
    @field(String)
    author!: string;

    /**
     * The markdown body of the comment.
     */
    @field(String)
    body!: string;

    /**
     * When the comment was written on GitHub.
     */
    @field(Date)
    commentedAt!: Date;
}
