// @generated by Cratis. Source: Planner.Accounts.Registering.RegisterAccount. Time: 2026-08-12T07:08:37.6375883Z. Hash: ED2BE1E1323DD1CBA020DBF59894034153EBE0AD2DC807B22D30988C0476EAC1
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command, CommandValidator } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { EventForEventSourceId } from '../../Chronicle/EventSequences/EventForEventSourceId';
import { ClaudePlan } from '../ClaudePlan';

/**
 * Command for registering a Claude account the Planner can schedule work on. Work runs through the regular Claude plan (not the API): a worker container gets the account's token and runs the Claude CLI with it. The account is associated with the user registering it - work that user schedules prefers their own account(s).
 */
export interface IRegisterAccount {
    
    /**
     * The display name of the account.
     */
    name?: string;
    
    /**
     * The subscription plan of the account.
     */
    plan?: ClaudePlan;
    
    /**
     * The Claude CLI token - optional; it can be set later.
     */
    token?: string;
}

export class RegisterAccountValidator extends CommandValidator<IRegisterAccount> {
    constructor() {
        super();
        this.ruleFor(c => c.name).notEmpty().withMessage('An account name is required');
    }
}

/**
 * Command for registering a Claude account the Planner can schedule work on. Work runs through the regular Claude plan (not the API): a worker container gets the account's token and runs the Claude CLI with it. The account is associated with the user registering it - work that user schedules prefers their own account(s).
 */
export class RegisterAccount extends Command<IRegisterAccount, EventForEventSourceId> implements IRegisterAccount {
    readonly route: string = '/api/accounts/registering';
    readonly validation: CommandValidator = new RegisterAccountValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('name', String, false),
        new PropertyDescriptor('plan', Number, false),
        new PropertyDescriptor('token', String, true),
    ];

    private _name!: string;
    private _plan!: ClaudePlan;
    private _token?: string;

    constructor() {
        super(EventForEventSourceId, true);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The display name of the account.
     */
    get name(): string {
        return this._name;
    }

    set name(value: string) {
        this._name = value;
        this.propertyChanged('name');
    }
    /**
     * The subscription plan of the account.
     */
    get plan(): ClaudePlan {
        return this._plan;
    }

    set plan(value: ClaudePlan) {
        this._plan = value;
        this.propertyChanged('plan');
    }
    /**
     * The Claude CLI token - optional; it can be set later.
     */
    get token(): string | undefined {
        return this._token;
    }

    set token(value: string | undefined) {
        this._token = value;
        this.propertyChanged('token');
    }

    static use(initialValues?: IRegisterAccount): [RegisterAccount, SetCommandValues<IRegisterAccount>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<RegisterAccount, IRegisterAccount>(RegisterAccount, initialValues);
    }
}
