// @generated by Cratis. Source: Planner.WeeklyDigests.WeeklyDigestStatus. Time: 2026-08-19T16:16:25.3642610Z. Hash: 2FCA11BD9CE2C1E3307C4C3B65AB9E9746B0DFA8809E9E6695DFD89F3C87A795
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

// eslint-disable-next-line header/header
/**
 * Where a weekly digest entry stands in its lifecycle.
 */
export enum WeeklyDigestStatus {
    received = 0,
    unpublished = 1,
    published = 2,
}
