// @generated by Cratis. Source: Planner.Work.WorkStatus. Time: 2026-08-08T21:11:05.5434570Z. Hash: A8874D6B23E53532ABF121C5FF93C3E9963169AD4E89DB7DEA83AE02300C6518
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

// eslint-disable-next-line header/header
/**
 * The lifecycle status of a unit of agent work.
 */
export enum WorkStatus {
    scheduled = 0,
    running = 1,
    completed = 2,
    failed = 3,
    stopped = 4,
}
