// @generated by Cratis. Source: Planner.Work.WorkStatus. Time: 2026-08-08T17:35:38.1733570Z. Hash: 9D235E2CCB2282840A150A1D5D5BB0A1D34BE57DF9D9A6F93DA260EBA03A9024
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

// eslint-disable-next-line header/header
/**
 * The lifecycle status of a unit of agent work.
 */
export enum WorkStatus {
    scheduled = 0,
    running = 1,
    completed = 2,
    failed = 3,
}
