// @generated by Cratis. Source: Planner.Work.WorkPurpose. Time: 2026-08-08T17:35:38.1733570Z. Hash: 5589646739B3449A1FE5C76A97DF48AD68A740A39CC36A741E26DDDA9182DF3E
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

// eslint-disable-next-line header/header
/**
 * What a unit of agent work is for.
 */
export enum WorkPurpose {
    investigation = 0,
    implementation = 1,
}
