// @generated by Cratis. Source: Planner.Work.WorkPurpose. Time: 2026-08-08T21:11:05.5434570Z. Hash: B92FE3304075FB584031C15EFA6F9122095219AA88BCB98F52EBB9D27FC61CDC
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

// eslint-disable-next-line header/header
/**
 * What a unit of agent work is for.
 */
export enum WorkPurpose {
    investigation = 0,
    implementation = 1,
    adHoc = 2,
}
