// @generated by Cratis. Source: Planner.Work.WorkPurpose. Time: 2026-08-10T15:01:02.9193540Z. Hash: 275C55C883B8E37E3725877BCEC6316880D84D2F17ECD0D183B890DD700D5560
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

// eslint-disable-next-line header/header
/**
 * What a unit of agent work is for.
 */
export enum WorkPurpose {
    investigation = 0,
    implementation = 1,
    adHoc = 2,
    alertInvestigation = 3,
}
