// @generated by Cratis. Source: Planner.Alerts.Raising.RaiseAlert. Time: 2026-08-10T15:01:02.9193540Z. Hash: F22A8FD9CF171E2DE3A6E4CC11ED39A4F0AAE8F0820D88266B36E8ABE76D3A8E
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { AlertSeverity } from '../AlertSeverity';

/**
 * Command for reporting that something is wrong in a running system - executed for every delivery the alert webhook accepts. A production watchdog re-reports a condition it cannot fix for as long as it lasts, so the same fingerprint arriving again is recorded as another sighting of the alert already open rather than as a new one.
 */
export interface IRaiseAlert {
    
    /**
     * The sending system's stable key for the condition.
     */
    fingerprint?: string;
    
    /**
     * How serious the sending system considers it.
     */
    severity?: AlertSeverity;
    
    /**
     * The system the alert came from.
     */
    source?: string;
    
    /**
     * What the sending system had to say about it.
     */
    summary?: string;
    
    /**
     * The one-line headline.
     */
    title?: string;
}


/**
 * Command for reporting that something is wrong in a running system - executed for every delivery the alert webhook accepts. A production watchdog re-reports a condition it cannot fix for as long as it lasts, so the same fingerprint arriving again is recorded as another sighting of the alert already open rather than as a new one.
 */
export class RaiseAlert extends Command<IRaiseAlert, Record<string, unknown>> implements IRaiseAlert {
    readonly route: string = '/api/alerts/raising';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('fingerprint', String, false),
        new PropertyDescriptor('severity', Number, false),
        new PropertyDescriptor('source', String, false),
        new PropertyDescriptor('summary', String, false),
        new PropertyDescriptor('title', String, false),
    ];

    private _fingerprint!: string;
    private _severity!: AlertSeverity;
    private _source!: string;
    private _summary!: string;
    private _title!: string;

    constructor() {
        super(Object, true);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The sending system's stable key for the condition.
     */
    get fingerprint(): string {
        return this._fingerprint;
    }

    set fingerprint(value: string) {
        this._fingerprint = value;
        this.propertyChanged('fingerprint');
    }
    /**
     * How serious the sending system considers it.
     */
    get severity(): AlertSeverity {
        return this._severity;
    }

    set severity(value: AlertSeverity) {
        this._severity = value;
        this.propertyChanged('severity');
    }
    /**
     * The system the alert came from.
     */
    get source(): string {
        return this._source;
    }

    set source(value: string) {
        this._source = value;
        this.propertyChanged('source');
    }
    /**
     * What the sending system had to say about it.
     */
    get summary(): string {
        return this._summary;
    }

    set summary(value: string) {
        this._summary = value;
        this.propertyChanged('summary');
    }
    /**
     * The one-line headline.
     */
    get title(): string {
        return this._title;
    }

    set title(value: string) {
        this._title = value;
        this.propertyChanged('title');
    }

    static use(initialValues?: IRaiseAlert): [RaiseAlert, SetCommandValues<IRaiseAlert>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<RaiseAlert, IRaiseAlert>(RaiseAlert, initialValues);
    }
}
