// @generated by Cratis. Source: Planner.Builds.BuildConclusion. Time: 2026-08-19T13:18:47.1489210Z. Hash: 15F74F15624FC472783A1F662DCCAE937C1027F8FDD960FB77A775E6D70C0B32
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

// eslint-disable-next-line header/header
/**
 * How a GitHub Actions workflow run concluded, as GitHub reports it.
 */
export enum BuildConclusion {
    unknown = 0,
    success = 1,
    failure = 2,
    cancelled = 3,
}
