// @generated by Cratis. Source: Planner.Accounts.Listing.ClaudeAccount, Planner.Accounts.Listing.ClaudeAccount. Time: 2026-08-08T17:20:55.2325870Z. Hash: 8483791D3149E6975319162EE7E91B16BD46B24DF422D3E5FB4327E38ED7C2DE
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { ObservableQueryFor, QueryResultWithState, Sorting, Paging, ChangeSet } from '@cratis/arc/queries';
import { useObservableQuery, useObservableQueryWithPaging, useSuspenseObservableQuery, useSuspenseObservableQueryWithPaging, useChangeStream, SetSorting, SetPage, SetPageSize, ObservableQueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { field, Guid } from '@cratis/fundamentals';
import { ClaudePlan } from '../ClaudePlan';

class AllAccountsSortBy {

    constructor(readonly query: AllAccounts) {
    }

}

class AllAccountsSortByWithoutQuery {

}


/**
 * Observes all Claude accounts.
 */
export class AllAccounts extends ObservableQueryFor<ClaudeAccount[]> {
    readonly route: string = '/api/accounts/listing/all-accounts';
    readonly queryName: string = 'Planner.Accounts.Listing.ClaudeAccount.AllAccounts';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: ClaudeAccount[] = [];
    private readonly _sortBy: AllAccountsSortBy;
    private static readonly _sortBy: AllAccountsSortByWithoutQuery = new AllAccountsSortByWithoutQuery();

    constructor() {
        super(ClaudeAccount, true);
        this._sortBy = new AllAccountsSortBy(this);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];


    get sortBy(): AllAccountsSortBy {
        return this._sortBy;
    }

    static get sortBy(): AllAccountsSortByWithoutQuery {
        return this._sortBy;
    }

    static use(sorting?: Sorting): [QueryResultWithState<ClaudeAccount[]>, SetSorting] {
        return useObservableQuery<ClaudeAccount[], AllAccounts>(AllAccounts, undefined, sorting);
    }

    static useWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<ClaudeAccount[]>, SetSorting, SetPage, SetPageSize] {
        return useObservableQueryWithPaging<ClaudeAccount[], AllAccounts>(AllAccounts, new Paging(0, pageSize), undefined, sorting);
    }

    static useSuspense(sorting?: Sorting): [QueryResultWithState<ClaudeAccount[]>, SetSorting] {
        return useSuspenseObservableQuery<ClaudeAccount[], AllAccounts>(AllAccounts, undefined, sorting);
    }

    static useSuspenseWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<ClaudeAccount[]>, SetSorting, SetPage, SetPageSize] {
        return useSuspenseObservableQueryWithPaging<ClaudeAccount[], AllAccounts>(AllAccounts, new Paging(0, pageSize), undefined, sorting);
    }

    static useChangeStream(getKey?: (item: ClaudeAccount) => unknown, sorting?: Sorting): ChangeSet<ClaudeAccount> {
        return useChangeStream<ClaudeAccount, AllAccounts>(AllAccounts, undefined, getKey, sorting);
    }

    static when(condition: boolean): ObservableQueryWhen<AllAccounts, ClaudeAccount[]> {
        return new ObservableQueryWhen<AllAccounts, ClaudeAccount[]>(AllAccounts, condition);
    }
}

/**
 * Read model for listing the Claude accounts. The token itself is deliberately not part of this model - only whether one has been set; the scheduler reads the token through the passive {@link AccountCredentials} model.
 */
export class ClaudeAccount {

    /**
     * The account identity.
     */
    @field(Guid)
    id!: Guid;

    /**
     * The display name of the account.
     */
    @field(String)
    name!: string;

    /**
     * The subscription plan of the account.
     */
    @field(Number)
    plan!: ClaudePlan;

    /**
     * Whether a Claude CLI token has been set for the account.
     */
    @field(Boolean)
    hasToken!: boolean;
}
