// @generated by Cratis. Source: Planner.Identity.PlannerUserDetails. Time: 2026-08-19T14:42:37.1641300Z. Hash: 33D38D0D74C1599D63B2E3EF30ECE9212327351CC5451A9614EEADC69FABF38B
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { field } from '@cratis/fundamentals';

/**
 * The details the frontend gets about the signed-in user - just the GitHub login today, which is what &quot;For me&quot; filtering, the inbox and replying as the user key off.
 */
export class PlannerUserDetails {

    /**
     * The GitHub login of the signed-in user - {@link NotSet} when nobody is signed in.
     */
    @field(String)
    login!: string;
}
