// @generated by Cratis. Source: Planner.Alerts.ConvertingToIssue.ConvertAlertToIssue, Planner.Alerts.ConvertingToIssue.AlertConvertedToIssue. Time: 2026-08-10T15:09:57.7165040Z. Hash: C0358AD4746F48C86AD17BD316E31C6F441F6765AA02578089BD6378C47C7DE1
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { field } from '@cratis/fundamentals';

/**
 * Command for turning an alert into a GitHub issue - the move for a condition that is not going to be fixed by an agent poking at production, but by someone changing the code. The alert keeps its own life on the board; the issue is where the work happens.
 */
export interface IConvertAlertToIssue {
    
    /**
     * The identity of the alert.
     */
    alert?: string;
    
    /**
     * The markdown body - the alert's own detail, what the agent found, and anything the user added.
     */
    body?: string;
    
    /**
     * The tracked repository to create the issue in.
     */
    repository?: string;
    
    /**
     * The issue title.
     */
    title?: string;
}


/**
 * Command for turning an alert into a GitHub issue - the move for a condition that is not going to be fixed by an agent poking at production, but by someone changing the code. The alert keeps its own life on the board; the issue is where the work happens.
 */
export class ConvertAlertToIssue extends Command<IConvertAlertToIssue, AlertConvertedToIssue> implements IConvertAlertToIssue {
    readonly route: string = '/api/alerts/converting-to-issue';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('alert', String, false),
        new PropertyDescriptor('body', String, false),
        new PropertyDescriptor('repository', String, false),
        new PropertyDescriptor('title', String, false),
    ];

    private _alert!: string;
    private _body!: string;
    private _repository!: string;
    private _title!: string;

    constructor() {
        super(AlertConvertedToIssue, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The identity of the alert.
     */
    get alert(): string {
        return this._alert;
    }

    set alert(value: string) {
        this._alert = value;
        this.propertyChanged('alert');
    }
    /**
     * The markdown body - the alert's own detail, what the agent found, and anything the user added.
     */
    get body(): string {
        return this._body;
    }

    set body(value: string) {
        this._body = value;
        this.propertyChanged('body');
    }
    /**
     * The tracked repository to create the issue in.
     */
    get repository(): string {
        return this._repository;
    }

    set repository(value: string) {
        this._repository = value;
        this.propertyChanged('repository');
    }
    /**
     * The issue title.
     */
    get title(): string {
        return this._title;
    }

    set title(value: string) {
        this._title = value;
        this.propertyChanged('title');
    }

    static use(initialValues?: IConvertAlertToIssue): [ConvertAlertToIssue, SetCommandValues<IConvertAlertToIssue>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<ConvertAlertToIssue, IConvertAlertToIssue>(ConvertAlertToIssue, initialValues);
    }
}

/**
 * Event raised when an alert has been turned into a GitHub issue.
 */
export class AlertConvertedToIssue {

    /**
     * The number GitHub assigned the issue.
     */
    @field(Number)
    number!: number;

    /**
     * The html URL of the issue.
     */
    @field(String)
    url!: string;

    /**
     * The organization owning the repository the issue was created in.
     */
    @field(String)
    owner!: string;

    /**
     * The repository the issue was created in.
     */
    @field(String)
    repository!: string;
}
