// @generated by Cratis. Source: Planner.Roadmap.Listing.Vision, Planner.Roadmap.Listing.Vision. Time: 2026-08-19T16:54:42.5460010Z. Hash: A173DEB513535226DD0054C0C76B73EBA088BCFAEF0365CDE373373B5F39BBFB
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { QueryFor, QueryResultWithState } from '@cratis/arc/queries';
import { useQuery, useSuspenseQuery, PerformQuery, SetSorting, QueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { field } from '@cratis/fundamentals';

/**
 * Gets the current vision - a default-initialized instance (empty {@link Content}) until one has been set.
 */
export class Current extends QueryFor<Vision> {
    readonly route: string = '/api/roadmap/listing/current';
    readonly queryName: string = 'Planner.Roadmap.Listing.Vision.Current';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: Vision = {} as any;

    constructor() {
        super(Vision, false);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];



    static use(): [QueryResultWithState<Vision>, PerformQuery, SetSorting] {
        return useQuery<Vision, Current>(Current);
    }

    static useSuspense(): [QueryResultWithState<Vision>, PerformQuery, SetSorting] {
        return useSuspenseQuery<Vision, Current>(Current);
    }

    static when(condition: boolean): QueryWhen<Current, Vision> {
        return new QueryWhen<Current, Vision>(Current, condition);
    }
}

/**
 * Read model for the Planner's vision document.
 */
export class Vision {

    /**
     * The vision identity - always {@link Default}.
     */
    @field(String)
    id!: string;

    /**
     * The markdown content of the vision.
     */
    @field(String)
    content!: string;

    /**
     * When the vision was last set.
     */
    @field(Date)
    updatedAt?: Date;
}
