// @generated by Cratis. Source: Planner.Roadmap.Listing.Plan, Planner.Roadmap.Listing.Plan. Time: 2026-08-19T16:55:58.0712010Z. Hash: 07823F7F78BC1C574D4AC96C20015B9C6A7FBB2CAF5160CCCA1DD45487091FAA
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { ObservableQueryFor, QueryResultWithState, Sorting, Paging, ChangeSet } from '@cratis/arc/queries';
import { useObservableQuery, useObservableQueryWithPaging, useSuspenseObservableQuery, useSuspenseObservableQueryWithPaging, useChangeStream, SetSorting, SetPage, SetPageSize, ObservableQueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { field, Guid } from '@cratis/fundamentals';
import { PlanStatus } from '../PlanStatus';

class AllPlansSortBy {

    constructor(readonly query: AllPlans) {
    }

}

class AllPlansSortByWithoutQuery {

}


/**
 * Observes every plan.
 */
export class AllPlans extends ObservableQueryFor<Plan[]> {
    readonly route: string = '/api/roadmap/listing/all-plans';
    readonly queryName: string = 'Planner.Roadmap.Listing.Plan.AllPlans';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: Plan[] = [];
    private readonly _sortBy: AllPlansSortBy;
    private static readonly _sortBy: AllPlansSortByWithoutQuery = new AllPlansSortByWithoutQuery();

    constructor() {
        super(Plan, true);
        this._sortBy = new AllPlansSortBy(this);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];


    get sortBy(): AllPlansSortBy {
        return this._sortBy;
    }

    static get sortBy(): AllPlansSortByWithoutQuery {
        return this._sortBy;
    }

    static use(sorting?: Sorting): [QueryResultWithState<Plan[]>, SetSorting] {
        return useObservableQuery<Plan[], AllPlans>(AllPlans, undefined, sorting);
    }

    static useWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<Plan[]>, SetSorting, SetPage, SetPageSize] {
        return useObservableQueryWithPaging<Plan[], AllPlans>(AllPlans, new Paging(0, pageSize), undefined, sorting);
    }

    static useSuspense(sorting?: Sorting): [QueryResultWithState<Plan[]>, SetSorting] {
        return useSuspenseObservableQuery<Plan[], AllPlans>(AllPlans, undefined, sorting);
    }

    static useSuspenseWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<Plan[]>, SetSorting, SetPage, SetPageSize] {
        return useSuspenseObservableQueryWithPaging<Plan[], AllPlans>(AllPlans, new Paging(0, pageSize), undefined, sorting);
    }

    static useChangeStream(getKey?: (item: Plan) => unknown, sorting?: Sorting): ChangeSet<Plan> {
        return useChangeStream<Plan, AllPlans>(AllPlans, undefined, getKey, sorting);
    }

    static when(condition: boolean): ObservableQueryWhen<AllPlans, Plan[]> {
        return new ObservableQueryWhen<AllPlans, Plan[]>(AllPlans, condition);
    }
}

/**
 * Read model for a plan covering a set of selected issues.
 */
export class Plan {

    /**
     * The plan identity.
     */
    @field(Guid)
    id!: Guid;

    /**
     * The identities of the issues the plan covers.
     */
    @field(String, true)
    issues!: string[];

    /**
     * Extra instructions the plan was requested with.
     */
    @field(String)
    instructions!: string;

    /**
     * The login of the user that requested the plan.
     */
    @field(String)
    requestedBy!: string;

    /**
     * When the plan was requested.
     */
    @field(Date)
    requestedAt?: Date;

    /**
     * Where the plan stands.
     */
    @field(Number)
    status!: PlanStatus;

    /**
     * The markdown content of the plan - empty until generated.
     */
    @field(String)
    content?: string;

    /**
     * Why generation failed - empty unless {@link Status} is {@link Failed}.
     */
    @field(String)
    failureReason!: string;
}
