// @generated by Cratis. Source: Planner.Accounts.ClaudePlan. Time: 2026-08-08T17:20:55.2325870Z. Hash: F24B499A8DA6E73EF37E39551A490B3996826C0159D9276AF0F71DF08082C594
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

// eslint-disable-next-line header/header
/**
 * The Claude subscription plan of an account - determines the usage boundaries the scheduler respects (sessions per five-hour window and per week, per model).
 */
export enum ClaudePlan {
    pro = 0,
    max5x = 1,
    max20x = 2,
}
