// @generated by Cratis. Source: Planner.Issues.ChangingBody.ChangeIssueBody, Planner.Issues.ChangingBody.IssueBodyChanged. Time: 2026-08-08T21:11:05.5434570Z. Hash: 503B37C78F40B0A8D6C0AA398E741FABC817413E7747E7F8B7B47E3D2F26EE82
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { field } from '@cratis/fundamentals';

/**
 * Command for changing the body of an issue - mirroring a body edit on GitHub.
 */
export interface IChangeIssueBody {
    
    /**
     * The new markdown body.
     */
    body?: string;
    
    /**
     * The identity of the issue.
     */
    issue?: string;
}


/**
 * Command for changing the body of an issue - mirroring a body edit on GitHub.
 */
export class ChangeIssueBody extends Command<IChangeIssueBody, IssueBodyChanged> implements IChangeIssueBody {
    readonly route: string = '/api/issues/changing-body';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('body', String, false),
        new PropertyDescriptor('issue', String, false),
    ];

    private _body!: string;
    private _issue!: string;

    constructor() {
        super(IssueBodyChanged, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The new markdown body.
     */
    get body(): string {
        return this._body;
    }

    set body(value: string) {
        this._body = value;
        this.propertyChanged('body');
    }
    /**
     * The identity of the issue.
     */
    get issue(): string {
        return this._issue;
    }

    set issue(value: string) {
        this._issue = value;
        this.propertyChanged('issue');
    }

    static use(initialValues?: IChangeIssueBody): [ChangeIssueBody, SetCommandValues<IChangeIssueBody>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<ChangeIssueBody, IChangeIssueBody>(ChangeIssueBody, initialValues);
    }
}

/**
 * Event raised when an issue's body has changed on GitHub.
 */
export class IssueBodyChanged {

    /**
     * The new markdown body.
     */
    @field(String)
    body!: string;
}
