// @generated by Cratis. Source: Planner.Work.SchedulingAdHoc.ScheduleAdHocWork. Time: 2026-08-08T21:11:05.5434570Z. Hash: C60D3018DEC5C9D7666228B557926503E294DE539369DDDCBD6E8FDACE89A764
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command, CommandValidator } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { Guid } from '@cratis/fundamentals';

/**
 * Command for scheduling ad-hoc agent work - a free-form prompt over one or more repositories, a whole organization, or a repository group (the frontend expands a group to its repositories).
 */
export interface IScheduleAdHocWork {
    
    /**
     * The model to use - optional; falls back to the configured default.
     */
    model?: string;
    
    /**
     * Work with every tracked repository of this organization - optional.
     */
    organization?: string;
    
    /**
     * The instructions for the agent.
     */
    prompt?: string;
    
    /**
     * The identities of the repositories to work with - optional when an organization is given.
     */
    repositories?: string[];
}

export class ScheduleAdHocWorkValidator extends CommandValidator<IScheduleAdHocWork> {
    constructor() {
        super();
        this.ruleFor(c => c.prompt).notEmpty().withMessage('A prompt is required');
    }
}

/**
 * Command for scheduling ad-hoc agent work - a free-form prompt over one or more repositories, a whole organization, or a repository group (the frontend expands a group to its repositories).
 */
export class ScheduleAdHocWork extends Command<IScheduleAdHocWork, Guid> implements IScheduleAdHocWork {
    readonly route: string = '/api/work/scheduling-ad-hoc';
    readonly validation: CommandValidator = new ScheduleAdHocWorkValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('model', String, true),
        new PropertyDescriptor('organization', String, true),
        new PropertyDescriptor('prompt', String, false),
        new PropertyDescriptor('repositories', String, true),
    ];

    private _model!: string;
    private _organization!: string;
    private _prompt!: string;
    private _repositories!: string[];

    constructor() {
        super(Guid, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The model to use - optional; falls back to the configured default.
     */
    get model(): string {
        return this._model;
    }

    set model(value: string) {
        this._model = value;
        this.propertyChanged('model');
    }
    /**
     * Work with every tracked repository of this organization - optional.
     */
    get organization(): string {
        return this._organization;
    }

    set organization(value: string) {
        this._organization = value;
        this.propertyChanged('organization');
    }
    /**
     * The instructions for the agent.
     */
    get prompt(): string {
        return this._prompt;
    }

    set prompt(value: string) {
        this._prompt = value;
        this.propertyChanged('prompt');
    }
    /**
     * The identities of the repositories to work with - optional when an organization is given.
     */
    get repositories(): string[] {
        return this._repositories;
    }

    set repositories(value: string[]) {
        this._repositories = value;
        this.propertyChanged('repositories');
    }

    static use(initialValues?: IScheduleAdHocWork): [ScheduleAdHocWork, SetCommandValues<IScheduleAdHocWork>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<ScheduleAdHocWork, IScheduleAdHocWork>(ScheduleAdHocWork, initialValues);
    }
}
