// @generated by Cratis. Source: Planner.Work.CompletingInvestigation.CompleteInvestigation, Planner.Work.CompletingInvestigation.InvestigationCompleted. Time: 2026-08-08T17:35:38.1733570Z. Hash: C1E23B27C077DFE3CACCB27520ECACD0644A9D71A1321325AAB4871996042989
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command, CommandValidator } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { Guid, field } from '@cratis/fundamentals';

/**
 * Command for recording that a unit of investigation work completed - executed when the worker container reports back with its findings.
 */
export interface ICompleteInvestigation {
    
    /**
     * The markdown findings of the investigation - the plan for how the issues can be implemented or fixed.
     */
    findings?: string;
    
    /**
     * The model the investigation suggests for implementing the issues.
     */
    suggestedModel?: string;
    
    /**
     * The identity of the work.
     */
    work?: Guid;
}

export class CompleteInvestigationValidator extends CommandValidator<ICompleteInvestigation> {
    constructor() {
        super();
        this.ruleFor(c => c.findings).notEmpty().withMessage('Investigation findings are required');
    }
}

/**
 * Command for recording that a unit of investigation work completed - executed when the worker container reports back with its findings.
 */
export class CompleteInvestigation extends Command<ICompleteInvestigation, InvestigationCompleted> implements ICompleteInvestigation {
    readonly route: string = '/api/work/completing-investigation';
    readonly validation: CommandValidator = new CompleteInvestigationValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('findings', String, false),
        new PropertyDescriptor('suggestedModel', String, false),
        new PropertyDescriptor('work', Guid, false),
    ];

    private _findings!: string;
    private _suggestedModel!: string;
    private _work!: Guid;

    constructor() {
        super(InvestigationCompleted, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The markdown findings of the investigation - the plan for how the issues can be implemented or fixed.
     */
    get findings(): string {
        return this._findings;
    }

    set findings(value: string) {
        this._findings = value;
        this.propertyChanged('findings');
    }
    /**
     * The model the investigation suggests for implementing the issues.
     */
    get suggestedModel(): string {
        return this._suggestedModel;
    }

    set suggestedModel(value: string) {
        this._suggestedModel = value;
        this.propertyChanged('suggestedModel');
    }
    /**
     * The identity of the work.
     */
    get work(): Guid {
        return this._work;
    }

    set work(value: Guid) {
        this._work = value;
        this.propertyChanged('work');
    }

    static use(initialValues?: ICompleteInvestigation): [CompleteInvestigation, SetCommandValues<ICompleteInvestigation>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<CompleteInvestigation, ICompleteInvestigation>(CompleteInvestigation, initialValues);
    }
}

/**
 * Event raised when a unit of investigation work completed - the findings flow onto the covered issues and are reported back to the original GitHub issues as comments.
 */
export class InvestigationCompleted {

    /**
     * The markdown findings of the investigation.
     */
    @field(String)
    findings!: string;

    /**
     * The model the investigation suggests for implementing the issues.
     */
    @field(String)
    suggestedModel!: string;
}
