// @generated by Cratis. Source: Planner.Work.CompletingInvestigation.CompleteInvestigation, Planner.Work.CompletingInvestigation.InvestigationCompleted. Time: 2026-08-12T07:08:37.6375883Z. Hash: 0BE52C45AA6B746C5E33DB7A4A50EE96C2288361B15F4ACF22CBC357DBEDD927
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command, CommandValidator } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { Guid, field } from '@cratis/fundamentals';

/**
 * Command for recording that a unit of investigation work completed - executed when the worker container reports back with its findings.
 */
export interface ICompleteInvestigation {
    
    /**
     * The cost of the session in USD as the Claude CLI reported it - optional.
     */
    cost?: number;
    
    /**
     * How long the session ran, in milliseconds - optional.
     */
    durationMs?: number;
    
    /**
     * The markdown findings of the investigation - the plan for how the issues can be implemented or fixed.
     */
    findings?: string;
    
    /**
     * The input tokens the session consumed - optional.
     */
    inputTokens?: number;
    
    /**
     * The output tokens the session produced - optional.
     */
    outputTokens?: number;
    
    /**
     * The model the investigation suggests for implementing the issues.
     */
    suggestedModel?: string;
    
    /**
     * The identity of the work.
     */
    work?: Guid;
}

export class CompleteInvestigationValidator extends CommandValidator<ICompleteInvestigation> {
    constructor() {
        super();
        this.ruleFor(c => c.findings).notEmpty().withMessage('Investigation findings are required');
    }
}

/**
 * Command for recording that a unit of investigation work completed - executed when the worker container reports back with its findings.
 */
export class CompleteInvestigation extends Command<ICompleteInvestigation, InvestigationCompleted> implements ICompleteInvestigation {
    readonly route: string = '/api/work/completing-investigation';
    readonly validation: CommandValidator = new CompleteInvestigationValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('cost', Number, true),
        new PropertyDescriptor('durationMs', Number, false),
        new PropertyDescriptor('findings', String, false),
        new PropertyDescriptor('inputTokens', Number, true),
        new PropertyDescriptor('outputTokens', Number, true),
        new PropertyDescriptor('suggestedModel', String, false),
        new PropertyDescriptor('work', Guid, false),
    ];

    private _cost?: number;
    private _durationMs!: number;
    private _findings!: string;
    private _inputTokens?: number;
    private _outputTokens?: number;
    private _suggestedModel!: string;
    private _work!: Guid;

    constructor() {
        super(InvestigationCompleted, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The cost of the session in USD as the Claude CLI reported it - optional.
     */
    get cost(): number | undefined {
        return this._cost;
    }

    set cost(value: number | undefined) {
        this._cost = value;
        this.propertyChanged('cost');
    }
    /**
     * How long the session ran, in milliseconds - optional.
     */
    get durationMs(): number {
        return this._durationMs;
    }

    set durationMs(value: number) {
        this._durationMs = value;
        this.propertyChanged('durationMs');
    }
    /**
     * The markdown findings of the investigation - the plan for how the issues can be implemented or fixed.
     */
    get findings(): string {
        return this._findings;
    }

    set findings(value: string) {
        this._findings = value;
        this.propertyChanged('findings');
    }
    /**
     * The input tokens the session consumed - optional.
     */
    get inputTokens(): number | undefined {
        return this._inputTokens;
    }

    set inputTokens(value: number | undefined) {
        this._inputTokens = value;
        this.propertyChanged('inputTokens');
    }
    /**
     * The output tokens the session produced - optional.
     */
    get outputTokens(): number | undefined {
        return this._outputTokens;
    }

    set outputTokens(value: number | undefined) {
        this._outputTokens = value;
        this.propertyChanged('outputTokens');
    }
    /**
     * The model the investigation suggests for implementing the issues.
     */
    get suggestedModel(): string {
        return this._suggestedModel;
    }

    set suggestedModel(value: string) {
        this._suggestedModel = value;
        this.propertyChanged('suggestedModel');
    }
    /**
     * The identity of the work.
     */
    get work(): Guid {
        return this._work;
    }

    set work(value: Guid) {
        this._work = value;
        this.propertyChanged('work');
    }

    static use(initialValues?: ICompleteInvestigation): [CompleteInvestigation, SetCommandValues<ICompleteInvestigation>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<CompleteInvestigation, ICompleteInvestigation>(CompleteInvestigation, initialValues);
    }
}

/**
 * Event raised when a unit of investigation work completed - the findings flow onto the covered issues and are reported back to the original GitHub issues as comments; the session's usage travels along for the account usage statistics.
 */
export class InvestigationCompleted {

    /**
     * The markdown findings of the investigation.
     */
    @field(String)
    findings!: string;

    /**
     * The model the investigation suggests for implementing the issues.
     */
    @field(String)
    suggestedModel!: string;

    /**
     * The input tokens the session consumed.
     */
    @field(Number)
    inputTokens!: number;

    /**
     * The output tokens the session produced.
     */
    @field(Number)
    outputTokens!: number;

    /**
     * The cost of the session in USD as the Claude CLI reported it.
     */
    @field(Number)
    cost!: number;

    /**
     * How long the session ran, in milliseconds.
     */
    @field(Number)
    durationMs!: number;
}
