// @generated by Cratis. Source: Planner.WeeklyDigests.Publishing.PublishWeeklyDigest, Planner.WeeklyDigests.Publishing.WeeklyDigestPublished. Time: 2026-08-19T16:16:25.3642610Z. Hash: 70CE4C4213274FE1764CD79F895FA17A2BB58A7469FD5BDE5DADEBCBC6F754A7
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { Guid, field } from '@cratis/fundamentals';

/**
 * Command for publishing a weekly digest to whichever outlets are configured.
 */
export interface IPublishWeeklyDigest {
    
    /**
     * The identity of the weekly digest.
     */
    weeklyDigest?: Guid;
}


/**
 * Command for publishing a weekly digest to whichever outlets are configured.
 */
export class PublishWeeklyDigest extends Command<IPublishWeeklyDigest, WeeklyDigestPublished> implements IPublishWeeklyDigest {
    readonly route: string = '/api/weekly-digests/publishing';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('weeklyDigest', Guid, false),
    ];

    private _weeklyDigest!: Guid;

    constructor() {
        super(WeeklyDigestPublished, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The identity of the weekly digest.
     */
    get weeklyDigest(): Guid {
        return this._weeklyDigest;
    }

    set weeklyDigest(value: Guid) {
        this._weeklyDigest = value;
        this.propertyChanged('weeklyDigest');
    }

    static use(initialValues?: IPublishWeeklyDigest): [PublishWeeklyDigest, SetCommandValues<IPublishWeeklyDigest>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<PublishWeeklyDigest, IPublishWeeklyDigest>(PublishWeeklyDigest, initialValues);
    }
}

/**
 * Event raised when a weekly digest has been published.
 */
export class WeeklyDigestPublished {

    /**
     * The names of the outlets it was published to.
     */
    @field(String, true)
    publishedTo!: string[];
}
