// @generated by Cratis. Source: Planner.Issues.IssueFeasibility. Time: 2026-08-19T14:32:49.9784910Z. Hash: 7C501C1FB97559DBAEEC91E41308402BB4A9D535113C52D1A315BA54D4B1671B
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

// eslint-disable-next-line header/header
/**
 * Whether triage judged an issue as something an agent can act on.
 */
export enum IssueFeasibility {
    unclassified = 0,
    agentCanDo = 1,
    needsHumanDecision = 2,
    needsMoreInformation = 3,
    notActionable = 4,
    duplicate = 5,
}
