// @generated by Cratis. Source: Planner.Issues.IssueStatus. Time: 2026-08-08T17:17:47.5182270Z. Hash: 0399715E47EA11FB1AEF60BD18B798C08E6A0262EF82C3696DCC082CC3264155
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

// eslint-disable-next-line header/header
/**
 * The Planner's internal status of an issue - deliberately separate from anything GitHub tracks.
 */
export enum IssueStatus {
    none = 0,
    readyForDevelopment = 1,
    inProgress = 2,
    forReview = 3,
}
