// @generated by Cratis. Source: Planner.Repositories.SettingReviewGatePolicy.SetReviewGatePolicy, Planner.Repositories.SettingReviewGatePolicy.ReviewGatePolicySet. Time: 2026-08-19T16:43:45.5809930Z. Hash: ED8D73AA76B00C3B5EC049A842C3F240CFFE884826213E8A2AF3DA20B821D388
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { ReviewGatePolicy } from '../ReviewGatePolicy';
import { field } from '@cratis/fundamentals';

/**
 * Command for setting a repository's review gate policy - whether a pull request always waits for a person, or an agent may merge one on its own once classified as safe to.
 */
export interface ISetReviewGatePolicy {
    
    /**
     * The policy to set.
     */
    policy?: ReviewGatePolicy;
    
    /**
     * The identity of the repository.
     */
    repository?: string;
}


/**
 * Command for setting a repository's review gate policy - whether a pull request always waits for a person, or an agent may merge one on its own once classified as safe to.
 */
export class SetReviewGatePolicy extends Command<ISetReviewGatePolicy, ReviewGatePolicySet> implements ISetReviewGatePolicy {
    readonly route: string = '/api/repositories/setting-review-gate-policy';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('policy', Number, false),
        new PropertyDescriptor('repository', String, false),
    ];

    private _policy!: ReviewGatePolicy;
    private _repository!: string;

    constructor() {
        super(ReviewGatePolicySet, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The policy to set.
     */
    get policy(): ReviewGatePolicy {
        return this._policy;
    }

    set policy(value: ReviewGatePolicy) {
        this._policy = value;
        this.propertyChanged('policy');
    }
    /**
     * The identity of the repository.
     */
    get repository(): string {
        return this._repository;
    }

    set repository(value: string) {
        this._repository = value;
        this.propertyChanged('repository');
    }

    static use(initialValues?: ISetReviewGatePolicy): [SetReviewGatePolicy, SetCommandValues<ISetReviewGatePolicy>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<SetReviewGatePolicy, ISetReviewGatePolicy>(SetReviewGatePolicy, initialValues);
    }
}

/**
 * Event raised when a repository's review gate policy has been set.
 */
export class ReviewGatePolicySet {

    /**
     * The policy that was set.
     */
    @field(Number)
    policy!: ReviewGatePolicy;
}
