// @generated by Cratis. Source: Planner.GitHub.GitIdentity.Setting.SetGitIdentity, Planner.GitHub.GitIdentity.Setting.GitIdentitySet. Time: 2026-08-09T09:18:49.3333770Z. Hash: A7B78A9BA7AC96D182B5EE40297CC54A8C4A52BCA43A5386481BE536AAD3EB94
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command, CommandValidator } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { field } from '@cratis/fundamentals';

/**
 * Command for setting the git identity worker containers commit as - one setting shared across the whole Planner deployment, injected into every worker as `PLANNER_GIT_USER_NAME` / `PLANNER_GIT_USER_EMAIL`.
 */
export interface ISetGitIdentity {
    
    /**
     * The `git config user.email` to commit as.
     */
    email?: string;
    
    /**
     * The `git config user.name` to commit as.
     */
    name?: string;
}

export class SetGitIdentityValidator extends CommandValidator<ISetGitIdentity> {
    constructor() {
        super();
        this.ruleFor(c => c.email).notEmpty().withMessage('A git user email is required');
        this.ruleFor(c => c.name).notEmpty().withMessage('A git user name is required');
    }
}

/**
 * Command for setting the git identity worker containers commit as - one setting shared across the whole Planner deployment, injected into every worker as `PLANNER_GIT_USER_NAME` / `PLANNER_GIT_USER_EMAIL`.
 */
export class SetGitIdentity extends Command<ISetGitIdentity, GitIdentitySet> implements ISetGitIdentity {
    readonly route: string = '/api/git-hub/git-identity/setting';
    readonly validation: CommandValidator = new SetGitIdentityValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('email', String, false),
        new PropertyDescriptor('name', String, false),
    ];

    private _email!: string;
    private _name!: string;

    constructor() {
        super(GitIdentitySet, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The `git config user.email` to commit as.
     */
    get email(): string {
        return this._email;
    }

    set email(value: string) {
        this._email = value;
        this.propertyChanged('email');
    }
    /**
     * The `git config user.name` to commit as.
     */
    get name(): string {
        return this._name;
    }

    set name(value: string) {
        this._name = value;
        this.propertyChanged('name');
    }

    static use(initialValues?: ISetGitIdentity): [SetGitIdentity, SetCommandValues<ISetGitIdentity>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<SetGitIdentity, ISetGitIdentity>(SetGitIdentity, initialValues);
    }
}

/**
 * Event raised when the git identity worker containers commit as has been set.
 */
export class GitIdentitySet {

    /**
     * The `git config user.name` to commit as.
     */
    @field(String)
    name!: string;

    /**
     * The `git config user.email` to commit as.
     */
    @field(String)
    email!: string;
}
