// @generated by Cratis. Source: Planner.Issues.SettingModel.SetIssueModel, Planner.Issues.SettingModel.IssueModelOverridden. Time: 2026-08-09T09:18:49.3333770Z. Hash: BB54C2D09A77B660C5DB3812F74897F27031D1D0CFE75A0D6E7F468EEAFF26E2
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { field } from '@cratis/fundamentals';

/**
 * Command for overriding the model used to implement an issue. Takes precedence over any model an investigation suggested - pass {@link NotSet} to clear the override and fall back to the investigation's suggestion (or the scheduler's configured default).
 */
export interface ISetIssueModel {
    
    /**
     * The identity of the issue.
     */
    issue?: string;
    
    /**
     * The model to use, or {@link NotSet} to clear the override.
     */
    model?: string;
}


/**
 * Command for overriding the model used to implement an issue. Takes precedence over any model an investigation suggested - pass {@link NotSet} to clear the override and fall back to the investigation's suggestion (or the scheduler's configured default).
 */
export class SetIssueModel extends Command<ISetIssueModel, IssueModelOverridden> implements ISetIssueModel {
    readonly route: string = '/api/issues/setting-model';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('issue', String, false),
        new PropertyDescriptor('model', String, false),
    ];

    private _issue!: string;
    private _model!: string;

    constructor() {
        super(IssueModelOverridden, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The identity of the issue.
     */
    get issue(): string {
        return this._issue;
    }

    set issue(value: string) {
        this._issue = value;
        this.propertyChanged('issue');
    }
    /**
     * The model to use, or {@link NotSet} to clear the override.
     */
    get model(): string {
        return this._model;
    }

    set model(value: string) {
        this._model = value;
        this.propertyChanged('model');
    }

    static use(initialValues?: ISetIssueModel): [SetIssueModel, SetCommandValues<ISetIssueModel>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<SetIssueModel, ISetIssueModel>(SetIssueModel, initialValues);
    }
}

/**
 * Event raised when the model used to implement an issue has been explicitly set (or cleared back to automatic, when {@link Model} is {@link NotSet}).
 */
export class IssueModelOverridden {

    /**
     * The model to use, or {@link NotSet} for automatic.
     */
    @field(String)
    model!: string;
}
