// @generated by Cratis. Source: Planner.WeeklyDigests.Listing.WeeklyDigest, Planner.WeeklyDigests.Listing.WeeklyDigest. Time: 2026-08-19T16:16:25.3642610Z. Hash: AFC9F749251A03BA64DE39AE9AD29F3C9DB151EF6222B9C50E6AD13262C0B42F
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { ObservableQueryFor, QueryResultWithState, Sorting, Paging, ChangeSet } from '@cratis/arc/queries';
import { useObservableQuery, useObservableQueryWithPaging, useSuspenseObservableQuery, useSuspenseObservableQueryWithPaging, useChangeStream, SetSorting, SetPage, SetPageSize, ObservableQueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { field, Guid } from '@cratis/fundamentals';
import { WeeklyDigestStatus } from '../WeeklyDigestStatus';

class AllWeeklyDigestsSortBy {

    constructor(readonly query: AllWeeklyDigests) {
    }

}

class AllWeeklyDigestsSortByWithoutQuery {

}


/**
 * Observes every weekly digest.
 */
export class AllWeeklyDigests extends ObservableQueryFor<WeeklyDigest[]> {
    readonly route: string = '/api/weekly-digests/listing/all-weekly-digests';
    readonly queryName: string = 'Planner.WeeklyDigests.Listing.WeeklyDigest.AllWeeklyDigests';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: WeeklyDigest[] = [];
    private readonly _sortBy: AllWeeklyDigestsSortBy;
    private static readonly _sortBy: AllWeeklyDigestsSortByWithoutQuery = new AllWeeklyDigestsSortByWithoutQuery();

    constructor() {
        super(WeeklyDigest, true);
        this._sortBy = new AllWeeklyDigestsSortBy(this);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];


    get sortBy(): AllWeeklyDigestsSortBy {
        return this._sortBy;
    }

    static get sortBy(): AllWeeklyDigestsSortByWithoutQuery {
        return this._sortBy;
    }

    static use(sorting?: Sorting): [QueryResultWithState<WeeklyDigest[]>, SetSorting] {
        return useObservableQuery<WeeklyDigest[], AllWeeklyDigests>(AllWeeklyDigests, undefined, sorting);
    }

    static useWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<WeeklyDigest[]>, SetSorting, SetPage, SetPageSize] {
        return useObservableQueryWithPaging<WeeklyDigest[], AllWeeklyDigests>(AllWeeklyDigests, new Paging(0, pageSize), undefined, sorting);
    }

    static useSuspense(sorting?: Sorting): [QueryResultWithState<WeeklyDigest[]>, SetSorting] {
        return useSuspenseObservableQuery<WeeklyDigest[], AllWeeklyDigests>(AllWeeklyDigests, undefined, sorting);
    }

    static useSuspenseWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<WeeklyDigest[]>, SetSorting, SetPage, SetPageSize] {
        return useSuspenseObservableQueryWithPaging<WeeklyDigest[], AllWeeklyDigests>(AllWeeklyDigests, new Paging(0, pageSize), undefined, sorting);
    }

    static useChangeStream(getKey?: (item: WeeklyDigest) => unknown, sorting?: Sorting): ChangeSet<WeeklyDigest> {
        return useChangeStream<WeeklyDigest, AllWeeklyDigests>(AllWeeklyDigests, undefined, getKey, sorting);
    }

    static when(condition: boolean): ObservableQueryWhen<AllWeeklyDigests, WeeklyDigest[]> {
        return new ObservableQueryWhen<AllWeeklyDigests, WeeklyDigest[]>(AllWeeklyDigests, condition);
    }
}

/**
 * Read model for the weekly digest inbox - every digest a weekly job has posted, what the language model made of it, and whether it has been published.
 */
export class WeeklyDigest {

    /**
     * The weekly digest identity.
     */
    @field(Guid)
    id!: Guid;

    /**
     * The raw content as delivered.
     */
    @field(String)
    content!: string;

    /**
     * When the digest was received.
     */
    @field(Date)
    receivedAt?: Date;

    /**
     * The themes the language model extracted - `null` until analyzed.
     */
    @field(String, true)
    themes?: string[];

    /**
     * The description - the language model's suggestion, or a person's edit of it.
     */
    @field(String)
    description?: string;

    /**
     * Where the digest stands.
     */
    @field(Number)
    status!: WeeklyDigestStatus;

    /**
     * Where the digest was published - `null` until published.
     */
    @field(String, true)
    publishedTo?: string[];
}
