// @generated by Cratis. Source: Planner.Alerts.Deleting.DeleteAlert, Planner.Alerts.Deleting.AlertDeleted. Time: 2026-08-10T15:01:02.9193540Z. Hash: D484CB2A3C888F73EF89AE33C6A11B7E471D6D3EC352720F8D9994B36CDF5129
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';

/**
 * Command for taking an alert off the board entirely - for the noise a sending system should not have reported in the first place. The alert's history stays in the event log; only the row goes.
 */
export interface IDeleteAlert {
    
    /**
     * The identity of the alert.
     */
    alert?: string;
}


/**
 * Command for taking an alert off the board entirely - for the noise a sending system should not have reported in the first place. The alert's history stays in the event log; only the row goes.
 */
export class DeleteAlert extends Command<IDeleteAlert, AlertDeleted> implements IDeleteAlert {
    readonly route: string = '/api/alerts/deleting';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('alert', String, false),
    ];

    private _alert!: string;

    constructor() {
        super(AlertDeleted, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The identity of the alert.
     */
    get alert(): string {
        return this._alert;
    }

    set alert(value: string) {
        this._alert = value;
        this.propertyChanged('alert');
    }

    static use(initialValues?: IDeleteAlert): [DeleteAlert, SetCommandValues<IDeleteAlert>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<DeleteAlert, IDeleteAlert>(DeleteAlert, initialValues);
    }
}

/**
 * Event raised when an alert has been deleted.
 */
export class AlertDeleted {
}
