// @generated by Cratis. Source: Cratis.Chronicle.Auditing.Causation. Time: 2026-08-08T17:17:47.5182270Z. Hash: 2BD247052FDA09AD76CC1226EA57059181720C391ACF0ABA67743BF8774D0041
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { field } from '@cratis/fundamentals';

export class Causation {
    @field(Date)
    occurred!: Date;
    @field(String)
    type!: string;
    @field(Object)
    properties!: Record<string, string>;
}
