// @generated by Cratis. Source: Planner.Issues.Closing.CloseIssue, Planner.Issues.Closing.IssueClosed. Time: 2026-08-08T17:17:47.5182270Z. Hash: 5CC574AC6D3BCB22F752AB8FE08A791A72FFF6E9980880552FC7A16911F3EA11
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';

/**
 * Command for closing an issue - mirroring the issue being closed on GitHub.
 */
export interface ICloseIssue {
    
    /**
     * The identity of the issue.
     */
    issue?: string;
}


/**
 * Command for closing an issue - mirroring the issue being closed on GitHub.
 */
export class CloseIssue extends Command<ICloseIssue, IssueClosed> implements ICloseIssue {
    readonly route: string = '/api/issues/closing';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('issue', String, false),
    ];

    private _issue!: string;

    constructor() {
        super(IssueClosed, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The identity of the issue.
     */
    get issue(): string {
        return this._issue;
    }

    set issue(value: string) {
        this._issue = value;
        this.propertyChanged('issue');
    }

    static use(initialValues?: ICloseIssue): [CloseIssue, SetCommandValues<ICloseIssue>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<CloseIssue, ICloseIssue>(CloseIssue, initialValues);
    }
}

/**
 * Event raised when an issue has been closed on GitHub.
 */
export class IssueClosed {
}
