<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <AssemblyName>Cratis.AI.Specs</AssemblyName>
        <RootNamespace>Cratis.AI</RootNamespace>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);SA0001</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../Cratis.AI/Cratis.AI.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Cratis.Specifications" />
        <PackageReference Include="Cratis.Specifications.XUnit" />
        <PackageReference Include="FluentValidation" />
        <PackageReference Include="xunit" />
        <PackageReference Include="xunit.runner.visualstudio">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="NSubstitute" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
    </ItemGroup>
</Project>
