// @generated by Cratis. Source: Planner.WeeklyDigests.Receiving.ReceiveWeeklyDigest. Time: 2026-08-19T16:16:25.3642610Z. Hash: 2F10BC212C64AF98BF930C840CA9940118BB8D0B2DF4FB8157324EC0C3F65DBD
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command, CommandValidator } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { Guid } from '@cratis/fundamentals';

/**
 * Command for recording a weekly digest job's raw output - executed by the weekly digest webhook receiver.
 */
export interface IReceiveWeeklyDigest {
    
    /**
     * The raw content the job posted.
     */
    content?: string;
}

export class ReceiveWeeklyDigestValidator extends CommandValidator<IReceiveWeeklyDigest> {
    constructor() {
        super();
        this.ruleFor(c => c.content).notEmpty().withMessage('A weekly digest needs content');
    }
}

/**
 * Command for recording a weekly digest job's raw output - executed by the weekly digest webhook receiver.
 */
export class ReceiveWeeklyDigest extends Command<IReceiveWeeklyDigest, Guid> implements IReceiveWeeklyDigest {
    readonly route: string = '/api/weekly-digests/receiving';
    readonly validation: CommandValidator = new ReceiveWeeklyDigestValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('content', String, false),
    ];

    private _content!: string;

    constructor() {
        super(Guid, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The raw content the job posted.
     */
    get content(): string {
        return this._content;
    }

    set content(value: string) {
        this._content = value;
        this.propertyChanged('content');
    }

    static use(initialValues?: IReceiveWeeklyDigest): [ReceiveWeeklyDigest, SetCommandValues<IReceiveWeeklyDigest>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<ReceiveWeeklyDigest, IReceiveWeeklyDigest>(ReceiveWeeklyDigest, initialValues);
    }
}
