// @generated by Cratis. Source: Planner.Issues.ChangingLabels.ChangeIssueLabels, Planner.Issues.ChangingLabels.IssueLabelsChanged. Time: 2026-08-08T21:11:05.5434570Z. Hash: 1B54A02E5EF6EC15E88E4AE043F0F996D0E7AC4B27E00ADCBA31192B5EAEA34E
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { field } from '@cratis/fundamentals';

/**
 * Command for changing the labels of an issue - mirroring labeling on GitHub. The full label set travels as one fact; GitHub's labeled/unlabeled deliveries both carry the resulting set.
 */
export interface IChangeIssueLabels {
    
    /**
     * The identity of the issue.
     */
    issue?: string;
    
    /**
     * The labels the issue now has.
     */
    labels?: string[];
}


/**
 * Command for changing the labels of an issue - mirroring labeling on GitHub. The full label set travels as one fact; GitHub's labeled/unlabeled deliveries both carry the resulting set.
 */
export class ChangeIssueLabels extends Command<IChangeIssueLabels, IssueLabelsChanged> implements IChangeIssueLabels {
    readonly route: string = '/api/issues/changing-labels';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('issue', String, false),
        new PropertyDescriptor('labels', String, false),
    ];

    private _issue!: string;
    private _labels!: string[];

    constructor() {
        super(IssueLabelsChanged, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The identity of the issue.
     */
    get issue(): string {
        return this._issue;
    }

    set issue(value: string) {
        this._issue = value;
        this.propertyChanged('issue');
    }
    /**
     * The labels the issue now has.
     */
    get labels(): string[] {
        return this._labels;
    }

    set labels(value: string[]) {
        this._labels = value;
        this.propertyChanged('labels');
    }

    static use(initialValues?: IChangeIssueLabels): [ChangeIssueLabels, SetCommandValues<IChangeIssueLabels>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<ChangeIssueLabels, IChangeIssueLabels>(ChangeIssueLabels, initialValues);
    }
}

/**
 * Event raised when the labels of an issue have changed on GitHub - carries the full resulting set.
 */
export class IssueLabelsChanged {

    /**
     * The labels the issue now has.
     */
    @field(String, true)
    labels!: string[];
}
