// @generated by Cratis. Source: Planner.Repositories.Organizations.OrganizationTrackingPolicy. Time: 2026-08-19T16:32:25.3218460Z. Hash: CB7CC7125F4E58AA0FF231866A3D2593EED6D21C6B10FB5743E0BDC446602817
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

// eslint-disable-next-line header/header
/**
 * How an organization's repositories are tracked once added.
 */
export enum OrganizationTrackingPolicy {
    all = 0,
    selected = 1,
}
