// @generated by Cratis. Source: Planner.Repositories.Organizations.RepositoryDiscoveryStatus. Time: 2026-08-09T20:22:26.4216830Z. Hash: EE705DDFC09A2F0C22456CA24C2063FDEBC8575875A20DB7374A3CDF5115A71D
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

// eslint-disable-next-line header/header
/**
 * How far the Planner got discovering the repositories of an organization on GitHub.
 */
export enum RepositoryDiscoveryStatus {
    pending = 0,
    discovered = 1,
    failed = 2,
}
