name: Verify No Work Records

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  verify:
    uses: Cratis/Workflows/.github/workflows/verify-no-work-records.yml@f4106c468d4483905b18651a50d22349627a0bcc
