// @generated by Cratis. Source: Planner.PullRequests.UpdatingDetails.UpdatePullRequestDetails, Planner.PullRequests.UpdatingDetails.PullRequestDetailsChanged. Time: 2026-08-19T12:35:46.4721490Z. Hash: E2BD25DDBEEBE5ED1B88060649E59419DEDED61BB469BD1789FC43919764014A
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { field } from '@cratis/fundamentals';

/**
 * Command for updating the details of a pull request mirrored from GitHub - body, labels, draft state and branches. Every pull request webhook delivery carries the full current state of these, regardless of which action triggered it, so this is applied unconditionally rather than separately per action (`edited`, `labeled`, `unlabeled`, `synchronize`, `ready_for_review`, `converted_to_draft`).
 */
export interface IUpdatePullRequestDetails {
    
    /**
     * The branch the pull request merges into.
     */
    baseBranch?: string;
    
    /**
     * The markdown body of the pull request.
     */
    body?: string;
    
    /**
     * Whether the pull request is a draft.
     */
    draft?: boolean;
    
    /**
     * The branch the pull request merges from.
     */
    headBranch?: string;
    
    /**
     * The labels on the pull request.
     */
    labels?: string[];
    
    /**
     * The identity of the pull request.
     */
    pullRequest?: string;
}


/**
 * Command for updating the details of a pull request mirrored from GitHub - body, labels, draft state and branches. Every pull request webhook delivery carries the full current state of these, regardless of which action triggered it, so this is applied unconditionally rather than separately per action (`edited`, `labeled`, `unlabeled`, `synchronize`, `ready_for_review`, `converted_to_draft`).
 */
export class UpdatePullRequestDetails extends Command<IUpdatePullRequestDetails, PullRequestDetailsChanged> implements IUpdatePullRequestDetails {
    readonly route: string = '/api/pull-requests/updating-details';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('baseBranch', String, false),
        new PropertyDescriptor('body', String, false),
        new PropertyDescriptor('draft', Boolean, false),
        new PropertyDescriptor('headBranch', String, false),
        new PropertyDescriptor('labels', String, false),
        new PropertyDescriptor('pullRequest', String, false),
    ];

    private _baseBranch!: string;
    private _body!: string;
    private _draft!: boolean;
    private _headBranch!: string;
    private _labels!: string[];
    private _pullRequest!: string;

    constructor() {
        super(PullRequestDetailsChanged, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The branch the pull request merges into.
     */
    get baseBranch(): string {
        return this._baseBranch;
    }

    set baseBranch(value: string) {
        this._baseBranch = value;
        this.propertyChanged('baseBranch');
    }
    /**
     * The markdown body of the pull request.
     */
    get body(): string {
        return this._body;
    }

    set body(value: string) {
        this._body = value;
        this.propertyChanged('body');
    }
    /**
     * Whether the pull request is a draft.
     */
    get draft(): boolean {
        return this._draft;
    }

    set draft(value: boolean) {
        this._draft = value;
        this.propertyChanged('draft');
    }
    /**
     * The branch the pull request merges from.
     */
    get headBranch(): string {
        return this._headBranch;
    }

    set headBranch(value: string) {
        this._headBranch = value;
        this.propertyChanged('headBranch');
    }
    /**
     * The labels on the pull request.
     */
    get labels(): string[] {
        return this._labels;
    }

    set labels(value: string[]) {
        this._labels = value;
        this.propertyChanged('labels');
    }
    /**
     * The identity of the pull request.
     */
    get pullRequest(): string {
        return this._pullRequest;
    }

    set pullRequest(value: string) {
        this._pullRequest = value;
        this.propertyChanged('pullRequest');
    }

    static use(initialValues?: IUpdatePullRequestDetails): [UpdatePullRequestDetails, SetCommandValues<IUpdatePullRequestDetails>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<UpdatePullRequestDetails, IUpdatePullRequestDetails>(UpdatePullRequestDetails, initialValues);
    }
}

/**
 * Event raised when the details of a pull request mirrored from GitHub have changed.
 */
export class PullRequestDetailsChanged {

    /**
     * The markdown body of the pull request.
     */
    @field(String)
    body!: string;

    /**
     * The labels on the pull request.
     */
    @field(String, true)
    labels!: string[];

    /**
     * Whether the pull request is a draft.
     */
    @field(Boolean)
    draft!: boolean;

    /**
     * The branch the pull request merges from.
     */
    @field(String)
    headBranch!: string;

    /**
     * The branch the pull request merges into.
     */
    @field(String)
    baseBranch!: string;
}
